### DISCUSSION TITLE
Configuration issues regarding integration with Keycloak

### DISCUSSION THREAD

**Discussion by sgpublic** [pomerium/pomerium#5613] [Q&A] [answered]
Hi! I'm trying to integrate Keycloak with Pomerium, but I'm a little confused.

I have multiple services that need to be protected by Pomerium, and I want to use the different user to log in, and I also want the password filling service (such as Bitwarden) to distinguish which service I'm logging into.

So I created many realms in Keycloak, each realm contains a user and an OIDC client. The realm will be reflected in the URL, which helps the password filling service distinguish the user to be filled. But now I'm confused about how to configure Pomerium. Here is my Pomerium configuration:

```yaml
shared_secret: xxx
cookie_secret: xxx

idp_provider: oidc
idp_client_id: REPLACE_ME
idp_client_secret: REPLACE_ME

routes:
  - from: https://my-service.com
    to: http://my-service:5056
    idp_client_id: my-service
    idp_client_secret: xxx
    pass_identity_headers: true
```

Since different routes use different OIDC clients, and different OIDC clients are in different realms, I probably need to set a different `authenticate_service_url` for each route, but the documentation doesn't seem to mention how to achieve this.

When I start Pomerium directly using the above configuration, I visit `https://my-service.com`, and Pomerium's 403 Forbidden page is displayed in the browser, this is obviously something wrong.

Is it that Pomerium does not yet support this use case, or am I missing something?
