### DISCUSSION TITLE
SSH/RDP Access control support

### DISCUSSION THREAD

**Discussion by whitepiratebaku** [pomerium/pomerium#5675] [Q&A] [answered]
Hi, does pomerium support auhentication/authorization to SSH/RDP servers based on user access levels? user/groups will be managed by Azure Entra ID.

**Comment by bndgnpom** [comment, marked as answer]
Hi! Great question.

Yes — Pomerium supports authentication and authorization for non-HTTP protocols like SSH and RDP by tunneling them over HTTPS. You can define access policies based on user email, groups, or claims from your identity provider — including Azure Entra ID.

To make this work:

Use pomerium-cli or Pomerium Desktop to establish a TCP tunnel to the SSH or RDP target.

Define your route like this:

```
routes:
  from: tcp+https://ssh.example.com:3389
    to: tcp://ssh.internal.local:3389
    policy:
      - allow:
          or:
            - email:
                is: alice@company.com
            - claim/groups:
                is: "IT Admins"
```

Azure Entra groups are available as token claims. To use them, make sure group claims are included in your ID token:
https://learn.microsoft.com/en-us/entra/identity-platform/claims-mapping

Documentation references:

Non-HTTP protocol support: https://www.pomerium.com/docs/capabilities/non-http

Azure Entra (Azure AD) integration: https://www.pomerium.com/docs/integrations/user-identity/azure

SSH tunneling: https://www.pomerium.com/docs/capabilities/non-http/examples/ssh

RDP tunneling: https://www.pomerium.com/docs/capabilities/non-http/examples/rdp

Let me know if you have any additional questions, 

Ben
