### ISSUE TITLE
Host header does not get rewritten properly in 0.9.2

### ISSUE THREAD

**Issue by jaguarcy** [pomerium/pomerium#1012]
## What happened?
Example config:

```
policy:
- from: https://httpbin.corp.example.com
  to: http://192.168.1.17:8000
  allowed_domains:
    - pomerium.io
```

When visiting httpbin.corp.example.com/headers, I see
```
  "headers": {
...
    "Host": "httpbin.corp.example.com", 
...
  }
```

## What did you expect to happen?

When visiting httpbin/headers, expected to see:
```
  "headers": {
...
    "Host": "192.168.1.17:8000", 
...
  }
```

## What's your environment like?

- Pomerium version 0.9.2
- Server Operating System/Architecture/Cloud:
Pomerium and httpbin running in Docker containers on Synology DSM 6.2.3 (docker version 18.09.8).

## What's your config.yaml?

See above

## Additional context

This breaks some systems that are configured to expect a specific Host (in this example, Synology's own DSM web portal - returns a 404 if the Host isn't set correctly).

**Comment by desimone** [comment]
In V0.8.X we _always_ overwrote the host header to the destination hostname unless preserve policy is set.

https://github.com/pomerium/pomerium/blob/0-8-0/proxy/proxy.go#L225-L230

In v0.9.x we defer to envoy's [auto-host-rewrite](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-auto-host-rewrite) functionality

https://github.com/pomerium/pomerium/blob/f94f45d9a255cb2c4c4e8069a143b34e58d44c3d/internal/controlplane/xds_routes.go#L188-L190

which 

> is applicable only when the destination cluster for a route is of type strict_dns or logical_dns. Setting this to true with other cluster types has no effect

So in the case above where we have a policy that routes to a static IP the host is not rewritten. For example. 

```yaml
policy:
  - from: https://httpbin.imac.bdd.io
    to: http://httpbin.org
```

httpbin.org/headers

```json
{
  "headers": {
    "Host": "httpbin.org", 
  }
}
```

 
```yaml
policy:
  - from: https://httpbin.imac.bdd.io
    to: http://localhost #local httpbin
```

httpbin.org/headers

```json
{
  "headers": {
    "Host": "httpbin.imac.bdd.io", 
  }
}
```
