### ISSUE TITLE
Example configuration for local OIDC server for dev/testing

### ISSUE THREAD

**Issue by benjamingorman** [pomerium/pomerium#1042]
**Is your feature request related to a problem? Please describe.**

During development I would like to be able to functionally test my app using a locally-running Pomerium server as well as a local OIDC server featuring dummy credentials/dummy users for login.

**Describe the solution you'd like**

It would be great if the docs here https://www.pomerium.io/docs/identity-providers/ could give an example of how to configure a dummy OIDC server for use with Pomerium locally, such as https://hub.docker.com/r/qlik/simple-oidc-provider. Ideally an example `docker-compose` file could be provided so that a user of Pomerium could easily run these services locally.

**Describe alternatives you've considered**

Perhaps there's an alternative way to do this which I haven't seen in the docs? For testing of pomerium itself do you use something similar?

**Explain any additional use-cases**

**Additional context**

I tried to set this up myself using simple-oidc-provider but I am a complete Pomerium noob. Here's the configuration I used: although it isn't working (I get 500 errors from pomerium)

docker_compose.yaml
```
---
version: '3.4'
services:
  pomerium:
    image: pomerium/pomerium:v0.9.2
    restart: "always"
    environment:
      # Generate new secret keys. e.g. `head -c32 /dev/urandom | base64`
      - COOKIE_SECRET=V2JBZk0zWGtsL29UcFUvWjVDWWQ2UHExNXJ0b2VhcDI=
    volumes:
      - ./pomerium.yaml:/pomerium/config.yaml:ro
    ports:
      - 80:80
    networks:
      # This sets up an additional hostname for the service, which can be used as
      # the frontend hostname for the service we're managing auth for.
      default:
        aliases:
          - httpbin-login
    depends_on:
      - identityprovider

  httpbin:
    image: kennethreitz/httpbin:latest

  identityprovider:
    image: qlik/simple-oidc-provider
    environment:
      - CONFIG_FILE=/etc/identityprovider.json
      - USERS_FILE=/etc/identityprovider-users.json
    volumes:
      - ./identityprovider.json:/etc/identityprovider.json:ro
      - ./identityprovider-users.json:/etc/identityprovider-users.json:ro
    ports:
      - 9000:9000

  ```

pomerium.yaml
```
---
address: ":80"

authenticate_service_url: http://pomerium
insecure_server: true

# identity provider settings : https://www.pomerium.io/docs/identity-providers.html
idp_provider_url: http://identityprovider:9000
idp_provider: oidc
idp_client_id: foo
idp_client_secret: bar

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
cookie_secret: WwMtDXWaRDMBQCylle8OJ+w4kLIDIGd8W3cB4/zFFtg=

# https://www.pomerium.io/configuration/#policy
policy:
  - from: http://httpbin-login
    to: http://httpbin
    allowed_users:
      - bob@example.org
```

identityprovider.json
```
{
  "idp_name": "http://identityprovider:9000",
  "port": 9000,
  "client_config": [
    {
      "client_id": "foo",
      "client_secret": "bar",
      "redirect_uris": [
        "http://pomerium/oauth2/callback"
      ]
    }
  ],
  "claim_mapping": {
    "openid": [ "sub" ],
    "email": [ "email", "email_verified" ],
    "profile": [ "name", "nickname" ]
  }
}
```

identityprovider-users.json
```
[
  {
    "id": "SIMPLE_OIDC_USER_ALICE",
    "email": "alice@example.org",
    "email_verified": true,
    "name": "Alice Smith",
    "nickname": "al",
    "password": "abc",
    "groups": ["Everyone", "Engineering"]
  },
  {
    "id": "SIMPLE_OIDC_USER_BOB",
    "email": "bob@example.org",
    "email_verified": true,
    "name": "Bob Smith",
    "nickname": "bobby",
    "password": "abc",
    "groups": ["Everyone", "Sales"]
  }
]
```
