### ISSUE TITLE
error creating authenticate service: authenticate: 'COOKIE_SECRET' invalid cryptutil: got 0 bytes but want 32

### ISSUE THREAD

**Issue by vorpentine** [pomerium/pomerium#1044]
## What happened?
pomerium_1  | {"level":"fatal","error":"error creating authenticate service: authenticate: 'COOKIE_SECRET' invalid cryptutil: got 0 bytes but want 32","time":"2020-07-07T14:41:27Z","message":"cmd/pomerium"}

## What did you expect to happen?
Working

## How'd it happen?

sudo docker-compose up

## What's your environment like?

Docker-
```
version: "3"
services:
  pomerium:
    image: pomerium/pomerium:latest
    environment:
      # Generate new secret keys. e.g. `head -c32 /dev/urandom | base64`
      - mybase64string
    volumes:
      # Mount your domain's certificates : https://www.pomerium.io/docs/reference/certificates
      - /home/bern/.pom/fullchain.pem:/pomerium/cert.pem:ro
      - /home/bern/.pom/privkey.pem:/pomerium/privkey.pem:ro
      # Mount your config file : https://www.pomerium.io/docs/reference/reference/
      - /home/bern/.pom/config.yaml:/pomerium/config.yaml:ro
    ports:
      - 443:443
```

## What's your config.yaml?

```config.yaml
# Main configuration flags : https://www.pomerium.io/docs/reference/reference/

# address: ":8443" # optional, default is 443

#pomerium_debug: true # optional, default is false
# service: "all" # optional, default is all
# log_level: info # optional, default is debug

#authenticate_service_url: https://authenticate.corp.beyondperimeter.com

#autocert: true
#insecure_server: true
certificates:
  - cert: "/pomerium/cert.pem"
    key: "/pomerium/privkey.pem"

## GOOGLE
idp_provider: "google"
#idp_provider_url: "https://accounts.google.com" # optional for google
idp_client_id: "myid.apps.googleusercontent.com"
idp_client_secret: "mysec"

# Proxied routes and per-route policies are defined in a policy block
policy:
  - from: https://mydomain.com
    to: http://192.168.8.130:80
    allowed_users:
      - myaccount@gmail.com
```

## What did you see in the logs?

```logs
Starting pom_pomerium_1 ... done
Attaching to pom_pomerium_1
pomerium_1  | {"level":"info","version":"0.9.2-1592838263+3b74053","time":"2020-07-07T14:41:27Z","message":"cmd/pomerium"}
pomerium_1  | {"level":"info","port":"32895","time":"2020-07-07T14:41:27Z","message":"gRPC server started"}
pomerium_1  | {"level":"info","port":"43935","time":"2020-07-07T14:41:27Z","message":"HTTP server started"}
pomerium_1  | {"level":"debug","service":"envoy","location":"/tmp/.pomerium-envoy/envoy-config.yaml","time":"2020-07-07T14:41:27Z","message":"wrote config file to location"}
pomerium_1  | {"level":"fatal","error":"error creating authenticate service: authenticate: 'COOKIE_SECRET' invalid cryptutil: got 0 bytes but want 32","time":"2020-07-07T14:41:27Z","message":"cmd/pomerium"}
pom_pomerium_1 exited with code 1
```
