### ISSUE TITLE
Initial Service Redirect Not Handle Correctly

### ISSUE THREAD

**Issue by devstein** [pomerium/pomerium#1113]
## What happened?
I'm using Pomerium with Istio to authenticate our internal Airflow service. The Istio virtual service send all traffic to the Pomerium proxy. The rule looks like the following:

```yaml
          - from: https://airflow.internal.com
            to: http://airflow-web.airflow.svc.cluster.local:8080
```
The issue is that Airflow redirects traffic from `/` to `/admin/` giving a 302 response to Pomerium. Pomerium then redirects the user's browser to `http://airflow-web.airflow.svc.cluster.local:8080/admin/` instead of the expected  `https://airflow.internal.com/admin/`

## What did you expect to happen?

Expected to be redirected to  `https://airflow.internal.com/admin/`

## How'd it happen?

1. Navigate to `https://airflow.internal.com/`
2. Got redirect to `http://airflow-web.airflow.svc.cluster.local:8080/admin/`

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): `v0.8.4`
- Server Operating System/Architecture/Cloud: AWS/K8s/Google Chrome

## What's your config.yaml?

```config.yaml
          - from: https://airflow.internal.com
            to: http://airflow-web.airflow.svc.cluster.local:8080
```

## What did you see in the logs?

I fixed the issue and no longer have the exact logs but the response code from the initial redirect to Airflow was `302` opposed to the usual `200`

## Additional context

I fixed the issue by handling the redirect via Istio

```yaml
    #  Airflow redirects from
    # / to /admin/  and  /admin to  /admin/
    # This breaks Pomerium, so we rewrite it before
    # so Pomerium only receives /admin/
    - match:
        - uri:
            exact: /
        - uri:
            exact: /admin
      redirect:
        uri: /admin/
```
