### ISSUE TITLE
refactor configuration handling

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium#115]
As initially discussed in #89 - I'd like to propose refactoring configuration handling from [pomerium/envconfig](/pomerium/envconfig) to [spf13/viper](/spf13/viper)  I see this as a precursor to #89, since reloading of policy naturally leads into how run time configuration is brought into the proxy and authz services.

- Brings in support for a variety of additional config storage formats
- Has vetted handling of live configuration notifications to support #89 
- Should reduce code surface area in pomerium

### Changes

* Non-breaking: Add support for a new configuration file located at /etc/pomerium/config.[yaml|toml|json]
  * This file can contain _all_ configuration options, including inline policy
* Non-breaking: Configuration file location can be overridden with an env_var
* Breaking: Deprecate POLICY_FILE and require policy to be defined as either a base64 encoded env var or as part of config file policy key

### Config file example

```yaml
authenticate_service_url: https://authenticate.corp.example.com
authorize_service_url: https://authorize.corp.example.com
shared_secret: 9wiTZq4qvmS/plYQyvzGKWPlH/UBy0DMYMA2x/zngrM= 
cookie_secret: uPGHo1ujND/k3B9V6yr52Gweq3RRYfFho98jxDG5Br8=
idp_provider: "google"
idp_client_id: "REPLACE-ME.googleusercontent.com"
idp_client_secret: "REPLACEME"
policy:
    - from: httpbin.corp.beyondperimeter.com
    to: http://httpbin
    allowed_domains:
        - pomerium.io
    cors_allow_preflight: true
    timeout: 30s
    - from: external-httpbin.corp.beyondperimeter.com
    to: httpbin.org
    allowed_domains:
        - gmail.com
    - from: weirdlyssl.corp.beyondperimeter.com
    to: http://neverssl.com
    allowed_users:
        - bdd@pomerium.io
    allowed_groups:
        - admins
        - developers
    - from: hello.corp.beyondperimeter.com
    to: http://hello:8080
    allowed_groups:
        - admins
```

## Internal Spec

The plan is to continue using a struct unmarshalled from the configuration to represent options. 

At a high level, there are two approaches to the refactor:

1. Extend the top level Options struct to support all options and pass this along to each service.  

    * Basic validation and loading can be done in a single location
    * Individual services can still validate the fields they're interested in
    * Makes the largest reduction in maintained/duplicate Service level code
    * Options shared across services don't need to be added to multiple service scope structs

2.  Retain current pattern of each scope (global level + 1 per service) initializing their own scoped Options structs

    * The change is smaller and retains more of existing call patterns
    * There is explicit struct level documentation of which fields are required by which service outside of validation

I prefer the first approach but, as it is a bit of a change from the current structure, I'm quite open to input or questions.  @desimone please weigh in with any preference or guidance here and I can start working on the PR.
