### ISSUE TITLE
proxy: Proxy configuration file preprocessed incorrectly, creating incorrect routes

### ISSUE THREAD

**Issue by nareddyt** [pomerium/pomerium#132]
## Bug Description

When configuring a proxy locally with a `policy.yaml` file, some of the routes created are incorrect. This leads to the proxy routing requests incorrectly.

### Environment 

- Running the source locally. Latest commit to the `master` branch
- Windows 10 with Windows Subsystem for Linux

### Impact

Minimal: I cannot test my fix to #129 with this bug in place. However, I believe I have a fix for this bug (below).

### Root Cause

Specifically, I noticed that [Proxy::routeConfigs](https://github.com/pomerium/pomerium/blob/3eff6cce13e51f97e47cd2c4aacbc82fe9646bcb/proxy/proxy.go#L117) is incorrectly initialized. In the image below, notice that two routes (with the configuration file given below) have the same memory address for the `policy` - highlighted in red. This should not occur, as each policy should be unique.

![image](https://user-images.githubusercontent.com/11142171/58129623-25e67480-7be8-11e9-9ad7-caa6eb115627.png)

After some further digging, I noticed issues with memory addresses [in this section of code](https://github.com/pomerium/pomerium/blob/3eff6cce13e51f97e47cd2c4aacbc82fe9646bcb/proxy/proxy.go#L180). `p.Handle(route.Source.Host, handler, &route)`, where the last argument is a pointer to route. However, the proxy must store **a copy of the route** for later requests outside of this function.

### Proposed Fix

I will make a PR with the fix. The main modification would be [here](https://github.com/pomerium/pomerium/blob/3eff6cce13e51f97e47cd2c4aacbc82fe9646bcb/proxy/proxy.go#L122) to store policies as a copy of the data, instead of pointers that do not exist after the main function exits.

### Policy Configuration

```yaml
- from: hello1.homelab.tejunareddy.com
  to: http://localhost:8081
  allowed_users:
    - tejunareddy@gmail.com
- from: hello2.homelab.tejunareddy.com
  to: http://localhost:8082
  allowed_users:
    - not_a_user@yahoo.com
- from: hello3.homelab.tejunareddy.com
  to: http://localhost:8083
  allow_public_unauthenticated_access: true
```

### Repro Steps

1. Start the server locally with this file
2. All requests to hello1.homelab.tejunareddy.com, hello2.homelab.tejunareddy.com, and hello3.homelab.tejunareddy.com are handled by the 3rd route, so they all redirect to http://localhost:8003. 

### Expected Behavior

It's expected that each route is handled by the correct proxy handler.
