### ISSUE TITLE
authorize: allow access based on arbitrary identity claims

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#1375]
**Is your feature request related to a problem? Please describe.**

Today, we have a limited set of ways a user can define their access control policy with declarative `yaml`. Namely, oeprators can set access based on `allowed_users`, `allowed_groups`, and `allowed_users`.  

This feature would be paricularly useful for users :

- with [custom claims](https://openid.net/specs/openid-connect-core-1_0.html#AdditionalClaims) (for example, we've seen cases where users have alternative values for user id) 
- are using a OIDC bridge like Dex (where groups are pseudo-added to the [id_token](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims))

What's especially confusing  -- which, I am responsible for -- is that `allowed_users` corresponds to the user's `email` claim, not the `sub` claim which is meant to be a globally unique user identifier (RFC 7519). 

**Describe the solution you'd like**

We should allow operators to allow access to user's based on the equality of arbitrary claims. For example, a policy could look like...

```yaml
policy:
  - from: https://httpbin.localhost.pomerium.io
    to: http://httpbin.org
    allowed_domains:
      - pomerium.com
      - gmail.com
    allowed_idp_claims:
      sub:
        - 111432655977273150308
        - 111432655977273152308
      groups:
        - dev@pomerium.com
        - admin@pomerium.com
      custom_claim:
        - "anything in your id_token, really"
        - "https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse"

```

To be clear, this would only before claims data that exists as part of the _original_ idp provided identity_token / jwt. This would _not_ be for writing policy against arbitrary datastore data. 

**Describe alternatives you've considered**

**Explain any additional use-cases**

**Additional context**

This would likely solve several issues including:

- https://github.com/pomerium/pomerium/issues/1112
- https://github.com/pomerium/pomerium/issues/834
- https://github.com/pomerium/pomerium/issues/1342 (For IdP claims only, not external auth sources or dynamic access policy)

**Comment by desimone** [comment]
Closing. After a discussion with the team, I think it makes more sense to allow arbitrary adding and removal of claims in the attestation header directly. 

See: https://github.com/pomerium/pomerium/issues/1376#issuecomment-689054282

**Comment by sly-net** [comment]
I think this is a first move towards more fine-grained authorization policies.

For my personal needs (as a Dex user), I'd like to be able to allow specific user_id to access backend applications.

```json
"federated_claims": {
  "connector_id": "ldap",
  "user_id": "bob"
}
```

I'm not sure what the Pomerium policy should look like. Something like this?
```yaml
policy:
  - from: https://httpbin.localhost.pomerium.io
    to: http://httpbin.org
    allowed_domains:
      - pomerium.com
      - gmail.com
    allowed_idp_claims:
      sub:
        - 111432655977273150308
        - 111432655977273152308
      groups:
        - dev@pomerium.com
        - admin@pomerium.com
      federated_claims:
        user_id:
          - alice
          - bob
```

In the future, I see a more advanced way to specify authorization policies. The goal again is to write fine-grained authorization policies. I can imagine using a declarative language. Simple policies should remain simple to write though. It seems like [Google Cloud](https://cloud.google.com/iam/docs/reference/rest/v1/Policy), [AWS](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_grammar.html) and [Azure](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure), all went for JSON. Another alternative  is [Rego](https://www.openpolicyagent.org/docs/latest/policy-language/).

**Comment by calebdoxsey** [comment]
@sly-net I've merged a change to master in https://github.com/pomerium/pomerium/pull/1542 that should provide this functionality. It matches the example you provided so hopefully should work if you want to try it. I've only tested it with azure, which also has many custom claims, and it worked for that. Let me know if you have any trouble.

**Comment by sly-net** [comment]
@calebdoxsey I've just tested your change. It works very well. Good improvement! Thanks :raised_hands:
```yaml
allowed_idp_claims:
  federated_claims.user_id:
    - alice
    - bob
```
