### ISSUE TITLE
Traefik Forward Auth Example doesn't seem to work

### ISSUE THREAD

**Issue by branchmispredictor** [pomerium/pomerium#1417]
## What happened?

Upgraded from v0.9.2 to v0.10.3. Existing config to use pomerium as fwdauth proxy in Traefik no longer works. Settings are essentially identical to the example here: https://github.com/pomerium/pomerium/tree/master/examples/traefik.

### Reproduction steps:

1. Visit https://whoami.domain in browser
2. Redirected to https://authentication.domain
3. Redirect to Google SAML page, then login
4. Redirected to http://whoami.domain/?pomerium_expiry=XXXXXX&pomerium_issued=XXXXXX&pomerium_redirect_uri=http%3A%2F%2Fwhoami.domain%2F&pomerium_session_encrypted=XXXXX&pomerium_signature=XXXXX (note this is now http instead of https)
5. Results in 404 page not found.

### Fixing manually

Manually changing the above url to use https in both the url itself and the `pomerium_redirect_uri` field finishes the auth process and allows passage to the actual service.

## What did you expect to happen?

Normal authentication flow without requiring manual editing of url params.

## What did you see in the logs?

```logs
8:41PM DBG "[C6][S9291447250879411976] request headers complete (end_stream=true):\n\':authority\', \'pomerium\'\n\':path\', \'/\'\n\':method\', \'GET\'\n\'user-agent\', \'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:79.0) Gecko/20100101 Firefox/79.0\'\n\'accept\', \'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\'\n\'accept-encoding\', \'gzip, deflate, br\'\n\'accept-language\', \'en-US,en;q=0.5\'\n\'cookie\', \'_pomerium=XXXXX\'\n\'upgrade-insecure-requests\', \'1\'\n\'x-forwarded-for\', \'X.X.X.X\'\n\'x-forwarded-host\', \'whoami.domain\'\n\'x-forwarded-method\', \'GET\'\n\'x-forwarded-port\', \'8890\'\n\'x-forwarded-proto\', \'https\'\n\'x-forwarded-server\', \'82e1fd1f1aac\'\n\'x-forwarded-uri\', \'/\'\n\'x-real-ip\', \'X.X.X.X\'" name=http service=envoy

8:41PM DBG "[C6][S9291447250879411976] router decoding headers:\n\':authority\', \'pomerium\'\n\':path\', \'/\'\n\':method\', \'GET\'\n\':scheme\', \'http\'\n\'user-agent\', \'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:79.0) Gecko/20100101 Firefox/79.0\'\n\'accept\', \'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\'\n\'accept-encoding\', \'gzip, deflate, br\'\n\'accept-language\', \'en-US,en;q=0.5\'\n\'cookie\', \'_pomerium=XXXXXXX\'\n\'upgrade-insecure-requests\', \'1\'\n\'x-forwarded-for\', \'X.X.X.X,Y.Y.Y.Y\'\n\'x-forwarded-host\', \'whoami.domain\'\n\'x-forwarded-method\', \'GET\'\n\'x-forwarded-port\', \'8890\'\n\'x-forwarded-proto\', \'http\'\n\'x-forwarded-server\', \'82e1fd1f1aac\'\n\'x-forwarded-uri\', \'/\'\n\'x-real-ip\', \'X.X.X.X\'\n\'x-envoy-external-address\', \'Y.Y.Y.Y\'\n\'x-request-id\', \'5fc4ab96-01f4-4171-a6d2-ce123e9c052c\'\n\'x-envoy-expected-rq-timeout-ms\', \'15000\'" name=router service=envoy

8:41PM INF authorize check allow=false check-request-id=5fc4ab96-01f4-4171-a6d2-ce123e9c052c groups=[] headers={"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","Accept-Encoding":"gzip, deflate, br","Accept-Language":"en-US,en;q=0.5","Content-Length":"0","Cookie":"_pomerium=XXXXXXX","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:79.0) Gecko/20100101 Firefox/79.0","X-Envoy-Expected-Rq-Timeout-Ms":"15000","X-Envoy-External-Address":"Y.Y.Y.Y","X-Forwarded-For":"X.X.X.X,Y.Y.Y.Y","X-Forwarded-Host":"whoami.domain","X-Forwarded-Method":"GET","X-Forwarded-Port":"8890","X-Forwarded-Proto":"http","X-Forwarded-Server":"82e1fd1f1aac","X-Forwarded-Uri":"/","X-Real-Ip":"X.X.X.X","X-Request-Id":"5fc4ab96-01f4-4171-a6d2-ce123e9c052c"} host=whoami.domain method=GET path= query= request-id=05ea86c5-d3a7-49b1-b0af-b67644bd5906 service=authorize status=401 user=

8:41PM DBG http-request X-Forwarded-For=["X.X.X.X,Y.Y.Y.Y"] X-Forwarded-Host=["whoami.domain"] X-Forwarded-Method=["GET"] X-Forwarded-Port=["8890"] X-Forwarded-Proto=["http"] X-Forwarded-Server=["82e1fd1f1aac"] X-Forwarded-Uri=["/"] X-Real-Ip=["X.X.X.X"] duration=8.733077 email= groups= host=pomerium ip=127.0.0.1 method=GET path=/ request-id=5fc4ab96-01f4-4171-a6d2-ce123e9c052c size=416 status=302 user= user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:79.0) Gecko/20100101 Firefox/79.0"
```

## Additional context
In the above logs, it looks like envoy overwrote `x-forwarded-proto: https` with `x-forwarded-proto: http`

**Comment by travisgroth** [comment]
Hi @branchmispredictor - can you share your forward auth middleware configuration please?

**Comment by branchmispredictor** [comment]
docker-compose.yaml:
```yaml
version: "3.3"

services:
    traefik:
        image: "traefik:v2.2"
        container_name: "traefik"
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--api.dashboard=true"
            - "--accesslog=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.websecure.address=:8890"
            - "--entrypoints.websecure.forwardedHeaders.insecure"
            - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
            - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=namecheap"
            - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
            - "8890:8890"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.rule=Host(`traefik.domain`)"
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.traefik.tls.certresolver=myresolver"
            - "traefik.http.routers.traefik.tls.domains[0].main=domain"
            - "traefik.http.routers.traefik.tls.domains[0].sans=*.domain"
            - "traefik.http.routers.traefik.entrypoints=websecure"

  whoami:
        image: "kennethreitz/httpbin"
        labels:
            - "traefik.http.middlewares.pomerium.forwardauth.authResponseHeaders=x-pomerium-jwt-assertion"
            - "traefik.http.middlewares.pomerium.forwardauth.address=http://pomerium/"
            - "traefik.http.middlewares.pomerium.forwardauth.trustForwardHeader=true"
            - "traefik.http.routers.whoami.middlewares=pomerium@docker"
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`whoami.new.totoro.epifano.codes`)"
            - "traefik.http.routers.whoami.entrypoints=websecure"
            - "traefik.http.routers.whoami.tls.certresolver=myresolver"

  pomerium:
        #image: pomerium/pomerium:v0.9.2
        image: pomerium/pomerium:v0.10.3
        volumes:
            - ./config/pomerium/config.yaml:/pomerium/config.yaml:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pomerium.rule=Host(`authenticate.domain`)"
            - "traefik.http.routers.pomerium.entrypoints=websecure"
            - "traefik.http.routers.pomerium.tls.certresolver=myresolver"
        expose:
          - 80
```

pomerium config:
```yaml
log_level: debug
address: :80
pomerium_debug: true
cookie_secret: SECRET
shared_secret: SECRET

idp_provider: "google"
idp_client_id: "SECRET"
idp_client_secret: "SECRET"

insecure_server: true
forward_auth_url: http://pomerium
authenticate_service_url: https://authenticate.domain

policy:
    - from: https://whoami.domain
      to: http://whoami
      allowed_users:
          - email@gmail.com
```
