### ISSUE TITLE
Local development route config

### ISSUE THREAD

**Issue by nareddyt** [pomerium/pomerium#146]
### Problem Description

When working on the pomerium source code while travelling, I'm not sure how to configure the routes in the config file. Normally when I'm at home with port forwarding set-up on my router, I can configure `from` with fully-qualified domain names:

```yaml
- from: hello.homelab.tejunareddy.com
  to: http://localhost:8081
  allow_public_unauthenticated_access: true
```

However, this doesn't work when travelling, as I cannot setup port forwarding on other routers. All requests to pomerium would have to be directly to https://localhost:443.

### Questions

- Is there an undocumented way of configuring the routes to work without port forwarding? This would be super helpful for local development.
- If not, is this a feature that needs to be supported?

### Additional Context

**Version**: Latest commit on master

As always, I can help with this feature if needed.

**Comment by desimone** [comment]
I'm honestly not sure as I had not considered that use case before.  Off the top of my head, I actually would expect this would work without any special configuration since, to my knowledge,  we aren't doing port stripping. Assuming all the certificates are trusted and valid. What are you seeing when you do something like...

```yaml
- from: https://localhost:443
  to: http://localhost:8081
  allow_public_unauthenticated_access: true
```

**Comment by nareddyt** [comment]
Ah, it actually works if I remove the port number on the `from` field. It seems like the `host` variable on [this line](https://github.com/pomerium/pomerium/blob/191015a0edb2961ace40210052488edcb555c4cf/proxy/handlers.go#L31) does not include the port number (as expected by the name I guess).

```yaml
- from: https://localhost
  to: http://localhost:8081
  allow_public_unauthenticated_access: true
```

I'm assuming there's no easy way to proxy requests between 2 different resources like this. Shouldn't be a big deal, as long as I can send traffic to pomerium.

Do we have any documentation for pomerium developers? I can add this piece to that section for future reference.
