### ISSUE TITLE
Weird Parsing Issue When Using Podman

### ISSUE THREAD

**Issue by bcstinch** [pomerium/pomerium#1492]
## What happened?
Whenever I try a very simple pomerium config to enable gitlab as an identity problem I am getting weird parsing issues:
```
8:08PM WRN invalid service account for github directory provider error="unexpected end of JSON input" provider=github service=directory
8:08PM WRN no directory provider implementation found, disabling support for groups provider=github
8:08PM WRN failed to read databroker CA file error="open : no such file or directory"
```
With no idp_service_account set

```
8:05PM WRN invalid service account for github directory provider error="invalid character 'u' looking for beginning of value" provider=github service=directory
8:05PM WRN no directory provider implementation found, disabling support for groups provider=github
8:05PM WRN failed to read databroker CA file error="open : no such file or directory"
```
With idp_service_account set

## What did you expect to happen?
A successful authentication to my gitlab app

## How'd it happen?

Running pomerium with podman with the following config mounted:
```
pomerium_debug: true
address: :6969
cookie_secret: SECRET

idp_provider: "gitlab"
idp_client_id: "SECRET"
idp_client_secret: "SECRET"
#idp_service_account: "SECRET"

certificates:
 - cert: "/pomerium/nginx.pem"
   key: "/pomerium/nginx-key.pem"

forward_auth_url: http://fwdauth.tendie.haus
authenticate_service_url: https://authenticate.tendie.haus

policy:
  - from: https://collect.tendie.haus
    to: https://10.0.0.202:8989
```

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`):
latest from dockerhub
- Server Operating System/Architecture/Cloud:
Fedora Server

## What's your config.yaml?
See above

## What did you see in the logs?

See above

## Additional context

Not sure if this is a gitlab issue or a specific podman issue. Podman is a more secure docker replacement.
