### ISSUE TITLE
[FR] can I use subpath style

### ISSUE THREAD

**Issue by Hokwang** [pomerium/pomerium#1499]
Hi,

I am deploying pomerium first time, and find out one problem.

In my case, I can't use `a.domain, b.domain, c.domain`, because in my company 1) does not provide well and 2) does not provide ssl.

so how about provide subpath style like my.domain.com/pomerium ?
it will be more easy for handling ingress too.

Thanks,

**Comment by calebdoxsey** [comment]
@Hokwang you can specify a path in the policy: https://www.pomerium.io/reference/#path

In the master branch you can also rewrite the path with `prefix_rewrite`: https://master.docs.pomerium.io/reference/#prefix-rewrite

I'm going to close this issue because I believe this feature is already implemented, but if we're missing something feel free to comment and we can re-open.

**Comment by Hokwang** [comment]
@calebdoxsey thanks for your comment. but it doesn't mean the `policy path`. I mean ingress path like

```
  spec:
    rules:
    - host: pomerium.my.company.net
      http:
        paths:
        - backend:
            serviceName: pomerium-stage-proxy
            servicePort: http
    - host: forwardauth.my.company.net
      http:
        paths:
        - backend:
            serviceName: pomerium-stage-proxy
            servicePort: http
    - host: authorize.my.company.net
      http:
        paths:
        - backend:
            serviceName: pomerium-stage-authorize
            servicePort: http
    - host: authenticate.my.company.net
      http:
        paths:
        - backend:
            serviceName: pomerium-stage-authenticate
            servicePort: http
    tls:
    - hosts:
      - authenticate.my.company.net
      - forwardauth.my.company.net
      - pomerium.my.company.net
```

In my case, I have only my.company.net, not *.my.company.net, and can not create sub domain of my.company.net.
