### ISSUE TITLE
identity/oidc: could not connect to oidc - x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by enenum** [pomerium/pomerium#1561]
## What happened?
Error: cmd/pomerium error="error creating authenticate service: identity/oidc: could not connect to oidc: Get \"https://<idp keycloak url>/.well-known/openid-configuration\": x509: certificate signed by unknown authority"

## What did you expect to happen?
Pomerium to connect to IDP without problem

## How'd it happen?
```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pom
  name: pomerium
  labels:
    app: pomerium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pomerium
  template:
    metadata:
      labels:
        app: pomerium
    spec:
      containers:
        - name: pomerium
          image: pomerium/pomerium:master
          ports:
            - containerPort: 30443
          env:
            - name: ADDRESS
              value: "0.0.0.0:30443"
            - name: AUTHENTICATE_SERVICE_URL
              value: "https://authenticate.localhost.pomerium.io:30443"
            - name: CERTIFICATE_AUTHORITY_FILE
              value: /tls/ca.crt
            - name: CLIENT_CA_FILE
              value: /tls/ca.crt
            - name: CERTIFICATE_FILE
              value: /tls/tls.crt
            - name: CERTIFICATE_KEY_FILE
              value: /tls/tls.key
            - name: COOKIE_SECRET
              value: "hllnCm3SvICRGH0Ey6YPdaF3baJajclVobTw4rAC+TI=" # $(head -c32 /dev/urandom | base64 -w 0)
            - name: IDP_PROVIDER
              value: oidc
            - name: IDP_PROVIDER_URL
              value: https://<idp url>
            - name: IDP_SERVICE_ACCOUNT
              value: default.hiota
            - name: IDP_CLIENT_ID
              value: "hiota"
            - name: IDP_CLIENT_SECRET
              value: "Change11me"
            - name: LOG_LEVEL
              value: debug
            - name: POMERIUM_DEBUG
              value: 'true'
            - name: INSECURE_SERVER
              value: 'true'
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tls
              mountPath: /tls
          args:
            - --config=/config/config.yaml
      volumes:
        - name: config
          secret:
            secretName: pomerium-policy
        - name: tls
          secret:
            secretName: pomerium-certs
```
1. Made a pod with this and the supporting resources
2. Get the can't connect to IDP for unknown CA error

## What's your environment like?
k8s 1.18.5 on RHEL 7.5 in a VM
keycloak IDP
Testing out dashbaord auth
Made certs for pomerium from same CA as keycloak has
Provided the CA in client ca and CERTIFICATE AUTHORITY
Set insecure_server
Still can't get beyond this unknow authority error

- Pomerium version (retrieve with `pomerium --version`):
master pulled from 2020-10-28 docker image

- Server Operating System/Architecture/Cloud:
k8s 1.18.5 on RHEL 7.5 in a VM

## What's your config.yaml?
```config.yaml
  config.yaml: |-
    policy:
      - from: https://pomerium.pom
        to: https://k8s-dash.pom:8443
        allowed_users:
          - user@domain.com
-```

## What did you see in the logs?

```logs
k -n pom logs pomerium-84c9dc87f-vl989
{"level":"info","version":"v0.10.0+93c2572","time":"2020-10-29T19:32:22Z","message":"cmd/pomerium"}
{"level":"warn","time":"2020-10-29T19:32:22Z","message":"config: cache url will be deprecated in v0.11.0"}
{"level":"info","addr":"127.0.0.1:5443","time":"2020-10-29T19:32:22Z","message":"internal/grpc: grpc with insecure"}
7:32PM INF gRPC server started port=33552
7:32PM INF HTTP server started port=38759
7:32PM DBG wrote config file to location location=/tmp/.pomerium-envoy/envoy-config.yaml service=envoy
7:32PM INF envoy: starting envoy process
7:32PM INF internal/grpc: grpc with insecure addr=127.0.0.1:5443
7:32PM FTL cmd/pomerium error="error creating authenticate service: identity/oidc: could not connect to oidc: Get \"<idp URL>/.well-known/openid-configuration\": x509: certificate signed by unknown authority"
```

## Additional context

I can reach the IDP URL with curl -k fine - it seems to me a matter of pomerium not having the cert by which to trust.
Of the CA settings provided (CLIENT_CA_FILE and CERTIFICATE_AUTHORITY_FILE) the all do not seem to help. How is this supposed to work?
