### ISSUE TITLE
Forward auth broken in v0.11.0

### ISSUE THREAD

**Issue by sylr** [pomerium/pomerium#1674]
## What happened?

I've upgraded all pomerium components to `v0.11.0`.

My Traefik dashboards protected with the forward auth middleware started to entered in **infinite redirection loop**.

Reverting the proxy to `v0.10.6` fixed the issue.

<img width="1680" alt="Fullscreen_11_12_2020_11_31" src="https://user-images.githubusercontent.com/153052/101894257-31243b00-3ba6-11eb-9eb3-0b407d1179a8.png">

I'd be happy to do a Zoom or such to debug with you if you need it. Ping me on slack.

**Comment by desimone** [comment]
Thanks @sylr  -- Can you post your redacted configuration both Traefik and Pomerium?

**Comment by sylr** [comment]
proxy's config:

```yaml
---
log_level: "info"
address: ":8080"
insecure_server: true
grpc_address: ":8081"
grpc_insecure: true
administrators: "sylvain@company.com"
forward_auth_url: https://k8s-cluster-pomerium-forward-auth.infra.company.com
authenticate_service_url: https://k8s-cluster-pomerium-auth.infra.company.com
authorize_service_url: http://pomerium-authorize.pomerium.svc.cluster.local.:8081
databroker_service_url: http://pomerium-cache.pomerium.svc.cluster.local.:8081
metrics_address: :9090
idp_provider: "azure"
idp_provider_url: "https://login.microsoftonline.com/15eb2494-5298-4347-81a3-e2d3c08a0f82/v2.0"
jwt_claims_headers: "email,groups,user"
policy: [...]
```

Traefik dashboard

```toml
    [http.routers]
      [http.routers.dashboard]
        rule = "HostRegexp(`{host:.*}`)"
        entryPoints = ["traefik"]
        service = "api@internal"
      [http.routers.dashboard-https]
        rule = "Host(`k8s-cluster-traefik-v2.dev.company.com`) || Host(`traefik-v2.dev.company.com`)"
        entryPoints = ["https"]
        service = "api@internal"
        middlewares = ["ip-whitelist-company", "pomerium-forward-auth"]
      [http.routers.dashboard-https.tls]
    [http.middlewares.pomerium-forward-auth.forwardAuth]
      address = "https://k8s-cluster-pomerium-forward-auth.infra.company.com/?uri=https://k8s-cluster-traefik-v2.dev.company.com"
      authResponseHeaders = [
        "x-pomerium-authenticated-user-email",
        "x-pomerium-authenticated-user-id",
        "x-pomerium-authenticated-user-groups",
        "x-pomerium-jwt-assertion",
      ]
```

**Comment by sylr** [comment]
proxy's config:

```yaml
---
log_level: "info"
address: ":8080"
insecure_server: true
grpc_address: ":8081"
grpc_insecure: true
administrators: "sylvain@company.com"
forward_auth_url: https://k8s-cluster-pomerium-forward-auth.infra.company.com
authenticate_service_url: https://k8s-cluster-pomerium-auth.infra.company.com
authorize_service_url: http://pomerium-authorize.pomerium.svc.cluster.local.:8081
databroker_service_url: http://pomerium-cache.pomerium.svc.cluster.local.:8081
metrics_address: :9090
idp_provider: "azure"
idp_provider_url: "https://login.microsoftonline.com/<tenant>/v2.0"
jwt_claims_headers: "email,groups,user"
policy: [...]
```

Traefik dashboard

```toml
    [http.routers]
      [http.routers.dashboard]
        rule = "HostRegexp(`{host:.*}`)"
        entryPoints = ["traefik"]
        service = "api@internal"
      [http.routers.dashboard-https]
        rule = "Host(`k8s-cluster-traefik-v2.dev.company.com`) || Host(`traefik-v2.dev.company.com`)"
        entryPoints = ["https"]
        service = "api@internal"
        middlewares = ["ip-whitelist-company", "pomerium-forward-auth"]
      [http.routers.dashboard-https.tls]
    [http.middlewares.pomerium-forward-auth.forwardAuth]
      address = "https://k8s-cluster-pomerium-forward-auth.infra.company.com/?uri=https://k8s-cluster-traefik-v2.dev.company.com"
      authResponseHeaders = [
        "x-pomerium-authenticated-user-email",
        "x-pomerium-authenticated-user-id",
        "x-pomerium-authenticated-user-groups",
        "x-pomerium-jwt-assertion",
      ]
```

**Comment by desimone** [comment]
@sylr 

I just tested forward-auth and seems to be working with the following configuration.

https://github.com/pomerium/pomerium/blob/1a9ac2fef5e9a9a7d8e8fb2b521dfe3442c28956/.devcontainer/envs/traefik.yaml#L26


The only thing that jumped out at me about being different was the  `trustForwardHeader` setting. Does setting that to true fix it in your configuration?


https://github.com/pomerium/pomerium/blob/c19990903251ee46af9efd0a673010403a7cc414/proxy/forward_auth.go#L82-L82

If that fixes it, we can update the UPGRADING docs to better cover the change.

**Comment by sylr** [comment]
The traefik config I pasted is the config of the traefik dashboard I protect with forward auth.

The forward auth requests are sent to another traefik instances which does reverse proxy for pomerium.

In the config of that latter traefik I do have trustForwardHeader turned on:

```toml
    [entryPoints.https]
      address = ":443"
        [entryPoints.https.forwardedHeaders]
        insecure = true
        trustedIPs = [...]
```

Like I said my current config works well with pomerium proxy v0.10.6 and does not work any more with v0.11.0 so I don't think the issue is related to traefik's config.
