### ISSUE TITLE
Certificate validation fails in 0.11.0

### ISSUE THREAD

**Issue by rd-michael-pasdziernik** [pomerium/pomerium#1686]
## What happened?

Internal communication from proxy to authorize fails when using a self-signed certificate. 
Same setup works using pomerium 0.10.6.

## What did you expect to happen?

Working communication.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 0.11.0
- Server Operating System/Architecture/Cloud: Google GKE

## What's your config.yaml?

```config.yaml
log_level: debug
address: ":8443"
grpc_address: ":5443"
certificate_file: "/pomerium/cert.pem"
certificate_key_file: "/pomerium/privkey.pem"
certificate_authority_file: "/pomerium/cert.pem"
forward_auth_url: "https://fwdauth.example.com"
authenticate_service_url: "https://auth.example.com"
authorize_service_url: "https://pomerium-authorize.pomerium.svc.cluster.local"
databroker_service_url: "https://pomerium-cache.pomerium.svc.cluster.local"
cookie_secret: *SCRUBBED*
shared_secret: *SCRUBBED*
signing_key: *SCRUBBED*
databroker_storage_type: "memory"
idp_provider: "google"
idp_provider_url: "https://accounts.google.com"
idp_client_id: *SCRUBBED*
idp_client_secret: *SCRUBBED*
idp_service_account: *SCRUBBED*
policy:
    - from: https://whoami.example.com
      to: http://whoami.pomerium.svc.cluster.local
      allowed_users:
        - user@example.com
```

## What did you see in the logs?

```logs
{"level":"debug","service":"envoy","name":"router","time":"2020-12-14T07:25:47Z","message":"[C0][S9354672976526267896] cluster \\'pomerium-authorize.pomerium.svc.cluster.local:443\\' match for URL \\'/envoy.service.auth.v2.Authorization/Check\\'"}
{"level":"debug","service":"envoy","name":"router","time":"2020-12-14T07:25:47Z","message":"[C0][S9354672976526267896] router decoding headers:\\n\\':method\\', \\'POST\\'\\n\\':path\\', \\'/envoy.service.auth.v2.Authorization/Check\\'\\n\\':authority\\', \\'pomerium-authorize.pomerium.svc.cluster.local:443\\'\\n\\':scheme\\', \\'https\\'\\n\\'te\\', \\'trailers\\'\\n\\'content-type\\', \\'application/grpc\\'\\n\\'x-envoy-internal\\', \\'true\\'\\n\\'x-forwarded-for\\', \\'172.22.128.154\\'"}
{"level":"debug","service":"envoy","name":"pool","time":"2020-12-14T07:25:47Z","message":"queueing stream due to no available connections"}
{"level":"debug","service":"envoy","name":"pool","time":"2020-12-14T07:25:47Z","message":"creating a new connection"}
{"level":"debug","service":"envoy","name":"client","time":"2020-12-14T07:25:47Z","message":"[C12] connecting"}
{"level":"debug","service":"envoy","name":"connection","time":"2020-12-14T07:25:47Z","message":"[C12] connecting to 172.24.238.83:443"}
{"level":"debug","service":"envoy","name":"connection","time":"2020-12-14T07:25:47Z","message":"[C12] connection in progress"}
{"level":"debug","service":"envoy","name":"http2","time":"2020-12-14T07:25:47Z","message":"[C12] updating connection-level initial window size to 268435456"}
{"level":"debug","service":"envoy","name":"connection","time":"2020-12-14T07:25:47Z","message":"[C12] connected"}
{"level":"debug","service":"envoy","name":"connection","time":"2020-12-14T07:25:47Z","message":"[C12] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED"}
{"level":"debug","service":"envoy","name":"connection","time":"2020-12-14T07:25:47Z","message":"[C12] closing socket: 0"}
{"level":"debug","service":"envoy","name":"client","time":"2020-12-14T07:25:47Z","message":"[C12] disconnect. resetting 0 pending requests"}
{"level":"debug","service":"envoy","name":"pool","time":"2020-12-14T07:25:47Z","message":"[C12] client disconnected, failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED"}
{"level":"debug","service":"envoy","name":"router","time":"2020-12-14T07:25:47Z","message":"[C0][S9354672976526267896] upstream reset: reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED"}
{"level":"debug","service":"envoy","name":"http","time":"2020-12-14T07:25:47Z","message":"async http request response headers (end_stream=true):\\n\\':status\\', \\'200\\'\\n\\'content-type\\', \\'application/grpc\\'\\n\\'grpc-status\\', \\'14\\'\\n\\'grpc-message\\', \\'upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED\\'"}
{"level":"debug","service":"envoy","name":"http","time":"2020-12-14T07:25:47Z","message":"[C11][S15134386274111615980] Sending local reply with details ext_authz_error"}
{"level":"debug","service":"envoy","name":"lua","time":"2020-12-14T07:25:47Z","message":"coroutine finished"}

```

## Additional context

Internal self-signed certificate created by cert-manager using:

```certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-internal
  namespace: pomerium
  labels:
    managed-by: terraform
spec:
  commonName: "*.pomerium.svc.cluster.local"
  dnsNames:
  - "pomerium-proxy.pomerium.svc.cluster.local"
  - "pomerium-authenticate.pomerium.svc.cluster.local"
  - "pomerium-authorize.pomerium.svc.cluster.local"
  - "pomerium-cache.pomerium.svc.cluster.local"
  secretName: pomerium-internal-tls
  duration: 876000h # 100y
  renewBefore: 360h # 15d
  keySize: 4096
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  issuerRef:
    name: pomerium-issuer
    kind: Issuer
```

**Comment by travisgroth** [comment]
Hi @rd-michael-pasdziernik,

I can reproduce locally.  Interestingly, this works if you just set:

```yaml
spec:
  isCA: true
```

I'm not entirely clear on why this has changed, but I don't _think_ that should be needed for self signed certs.  We're still investigating.

**Comment by travisgroth** [comment]
@rd-michael-pasdziernik Actually, I see the same behavior through the entire v0.10.x series with that Certificate.  Can you confirm your CRD hasn't changed?  It doesn't look like this is new, and may be coming directly from envoy.

**Comment by rd-michael-pasdziernik** [comment]
Using "isCA: true" with 0.11.1 works here too. On 0.10.6 it works without "isCa: true". I have double-ckecked with new deployments. We are using cert-manager 1.0.3 deployed via helm chart.

**Comment by travisgroth** [comment]
Deployed the same version of cert-manager and used your CRD.  v0.10.1 and v0.10.6 fails:

```
% helm list -n cert-manager
NAME        	NAMESPACE   	REVISION	UPDATED                             	STATUS  	CHART              	APP VERSION
cert-manager	cert-manager	1       	2020-12-16 10:09:27.129021 -0500 EST	deployed	cert-manager-v1.0.3	v1.0.3
```

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: pomerium-issuer
  namespace: pomerium
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: pomerium-internal
  namespace: pomerium
spec:
  commonName: "*.pomerium.svc.cluster.local"
  dnsNames:
  - "pomerium-proxy.pomerium.svc.cluster.local"
  - "pomerium-authenticate.pomerium.svc.cluster.local"
  - "pomerium-authorize.pomerium.svc.cluster.local"
  - "pomerium-cache.pomerium.svc.cluster.local"
  secretName: pomerium-internal-tls
  duration: 876000h # 100y
  renewBefore: 360h # 15d
  keySize: 4096
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  issuerRef:
    name: pomerium-issuer
    kind: Issuer
```

Note: your CRD API does not match your syntax.  You're using the older version, so I matched that just in case the key options made a difference.

helm chart v14.0.0 values:
```yaml
authenticate:
  idp: XXXX
  existingTLSSecret: pomerium-internal-tls
authorize:
  generateSigningKey: true
  existingTLSSecret: pomerium-internal-tls
cache:
  existingTLSSecret: pomerium-internal-tls
proxy:
  existingTLSSecret: pomerium-internal-tls
config:
  extraOpts:
    log_level: debug
    cache_service_url: https://pomerium-cache.pomerium.svc.cluster.local
  rootDomain: localhost.pomerium.io
  generateTLS: false
  existingCASecret: pomerium-internal-tls
  policy:
    - from: https://httpbin.localhost.pomerium.io
      to: https://httpbin.org
      pass_identity_headers: true
      allowed_domains:
        - pomerium.com
        - gmail.com
image:
  repository: pomerium/pomerium
  tag: v0.10.6
  pullPolicy: Always
ingress:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
```

I'm not sure this conversation is authoritative but it seems to indicate that full validation will fail if the CA constraint isn't set to true http://openssl.6102.n7.nabble.com/Cannot-verify-self-signed-certificates-td61702.html

Sure enough, on the command line, openssl will also fail to verify the certificate generated from your CRD.  Testing with a certificate generated with `isCA: true` works:

```
% openssl x509 -text -in test.crt | grep CA:
% openssl verify -CAfile test.crt test.crt
CN = *.pomerium.svc.cluster.local
error 20 at 0 depth lookup: unable to get local issuer certificate
error test.crt: verification failed
```

```
% openssl x509 -text -in test.crt | grep CA:
                CA:TRUE
% openssl verify -CAfile test.crt test.crt
test.crt: OK
```

I think (a) this is working as expected (b) the behavior doesn't appear to have changed recently.
