### ISSUE TITLE
Unable to integrate with grafana running in istio mesh

### ISSUE THREAD

**Issue by samarth-gupta-traceable** [pomerium/pomerium#1742]
## What happened?
I followed the steps in https://www.pomerium.io/guides/istio.html#istio
however when I try to access `https://grafana.yourcompany.com`  it get below it redirects to 

```
https://authenticate.corp.beyondperimeter.com/.pomerium/sign_in?pomerium_expiry=1609950824&pomerium_issued=1609950524&pomerium_redirect_uri=https%3A%2F%2Fgrafana.yourcompany.com%2F&pomerium_signature......

```

**Note:** I dont have a public DNS and working around with making changes in `/etc/hosts` 

## What did you expect to happen?
Expected to go to github / google for auth

## How'd it happen?

Followed the steps in https://www.pomerium.io/guides/istio.html#istio
below is list of commands ran on newly started gke cluster

```
1) install istio
istioctl install --set profile=demo -y

2) install cert manager
kubectl create namespace cert-manager
helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.1.0 --set installCRDs=true

3)made below entires in /etc/hosts, wwher 35.XXX.XXX.XXX is the external IP for istio ingress gateway started in step 1
35.XXX.XXX.XXX grafana.yourcompany.com
35.XXX.XXX.XXX authenticate.yourcompany.com

4) added quotes around *.yourcompany.com to overcome parsing error and below 

❯ kubectl apply -f gateway.yml
gateway.networking.istio.io/internal-gateway created
certificate.cert-manager.io/internal-cert created
clusterissuer.cert-manager.io/self-signed-issuer created 

5) create pomerium resources
kubectl create namespace pomerium
kubectl label namespace pomerium istio-injection=enabled

❯ kubectl apply -f virtual-services.yml
virtualservice.networking.istio.io/grafana-virtual-service created
virtualservice.networking.istio.io/authenticate-virtual-service created   

#not applying service-enrty 

#added authenticate section to pomerium-helm-values with github as option
❯ helm install pomerium pomerium/pomerium -n pomerium -f pomerium-helm-values.yml
NAME: pomerium
LAST DEPLOYED: Wed Jan  6 21:30:23 2021
NAMESPACE: pomerium
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
##############################################################################
####        DANGER: You have disabled TLS!
####
####        Please only do this if you absolutely know what you are doing.
############################################################################## 

6) Install grafana in monitoring namespace
kubectl create namespace monitoring

kubectl label namespace monitoring istio-injection=enabled

#added service: portName: http-grafana to grafana.ini.yml
 helm install prometheus-grafana grafana/grafana -n monitoring -f grafana.ini.yml

```

## What's your environment like?
- new gke cluster
- latest pomerium version

## What's your config.yaml?

1. gateway.yaml: exactly same as https://github.com/pomerium/pomerium/blob/master/examples/kubernetes/istio/gateway.yml  , but had to quote "*.yourcompany.com"
2. vistual-service.yaml: exactly same as https://github.com/pomerium/pomerium/blob/master/examples/kubernetes/istio/virtual-services.yml
3. did not apply service-entry.yaml
4. pomerium-helm-values
```
config:
  insecure: true
  policy:
    - from: https://grafana.yourcompany.com
      to: "http://prometheus-grafana.monitoring.svc.cluster.local"
      timeout: 30s
      allowed_domains:
        - yourcompany.com
ingress:
  enabled: false

extraEnv:
  JWT_CLAIMS_HEADERS: email

authenticate:
  idp:
    provider: github
    clientID: "xxxxx"
    clientSecret: "xxxxx"
    serviceAccount: "xxxxx"
```
5. grafana.ini.yaml
```
grafana.ini:
  users:
    allow_sign_up: false
    auto_assign_org: true
    auto_assign_org_role: Editor
  auth.proxy:
    enabled: true
    header_name: X-Pomerium-Claim-Email
    header_property: username
    auto_sign_up: true
    sync_ttl: 60
    enable_login_token: false
service:
  portName: http-grafana
  ```

## What did you see in the logs?

1. proxy logs
```
{"level":"info","service":"envoy","upstream-cluster":"","method":"GET","authority":"grafana.yourcompany.com","path":"/","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0","referer":"","forwarded-for":"10.28.2.1,10.28.2.21","request-id":"921d1bf8-4735-4de8-b68e-382fcf2a4b51","duration":15.714731,"size":63124,"response-code":302,"response-code-details":"ext_authz_denied","time":"2021-01-06T16:47:05Z","message":"http-request"}

```

2. no logs in authenticate service
3. below log in authorize service
```
{"level":"info","service":"envoy","name":"main","time":"2021-01-06T16:16:19Z","message":"shutting down parent after drain"}
{"level":"info","service":"authorize","request-id":"470045e5-68ca-9778-a0e5-3301abebb9ff","check-request-id":"b263e40c-03bb-403e-ada6-9a53ba5c862a","method":"GET","path":"/","host":"grafana.yourcompany.com","query":"","allow":false,"status":401,"message":"login required","user":"","groups":[],"time":"2021-01-06T16:28:44Z","message":"authorize check"}
{"level":"info","service":"authorize","request-id":"9d5a8878-53c0-9a82-89c4-70806a733ff3","check-request-id":"921d1bf8-4735-4de8-b68e-382fcf2a4b51","method":"GET","path":"/","host":"grafana.yourcompany.com","query":"","allow":false,"status":401,"message":"login required","user":"","groups":[],"time":"2021-01-06T16:47:04Z","message":"authorize check"}
```

## Additional context
Attaching screenshots of what I see in browser

<img width="1780" alt="Screenshot 2021-01-06 at 10 22 53 PM" src="https://user-images.githubusercontent.com/64777291/103796871-c31c4800-506d-11eb-97bb-a2cddb9ba400.png">
<img width="940" alt="Screenshot 2021-01-06 at 9 58 42 PM" src="https://user-images.githubusercontent.com/64777291/103796892-c9122900-506d-11eb-80cd-6919eb8be9b5.png">
