### ISSUE TITLE
Unable to set policy config via ENVs

### ISSUE THREAD

**Issue by robertgates55** [pomerium/pomerium#1781]
I’m looking to set `set_request_headers` in a policy via an env variable (since I’m looking to pass a basic auth token as a header)

Is this possible? It looks like most settings can be configured via ENVs, but not many of the policy config, and I wondered if I was missing something

**Comment by desimone** [comment]
Hey @robertgates55 -- yes [that is possible](https://www.pomerium.io/reference/#set-request-headers). 



Take a look at our kubernetes dashboard example for an [example](https://www.pomerium.com/guides/kubernetes-dashboard.html#pomerium).

```yaml
  sharedSecret: YOUR_SHARED_SECRET
  cookieSecret: YOUR_COOKIE_SECRET

  policy:
    # this route is directly proxied by pomerium & injects the authorization header
    - from: https://dashboard-proxied.domain.example
      to: https://helm-dashboard-kubernetes-dashboard
      allowed_users:
        - user@domain.example
      tls_skip_verify: true # dashboard uses self-signed certificates in its default configuration
      set_request_headers:
        Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.....

```
