### ISSUE TITLE
config: hot-reloading of configuration and policy not working 

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#1818]
## What happened?

Policy is not hot-reloaded. 

## What did you expect to happen?

Policy to be hot reloaded. 

## How'd it happen?

1. Start pomerium with the following configuration policy.

```yaml
policy:
  - from: https://verify.localhost.pomerium.io
    to: https://verify.pomerium.com/
    allowed_users:
      - bdd@pomerium.com
    pass_identity_headers: true
```

2. Update the policy

```diff
policy:
  - from: https://verify.localhost.pomerium.io
    to: https://verify.pomerium.com/
-    allowed_users:
-      - bdd@pomerium.com
    pass_identity_headers: true
```

3. `bdd@pomerium.com` still has access.

If I hard restart pomerium / envoy, I get the expected behavior. 

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): `v0.12.0+3a505d55`
- Server Operating System/Architecture/Cloud: OSX binaries, and docker-compose. 

## What's your config.yaml?

See above. 

## What did you see in the logs?

On "save" I only see a single log message which seems wrong. 

```logs
{
  "level": "info",
  "time": "2021-01-25T08:30:05-08:00",
  "message": "defaulting to idp_service_account for google_cloud_serverless_authentication_service_account"
}
```

## Additional context

This seems also to apply to other fields in the policy.
