### ISSUE TITLE
Improperly set X-Forwarded-For header

### ISSUE THREAD

**Issue by mleklund** [pomerium/pomerium#1824]
## What happened?

It seems that pomerium is setting imporperly formatted X-Forwarded-For header.  

The generally accepted format of the field is:

```
X-Forwarded-For: client, proxy1, proxy2
```

where the value is a comma+space separated list of IP addresses, the left-most being the original client, and each successive proxy that passed the request adding the IP address where it received the request from. In this example, the request passed through proxy1, proxy2, and then proxy3 (not shown in the header). proxy3 appears as remote address of the request.

I got: 

```
x-forwarded-for: 10.10.22.60,10.244.211.237
```

This is comma separated, not comma+space separated. 

## What did you expect to happen?

I expected to get properly formatted X-Forwarded-For headers.

Example: 

```
x-forwarded-for: 10.10.22.60, 10.244.211.237
```

## How'd it happen?

command run:

```
curl -k -X PUT -H "Arbitrary:Header" -d aaa=bbb https://echo.example.net
```

Output:

```
PUT / HTTP/1.1
host: echo.pomerium.svc.cluster.local
x-request-id: a5353a3d-7dc6-4dfb-87ac-5f012d731cea
x-real-ip: 10.10.22.60
x-forwarded-for: 10.10.22.60,10.244.211.237
x-forwarded-host: echo.example.net
x-forwarded-port: 443
x-forwarded-proto: http
x-scheme: https
content-length: 7
user-agent: curl/7.64.1
accept: */*
arbitrary: Header
content-type: application/x-www-form-urlencoded
x-envoy-external-address: 10.244.211.237
x-envoy-expected-rq-timeout-ms: 30000


aaa=bbb
echo-5d57888b9-j9jjb
```

## What's your environment like?

- Pomerium version 0.12.0
- Kubernetes
## What's your config.yaml?

```
insecure_server: true
grpc_insecure: true
address: ":80"
grpc_address: ":80"

authenticate_service_url: https://authenticate.example.net
authorize_service_url: http://pomerium-authorize-service.pomerium.svc.cluster.local
databroker_service_url: http://pomerium-cache-service.pomerium.svc.cluster.local
forward_auth_url: https://forwardauth.example.net


override_certificate_name: "*.example.net"

policy:
  - from: https://echo.example.net
    to: http://echo.pomerium.svc.cluster.local:8080
    allow_public_unauthenticated_access: true
```

## What did you see in the logs?

```
{"level":"info","service":"envoy","upstream-cluster":"policy-2c6cf6ca2e007062","method":"PUT","authority":"echo.pomerium.svc.cluster.local","path":"/","user-agent":"curl/7.64.1","referer":"","forwarded-for":"10.10.22.60,10.244.211.237","request-id":"a5353a3d-7dc6-4dfb-87ac-5f012d731cea","duration":10.924654,"size":517,"response-code":200,"response-code-details":"via_upstream","time":"2021-01-26T01:10:58Z","message":"http-request"}
```
