### ISSUE TITLE
redirect does not work as expected

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#1907]
## What happened?

With the following policy:

```
- from: https://foo.example.com                                                   
  allow_public_unauthenticated_access: true                                     
  redirect:                                                                     
      host_redirect: github.com                                                                 
      path_redirect: /yegle/your-dns
```

I'm getting the following error:

```
< HTTP/2 503 
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< content-length: 91
< content-type: text/plain
< date: Wed, 17 Feb 2021 21:05:54 GMT
< server: envoy
< 
* Connection #0 to host foo.example.com left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure% 
```

## What did you expect to happen?

A 301/302 redirect to `https://github.com/yegle/your-dns`.

## How'd it happen?

1. Config the server with the policy example above.
2. Wait for autocert to kick in, do a curl

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 0.12.2-1613583129+2060f4e
- Server Operating System/Architecture/Cloud: docker

## What did you see in the logs?

```logs

1:10PM INF authenticate: session load error error="Bad Request: internal/sessions: session is not found" X-Forwarded-For=["172.29.0.1"] X-Forwarded-Proto=["https"] ip=127.0.0.1 request-id=ee82c992-7303-44f8-b1af-4a55a93aaad4 user_agent=Go-http-client/2.0
1:10PM INF authorize check allow=true check-request-id=09bd8617-4399-46b4-b058-a42bbeed0051 groups=[] host=foo.example.com method=GET path=/ query= request-id=d958d606-1d4a-484e-ade9-89f2cd0277f2 service=authorize status=200 user=
1:10PM INF http-request authority=foo.example.com duration=9.865048 forwarded-for=172.29.0.1 method=GET path=/ referer= request-id=09bd8617-4399-46b4-b058-a42bbeed0051 response-code=503 response-code-details="upstream_reset_before_response_started{connection failure}" service=envoy size=91 upstream-cluster=policy-fdba4ca050f5d749 user-agent=curl/7.64.0
```
