### ISSUE TITLE
User unauthenticated using Google IDP

### ISSUE THREAD

**Issue by sandeep-khanna** [pomerium/pomerium#191]
Cannot access Pomerium protected Dockerized resources. Keep getting 403 Forbidden page with message: 'User unauthenticated'.

Followed instructions at [Synology instructions](https://www.pomerium.io/guide/synology.html) to configure Dockerized Pomerium Container within Synology DS3018xs.

1. Navigated to `https://httpbin.corp.taxautomationgroup.com`
2. After being redirected to 'Sign in with Google' page, selected a G Suite account
3. After selecting the G Suite account, get redirected to `https://httpbin.corp.taxautomationgroup.com` with a 403 Forbidden page saying 'User unauthencated'

**Expected behavior**

After G Suite authentication, I should be redirected back to httpbin.

**Environment:**

- Pomerium version (retrieve with `pomerium --version`): `v0.0.5+a405379`
- Server Operating System/Architecture/Cloud: `Linux nas 4.4.59+ #24922 SMP PREEMPT x86_64 GNU/Linux synology_broadwellnk_3018xs`

Configuration file(s):

***Pomerium config file***
```text
# Main configuration flags : https://www.pomerium.io/reference/
#
# address: ":8443" # optional, default is 443
pomerium_debug: true # optional, default is false
# service: "all" # optional, default is all
# log_level: info # optional, default is debug

authenticate_service_url: https://authenticate.corp.taxautomationgroup.com
authorize_internal_url: https://localhost
authorize_service_url: https://localhost

# Certificates can be loaded as files or base64 encoded bytes. If neither is set, a
# pomerium will attempt to locate a pair in the root directory
certificate_file: "./cert.pem" # optional, defaults to `./cert.pem`
certificate_key_file: "./certprivkey.pem" # optional, defaults to `./certprivkey.pem`
certificate_authority_file: "./ca.pem"

# base64 encoded cert, eg. `base64 -i cert.pem` / `base64 -i privkey.pem`
# certificate: |
#  "xxxxxx"
# certificate_key: |
#  "xxxx"
override_certificate_name: "*.corp.taxautomationgroup.com"

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
# shared_secret: hsJIQsx9KKx4qVlggg/T3AuLTmVu0uHhwTQgMPlVs7U=
# cookie_secret: WwMtDXWaRDMBQCylle8OJ+w4kLIDIGd8W3cB4/zFFtg=
# If set, a JWT based signature is appended to each request header `x-pomerium-jwt-assertion`
# signing_key: "Replace with base64'd private key from ./scripts/self-signed-sign-key.sh"

# Identity Provider Settings
## GOOGLE
idp_provider: "google"
idp_provider_url: "https://accounts.google.com" # optional for google
idp_client_id: “1234567890-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com"
idp_client_secret: “XXXX"

# IF GSUITE and you want to get user groups you will need to set a service account
# see identity provider docs for gooogle for more info :
idp_service_account: XXXX

# Proxied routes and per-route policies are defined in a policy block
policy:
  - from: httpbin.corp.taxautomationgroup.com
    to: http://httpbin
    allowed_domains:
      - taxautomationgroup.com
    allowed_users:
      - sandeep.khanna@taxautomationgroup.com
    cors_allow_preflight: true
    timeout: 30s
  - from: external-httpbin.corp.taxautomationgroup.com
    to: httpbin.org
    allowed_domains:
      - gmail.com
```

***Docker Compose file***
```
version: "3"
services:
  pomerium:
    image: pomerium/pomerium:latest
    container_name: pomerium-TAG
    environment:
      - SERVICES=all
      # Generate new secret keys. e.g. `head -c32 /dev/urandom | base64`
      - SHARED_SECRET=XXXX
      - COOKIE_SECRET=XXXX
    volumes:
      # Mount your domain's certificates : https://www.pomerium.io/docs/certificates.html
      - ./*.corp.taxautomationgroup.com_ecc/fullchain.cer:/pomerium/cert.pem:ro
      - ./*.corp.taxautomationgroup.com_ecc/*.corp.taxautomationgroup.com.key:/pomerium/certprivkey.pem:ro
      - ./*.corp.taxautomationgroup.com_ecc/ca.cer:/pomerium/ca.pem:ro
      # Mount your config file : https://www.pomerium.io/reference/
      - ./config.yaml:/pomerium/config.yaml:ro
    network_mode: "bridge"
    ports:
      - "32443:443/tcp"
    external_links:
      - httpbin:httpbin
```

Logs(s):

```text
12:02PM DBG http-request duration=0.594769 email= fwd_ip=192.168.1.1 group= ip=172.17.0.1 method=POST req_id=7a1d9f9c-576e-ab84-bfcb-db54a942104f service=all size=7853 status=404 url=/authenticate.Authenticator/Validate user_agent=grpc-go/1.21.1

12:02PM DBG proxy: user unauthenticated error="proxy: session valid: false : rpc error: code = Unimplemented desc = Not Found: HTTP status code 404; transport: received the unexpected content-type \"text/html; charset=utf-8\"" fwd_ip=192.168.1.1 ip=172.17.0.1 req_id=928e298b-15d1-25f5-e6b0-57682654f92d user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"

12:02PM DBG http-request duration=4.62125 email= fwd_ip=192.168.1.1 group= ip=172.17.0.1 method=GET req_id=928e298b-15d1-25f5-e6b0-57682654f92d service=all size=7934 status=403 url=/ user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36”
```

**Additional context**
