### ISSUE TITLE
option to pass oAuth access token as authorization header to upstream

### ISSUE THREAD

**Issue by pflipp** [pomerium/pomerium#1915]
**Is your feature request related to a problem? Please describe.**

I would like to authenticate to an API which is backed by the same identity provider which I use in pomerium.

**Describe the solution you'd like**

An option which allows me to forward the origin access token as `Authorization: Bearer [Access-Token]`-Header.

**Describe alternatives you've considered**

Re-implementing the whole OIDC/oAuth Login/Consent and token refresh flow in an app behind pomerium.
Well, pomerium already lets me request all the scopes I need and also already has everything i need ;)

**Explain any additional use-cases**

From my frontend, secured by pomerium with gitlab as idP, I would like to display the private projects from the logged in user.
I policy like:
```yaml
policy:
- from: https://example.com
  prefix: /apis/gitlab
  to: https://gitlab.com/api/v4/
  pass_oauth_access_token: true
```
would allow me to access the API as simple as `fetch("https://example.com/apis/gitlab/projects")`
