### ISSUE TITLE
Allow to specify IP whitelist to bypass the auth 

### ISSUE THREAD

**Issue by AlexShuraits** [pomerium/pomerium#1943]
**Is your feature request related to a problem? Please describe.**

In our organization, we want to have the ability to bypass authentication from office IP addresses. In addition, this will be useful when we want to test a protected environment with various tools that don't support OAuth and for e2e tests.
Since we need the application to receive the original host header, we would have to implement a workaround.

**Describe the solution you'd like**

This may be added as an additional directive
`
allow_public_unauthenticated_access_from: ["cidr1", "cidr2"]
`

**Describe alternatives you've considered**

We have implemented another proxy that rewrites the host header in order to achieve conditional routing via Pomerium. The IP whitelist is held inside that proxy and routes to different pomerium policies. But this looks like a workaround and it would be nice to have it supported by Pomerium.

**Comment by mescanne** [comment]
I would like the same thing for my home network. Many self hosted services require Https, and while I'd like to expose them via Pomerium over the internet I'd like them on the home network open.

**Comment by bl0m1** [comment]
Another scenario where this could be useful is if you have a service connecting over the internet to another.
For example if you have Prometheus and want to federate metrics to another central Prometheus server.

**Comment by fnkr** [comment]
This is already possible when using nginx and forward auth. Using Pomerium Operator + nginx ingress controller:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/satisfy: any
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,172.16.0.0/12
    ingress.pomerium.io/allowed_domains: '["example.com"]'
```

Or just using nginx:

```nginx
server {
  # ...
  location / {
    satisfy any;
    allow 10.0.0.0/8;
    allow 172.16.0.0/12;
    # auth_request, ...
  }
}
```

Make sure nginx _knowns_ the real IP address of the visitor ((`proxy_protocol` or `real_ip_header`) and `set_real_ip_from`).

I'd still like to see this implemented in Pomerium for other use cases.
