### ISSUE TITLE
OCSP staple sometimes missing

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#1946]
## What happened?

Note I cannot reproduce this issue but I'm pretty certain it happened.

It looks like in some cases the HTTPS response does not contain OCSP staple result, which conflicts with OCSP Must-Staple and cause HTTPS connection to fail.

This only happened to one of my routes. Chrome would fail to connect. When I test the server using ssllabs.com it returned A+ with warning that there's no OCSP stapling in the response.

Restart the server seems to have fixed the issue. I do notice the route's certificate was recently renewed on Feb 19 but not sure if this is related.

## How'd it happen?

1. Ran `x`
2. Clicked `y`
3. Saw error `z`

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 0.13.0
- Server Operating System/Architecture/Cloud:

## What's your config.yaml?

```config.yaml
# Paste your configs here
# Be sure to scrub any sensitive values
```

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```

**Comment by yegle** [comment]
The error I got from Chrome is `ERR_SSL_VERSION_OR_CIPHER_MISMATCH` FWIW.

**Comment by fightforlife** [comment]
I just got the same error, with latest docker container.

**Comment by desimone** [comment]
Thanks for reporting. I'm not sure what to do without more context. 

This is a real long shot (and doesn't make sense given your error ) but, by any chance could this be related to LE's recent downtime?

https://status.io/pages/incident/55957a99e800baa4470002da/6032bcc06a601504d1dbbdf0

@fightforlife  -- is this persistent? Could you provide a bit more context / logs?

**Comment by fightforlife** [comment]
I restarted pomerium after I noticed the error and it's working fine since then. If it happens again I will try to provide the logs. 
Maybe it really had something to do with the downtime.

**Comment by yegle** [comment]
I'm getting the same error right now.

Seeing this error repeatedly from the log:

```
ERR script log: [string \"function envoy_on_request(request_handle)...\"]:16: attempt to index a nil value name=lua service=envoy
```

FWIW I also used ssllabs to test the server and here's the screenshot:

![Screenshot_20210327-011940.png](https://user-images.githubusercontent.com/146133/112715043-1e0a5200-8e9b-11eb-82ea-8872923632d0.png)

**Comment by desimone** [comment]
Hey @yegle  -- I think the `lua` error (#2038) is possibly unrelated. 


Hunting through my own logs, I do see something that may be related.

```json
{
  "level": "warn",
  "time": "2021-03-23T17:28:45Z",
  "msg": "stapling OCSP",
  "service": "autocert",
  "error": "no OCSP stapling for [authenticate.int.nas.bdd.io]: parsing OCSP response: asn1: structure error: tags don't match (16 vs {class:0 tag:28 length:33 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} responseASN1 @2"
}
```

Do you see anything similar? 

Even so, I am seeing OCSP working for those routes. I am using auto-cert. Not sure if that would matter.

https://www.ssllabs.com/ssltest/analyze.html?d=authenticate.int.nas.bdd.io&hideResults=on
https://www.ssllabs.com/ssltest/analyze.html?d=verify.int.nas.bdd.io&hideResults=on

**Comment by yegle** [comment]
I kept a copy of the log when this happened, but I don't see anything related to ocsp in my log.

**Comment by fightforlife** [comment]
I still get this error from time to time using the latest docker image.
I would say it happens once a week. I will provide logs the next time it happens.

**Comment by fightforlife** [comment]
And again Chrome error message on all domains served by pomerium:
This website cannot connect securely. ERR_SSL_VERSION_OR_CIPHER_MISMATCH
The site is using a not supported protocol.

With POMERIUM_DEBUG=false, there is nothing in the logs. 

I will change this to POMERIUM_DEBUG=true and will post logs as soon as it happens again.

**Comment by fightforlife** [comment]
And it happened again.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
SSLlabs reports: This server certificate supports OCSP must staple but OCSP response is not stapled.
And a lot of handshake failures:
![image](https://user-images.githubusercontent.com/5511687/120887040-1086ec00-c5f1-11eb-903c-da8887d34416.png)

Even with POMERIUM_DEBUG TRUE, I dont find anything in the pomerium logs regarding the failed requests.
I will leave it in this state, if something needs to be tested.

**Comment by yegle** [comment]
This also still happen to me. I decide to post my full configuration (with information redacted) in case it can help the investigation.

docker-compose config (in jsonnet format):

```
  pomerium: uses_adguard {
    image: 'docker.io/pomerium/pomerium:v0.13.6',
    hostname: 'foo.bar.com',
    sysctls: {
      'net.ipv6.conf.all.disable_ipv6': 0,
    },
    environment: super.environment {
      AUTHENTICATE_SERVICE_URL: 'https://foo.bar.com',
      AUTOCERT: '1',
      AUTOCERT_MUST_STAPLE: '1',
      COOKIE_SECRET: '${POMERIUM_COOKIE_SECRET}',
      GRPC_CLIENT_DNS_ROUNDROBIN: '0',
      HTTP_REDIRECT_ADDR: ':80',
      IDP_CLIENT_ID: '${POMERIUM_CLIENT_ID}',
      IDP_CLIENT_SECRET: '${POMERIUM_CLIENT_SECRET}',
      IDP_PROVIDER: 'google',
      IDP_PROVIDER_URL: 'https://accounts.google.com',
      JWT_CLAIMS_HEADERS: 'email',
      LOG_LEVEL: 'info',
      METRICS_ADDRESS: ':9090',
      POLICY: std.base64(importstr 'pomerium/pomerium.yaml'),
      POMERIUM_DEBUG: '1',
      SHARED_SECRET: '${POMERIUM_SHARED_SECRET}',
      SIGNING_KEY: std.base64(importstr 'pomerium/ed25519_private.pem'),
      SIGNING_KEY_ALGORITHM: 'EdDSA',
    },
    volumes: [
      '/opt/pomerium:/data/autocert',
    ],
    ports: [
      '443:443/tcp',
      '80:80/tcp',
      '8843:443/tcp',
    ],
  },
```

pomerium.yaml file:
```
- from: https://1.bar.com
  to: http://1
  pass_identity_headers: true
  allowed_users:
    - A@gmail.com
- from: https://2.bar.com
  to: http://2:8080
  allowed_users:
    - A@gmail.com
  pass_identity_headers: true
- from: https://3.bar.com
  to: http://3:9000
  allowed_users:
    - A@gmail.com
- from: https://4.bar.com
  to: http://4.local
  timeout: 10m
  allowed_users:
    - A@gmail.com
- from: https://5.bar.com
  to: http://5.local
  timeout: 10m
  allowed_users:
    - A@gmail.com
- from: https://6.bar.com
  to: http://6
  path: /foo-bar
  allow_public_unauthenticated_access: true
- from: https://6.bar.com
  to: http://6
  allowed_users:
    - A@gmail.com
    - B@gmail.com
- from: https://7.bar.com
  to: http://7.local
  allowed_users:
    - A@gmail.com
- from: https://8.bar.com
  to: http://8.local
  allowed_users:
    - A@gmail.com
- from: https://9.bar.com
  to: http://172.17.x.x:xxxx
  allow_websockets: true
  allow_public_unauthenticated_access: true
- from: https://10.bar.com
  to: http://10
  allow_public_unauthenticated_access: true
- from: https://11.bar.com
  to: http://11:9090
  allowed_users:
    - A@gmail.com
- from: https://12.bar.com
  to: http://12:3000
  allowed_users:
    - A@gmail.com
    - B@gmail.com
  pass_identity_headers: true
- from: https://13.bar.com
  to: http://13
  pass_identity_headers: true
  allowed_users:
    - A@gmail.com
- from: https://14.bar.com
  to: http://14.local
  allowed_users:
    - A@gmail.com
- from: https://15.bar.com
  to: https://15:xxxxx
  allow_public_unauthenticated_access: true
  tls_server_name: aaa.bbb.com
  allow_websockets: true
- from: https://15.bar.com:443
  to: https://15:xxxxx
  allow_public_unauthenticated_access: true
  tls_server_name: aaa.bbb.com
  allow_websockets: true
- from: https://16.bar.com
  to: https://16:8443
  set_request_headers:
    Referer: https://16:8443
  remove_request_headers:
    - Origin
  allow_websockets: true
  tls_skip_verify: true
  allow_public_unauthenticated_access: true
- from: https://16.bar.com:8843
  to: https://16:8843
  allow_public_unauthenticated_access: true
  set_request_headers:
    Referer: https://16:8443
  remove_request_headers:
    - Origin
  allow_websockets: true
  tls_skip_verify: true
- from: https://17.bar.com
  to: https://17:8843
  allow_public_unauthenticated_access: true
  set_request_headers:
    Referer: https://17:8443
  remove_request_headers:
    - Origin
  allow_websockets: true
  tls_skip_verify: true
- from: https://18.bar.com
  to: http://192.168.x.x:xxxx
  allowed_users:
    - A@gmail.com
- from: https://19.bar.com
  to: http://192.168.x.x:xxxx
  allowed_users:
    - A@gmail.com
- from: https://20.bar.com
  to: http://20.local:xxxx/
  allowed_users:
    - A@gmail.com
  timeout: 10m
  set_request_headers:
      Authorization: Basic xxxx
- from: https://21.bar.com
  allow_public_unauthenticated_access: true
  redirect:
      host_redirect: foo.com
      path_redirect: /bar/baz
- from: https://22.bar.com
  to: http://22:4000
  allowed_users:
    - A@gmail.com
  allow_websockets: true
- from: https://23.bar.com
  to: http://23.local:8080
  remove_request_headers:
    - Origin
    - Referer
  allow_public_unauthenticated_access: true
```
