### ISSUE TITLE
DNS-1123 subdomain error when exposing TCP service on Helm Chart

### ISSUE THREAD

**Issue by eddiewang** [pomerium/pomerium#1981]
## What happened?
When trying to applying the following config:
```yaml
    - from: "tcp+https://postgres.corp.redacted.com:5432"
      to: "tcp://postgres-test.postgres.svc.cluster.local:5432"
      timeout: 30s
      allowed_users:
        - admin@org.com
```

An error occurs on helm upgrade:  `helm upgrade -f values.yaml pom pomerium/pomerium -n auth`
```
Error: UPGRADE FAILED: cannot patch "pom-pomerium" with kind Ingress: Ingress.extensions "pom-pomerium" is invalid: [spec.rules[3].host: Invalid value: "tcp+https://postgres.corp.redacted.com:5432": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.tls[4].hosts: Invalid value: "tcp+https://postgres.corp.redacted.com:5432": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```
## What did you expect to happen?

The helm upgrade the config succesfully.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): v0.13.2
- Server Operating System/Architecture/Cloud: Kubernetes (Self-managed on Hetzner, running Istio as the service mesh)
