### ISSUE TITLE
Integrate with istio 1.9 external authorization 

### ISSUE THREAD

**Issue by derrickburns** [pomerium/pomerium#1997]
Once you have a pomerium controller in k8s, the next step may be to integrate with commonly used ingress controllers like istio ingress.

**Comment by travisgroth** [comment]
Hi @derrickburns - could you elaborate more on the ask here?

**Comment by derrickburns** [comment]
Istio 1.9 offers support for external authorization. https://istio.io/latest/blog/2021/better-external-authz/

I suppose that I am asking a Pomerium CRD that sets up a Pomerium as an ext auth service using the expected GRPC interface.

**Comment by travisgroth** [comment]
Thanks!  Our Authorize service actually implements the envoy extauthz API already.  It is _possible_ that you could do this today with a standard pomerium deployment, but this would need testing.  You'd simply configure the pomerium authz endpoint as your extension provider.  Example:

```
extensionProviders:
- name: "pomerium-authorize"
  envoyExtAuthzGrpc:
    service: "pomerium-authorize.pomerium.svc.cluster.local"
    port: 443
```
