### ISSUE TITLE
TCP tunnel error when connecting to database hosted in kubernetes 

### ISSUE THREAD

**Issue by Pavankumar6997** [pomerium/pomerium#1998]
Hey guys,
##### What happened?

After applying the following config in kubernetes:

    - from: "tcp+https://qa-postgres.corp.redacted.com:5432"
      to: "tcp://postgres.qa.svc.cluster.local:5432"
      allowed_groups:
        - folks@org.com

An error occurs on when connecting using `pomerium-cli`
```
$ pomerium-cli tcp qa-postgres.corp.redacted.com:5432 --listen :5432 &
$ psql -h localhost -p 5432 -U user -d mydb -W
Password:
psql: error: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

errors from pomerium-cli:
10:50AM INF tcptunnel: opening connection dst=qa-postgres.corp.redacted.com:5432 proxy=qa-postgres.corp.redacted.com:443 secure=true
10:50AM INF tcptunnel: connection closed
10:50AM ERR tcptunnel: error serving local connection error="tcptunnel: invalid http response code: 400"
```
referred the document here https://www.pomerium.com/docs/topics/tcp-support.html#using
it says 
```
On first connection, you will be sent through a standard Pomerium HTTP authentication flow. After completing this, your TCP connection should be established!
```
but i dont happen to see any authentication flow, it fails right after entering password  

What's your environment like?

    Pomerium version on kubernetes - `pomerium/pomerium:v0.10.6`
    Pomerium CLI version - `0.13.3-1616105987+a879e5f` on macOS catalina
    
Additional context

This problem is with TCP routes. HTTP routes work just fine for services like grafana, prometheus in k8s

**Comment by desimone** [comment]
Hey @Pavankumar6997  -- could you elaborate a bit more about the infrastructure in front of Pomerium. Is it being fronted by any other load balancer or reverse proxy by any chance?

**Comment by Pavankumar6997** [comment]
@desimone we are using AWS ALB ingress that load balances application traffic

**Comment by travisgroth** [comment]
Hi @Pavankumar6997 - When using TCP routes, you must not send the traffic through another HTTP proxy.  In your example, `qa-postgres.corp.redacted.com` must point directly at the `pomerium-proxy` service's HTTP port and not at your ingress controller's HTTP port.  If you're using our helm chart, you'd want to set `service.type` to `LoadBalancer` so that a public TCP service is provisioned for `pomerium-proxy`.

**Comment by Pavankumar6997** [comment]
@travisgroth like you said, we have deployed pomerium with a service of type `LoadBalancer` which creates a Classic Load Balancer in AWS - but while accessing URL configured in the policy -> `https://prod-prom.corp-1.domain.com` we are getting 
```
Not Found: authenticate.corp.domain.com route unknown
```
installed the latest helm charts `0.13.2` via terraform

config.yaml:
```
address: ":443"
grpc_address: ":443"

certificate_file: "/pomerium/cert.pem"
certificate_key_file: "/pomerium/privkey.pem"
certificate_authority_file: "/pomerium/ca.pem"
authenticate_service_url: https://authenticate.corp-1.domain.com
authorize_service_url: https://pomerium-authorize-test.pomerium-test.svc.cluster.local
databroker_service_url: https://pomerium-cache-test.pomerium-test.svc.cluster.local

idp_provider: google
idp_scopes:
idp_provider_url: "https://accounts.google.com"
cookie_secret: REDACTED
shared_secret: REDACTED
idp_client_id: REDACTED
idp_client_secret: REDACTED
idp_service_account: <REDACTED>
databroker_storage_type: memory

policy:
- from: https://prod-prom.corp-1.domain.com
  to: http://prometheus.corp-2.domain.com:80
  allowed_groups:
  - folks@domain.com
  ```
  root domain: `corp-1.domain.com`

additional info: we have added dns record for the `proxy` service external IP which is `*.corp-1.domain.com` (wildcard dns)

the requests are hitting to `proxy` deployment instead of `authenticate` deployment

Could you help In pointing out any cofiguration error ?
