### ISSUE TITLE
Support Envoy's `xff_num_trusted_hops` config option

### ISSUE THREAD

**Issue by ntoofu** [pomerium/pomerium#2002]
**Is your feature request related to a problem? Please describe.**

When pomerium is deployed with a reverse proxy in front of it, `x-envoy-external-address` and `x-forwarded-proto` which upstream servers observe are based on the request from the reverse proxy to pomerium.

**Describe the solution you'd like**

Add a new config option and set the value to [Envoy's `xff_num_trusted_hops`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-xff-num-trusted-hops) config option. Because `x-forwarded-proto` will not be overwritten by envoy when that option is greater than 0, users who have reverse proxies in front of pomerium should specify this option to be greater than 0. Please refer https://github.com/envoyproxy/envoy/pull/7995 for details.

**Describe alternatives you've considered**

**Explain any additional use-cases**

For example, let's assume pomerium and upstream servers are deployed with following configuration files.

* `docker-compose.yml`

    ```yaml
    version: "3"
    services:
      nginx:
        image: nginx:1.19.8
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - ./nginx/cert.pem:/etc/nginx/cert.pem:ro
          - ./nginx/key.pem:/etc/nginx/key.pem:ro
        ports:
          - 443:443
      pomerium:
        image: pomerium/pomerium:v0.13.2
        environment:
          - COOKIE_SECRET=R+zvM7v92Xqc2PJH/c6Iwc/z3scr+33l/3sC1aWhXYE=
        volumes:
          - ./config.yaml:/pomerium/config.yaml:ro
        expose:
          - 443
      hello:
        image: "gcr.io/google-containers/echoserver:1.8"
        expose:
          - 8080
    ``` 
* `nginx.conf`

    ```
    events {}
    
    http {
    
        map $http_x_forwarded_proto $proxy_x_forwarded_proto {
          default $http_x_forwarded_proto;
          ''      $scheme;
        }
        map $http_x_forwarded_port $proxy_x_forwarded_port {
          default $http_x_forwarded_port;
          ''      $server_port;
        }
        map $http_upgrade $proxy_connection {
          default upgrade;
          '' close;
        }
        server_names_hash_bucket_size 128;
        map $scheme $proxy_x_forwarded_ssl {
          default off;
          https on;
        }
    
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $proxy_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
        proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
        proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
    
        server {
            listen       443 ssl http2;
            server_name  localhost;
            ssl_certificate cert.pem;
            ssl_certificate_key key.pem;
            ssl_protocols TLSv1.2;
            ssl_ciphers HIGH:!aNULL:!MD5;
            location / {
                proxy_pass   http://pomerium:443;
            }
        }
    }
    ```
* `config.yaml`

    ```yaml
    # skip configurations about authentication
    authenticate_service_url: https://auth.localhost
    insecure_server: true
    idp_provider: google
    idp_client_id: "******"
    idp_client_secret: "******"
    
    policy:
      - from: https://localhost
        to: http://hello:8080
        allow_public_unauthenticated_access: true
    ```
    * Even when `skip_xff_append` is set to `true` in `config.yaml`, this issue is not solved.

In this example, upstream servers expect `x-forwarded-proto`  to be `https`, but pomerium overwrites it to be `http`. It can be confirmed in a easy way shown below:

```
$ curl -k https://localhost
  
 
Hostname: 4bafc54d6b05

Pod Information:
	-no pod information available-

Server values:
	server_version=nginx: 1.13.3 - lua: 10008

Request Information:
	client_address=192.168.176.3
	method=GET
	real path=/
	query=
	request_version=1.1
	request_uri=http://hello:8080/

Request Headers:
	accept=*/*
	content-length=0
	host=hello
	user-agent=curl/7.74.0
	x-envoy-expected-rq-timeout-ms=30000
	x-envoy-external-address=192.168.176.2
	x-forwarded-for=192.168.176.1,192.168.176.2
	x-forwarded-port=443
	x-forwarded-proto=http
	x-forwarded-ssl=on
	x-real-ip=192.168.176.1
	x-request-id=1a5f963e-56dc-4b3a-9e61-69d3fda35788

Request Body:
	-no body in request-
```

Depecting the result,

```
IP Addr:                .1                 .2                   .3                  .4 
                   [client] --https--> [nginx] --http--> [pomerium] --http--> [servers] 
x-forwarded-proto:          (not set)            https                http 
x-forwarded-for:            (not set)             .1                 .1, .2   
```

Consequently, upstream servers which recognize `x-forwarded-proto` would generate response containing `http://` URL, but client is expected to use `https://`  URL in actual.

**Additional context**
