### ISSUE TITLE
How to define `allowed_groups` policy for OIDC Provider Type that support `groups` claim?

### ISSUE THREAD

**Issue by bangau1** [pomerium/pomerium#2015]
## What happened?

- I setup pomerium with provider type `oidc`, which is [dexIdp](https://dexidp.io/) server.
- I installed pomerium with the helm chart, here is the relevant helm chart configuration
```
image:
  tag: ${pomerium_version}

config:
  rootDomain: ${cluster_domain}
  policy:
  - from: https://httpbin-sso.${cluster_domain}
    to: http://httpbin.test.svc.cluster.local:8000
    timeout: 30s
    allowed_groups:
    - ${orgz}:backend

ingress:
  enabled: false

extraEnv:
  # Global timeout for Pomerium so that long query can be executed
  # Route timeout can not exceed global timeout
  # https://www.pomerium.io/reference/#route-timeout
  # TO DO: figure out which timeout matter
  TIMEOUT_IDLE: "15m"
  TIMEOUT_READ: "15m"
  TIMEOUT_WRITE: "15m"
  JWT_CLAIMS_HEADERS: "email,groups"
  
  METRICS_ADDRESS: ":9090"

authenticate:
  redirectUrl: ""
  idp:
    provider: oidc
    url: ${dex_url}
    clientID: ${dex_client_id}
    clientSecret: ${dex_client_secret}
    scopes: "openid profile email offline_access groups"
```

As you can see, I provided `groups` scope as well. Upon accessing the website, it redirects me to the Dex Login (which I choose Github there - Dex can provide multiple login options), I can see that my pomerium session has user claim with relevant group.
![image](https://user-images.githubusercontent.com/352737/112147678-90ff9880-8c0f-11eb-929d-ce8c730d6e1f.png)

But I got 403, even though I have the groups claim. Upon checking the pomerium-authorize log, there is this
```
pomerium-authorize-7fc4bc45f5-dtlvf pomerium {"level":"error","error":"config: options from config file \"/etc/pomerium/config.yaml\": validation error config: `allowed_groups` requires `idp_service_account`","time":"2021-03-23T12:31:27Z","message":"config: could not reload configuration"}
```
Any advice? 

I read this doc https://github.com/pomerium/pomerium/blob/master/docs/docs/identity-providers/readme.md, it stated that I need to create another service account to retrieve the additional user information (e.g: group). Since DexIDP is OIDC provider, not a specific one, how to by pass this behavior? Since the DexIdp itself support `groups` scope/claim, should it by default (or through some flag in configuration) be supported?

**Comment by bangau1** [comment]
After reading through the `policy` config documentation, I can see there is `allowed_idp_claims` 

> Allowed IdP Claims is a collection of whitelisted claim key-value pairs to authorize for a given route.
> This is useful if your identity provider has extra information about a user that is not in the directory. It can also be useful if you wish to use groups with the generic OIDC provider.

It works now with this policy
```
config:
  rootDomain: ${cluster_domain}
  policy:
  - from: https://httpbin-sso.${cluster_domain}
    to: http://httpbin.test.svc.cluster.local:8000
    timeout: 30s
    allowed_idp_claims:
      groups:
      - ${group}
```

I will close this issue.
