### ISSUE TITLE
proxy: session fails to re-authenticate after token expiration

### ISSUE THREAD

**Issue by ValentinPortais** [pomerium/pomerium#203]
**Describe the bug**
When the token expires, the session expires aswell (60min after login).
The Forbidden page , user unauthenticated is displayed.
I have to login again through the IDP.

**Expected behavior**

I expect the refresh_token to be use to get a new token.

**Environment:**
- Pomerium 0.0.5
- K8s 1.13.6
- Helm 2.13
- IDP: Google Accounts

**Configuration file(s):**
helm values:
```
config:
  rootDomain: productapps.mydomain.com
  sharedSecret: ""
  cookieSecret: ""
  generateTLS: true
  extraOpts: {}
  existingPolicy: ""
  policy: {}
authenticate:
  redirectUrl: "https://authenticate.productapps.mydomain.com/oauth2/callback"
  idp:
    provider: google
    clientID: "id.apps.googleusercontent.com"
    clientSecret: "REPLACE_ME"
    url: "https://accounts.google.com"
    serviceAccount: ""
  tls:
    cert: ""
    key: ""
    defaultSANList: []
    defaultIPList: []
authorize:
  tls:
    cert: ""
    key: ""
    defaultSANList: []
    defaultIPList: []
proxy:
  tls:
    cert: ""
    key: ""
    defaultSANList: []
    defaultIPList: []
  authenticateServiceUrl: ""
  authorizeServiceUrl: ""
  authorizeInternalUrl: ""
  authenticateInternalUrl: ""
service:
  type: NodePort
  externalPort: 443
  annotations:
    cloud.google.com/app-protocols: '{"https":"HTTPS"}'
  labels: {}
ingress:
  secretName: "productapps-tls"
  secret:
    name: ""
    cert: ""
    key: ""
  enabled: true
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: pomerium-productapps-ip
resources:
  {}
priorityClassName: ""
podAnnotations: {}
podLabels: {}
replicaCount: 1
extraEnv: 
  POMERIUM_DEBUG: true
extraArgs: {}
extraVolumes: {}
image:
  repository: "pomerium/pomerium"
  tag: "v0.0.5"
  pullPolicy: "IfNotPresent"
```

Logs(s):

```
ERR identity: failed to verify session state error="oidc: token is expired (Token Expiry: 2019-07-03 12:59:28 +0000 UTC)"
```

**Additional context**
Using manual refresh in user dashboard (/.pomerium hitting refresh button) works, token is refreshed.
