### ISSUE TITLE
Policy specific client CA error

### ISSUE THREAD

**Issue by ventris** [pomerium/pomerium#2094]
## What happened?
Settings specific client CA for selected policies results in a `495 invalid client certificate` when visiting that address.

## What did you expect to happen?

Im trying to add client certificates for specific policies. From your documentation it seems like its possible to do this with the `tls_downstream_client_ca_file` flag in each policy. As the documentation states [HERE](https://www.pomerium.com/reference/#tls-downstream-client-certificate-authority)

## How'd it happen?

I have two endpoints example-a and example-b. 
Example-a has the `tls_downstream_client_ca_file` config row in its policy.

When I visit the policy address I get an 495 invalid client certificate error in my browser.

I also tried to add the `client_ca_file` to the global config. When I do this I get example B to work with client certificates which has no `tls_downstream_client_ca_file` set. 

When I do this example-b works with client certificate but I still receive the same error for example-a.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): `0.13.5-1617718510+403718c`
- Server Operating System/Architecture/Cloud: `4.15.0-141-generic #145-Ubuntu SMP Wed Mar 24 18:08:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

## What's your config.yaml?

```config.yaml
address: :443
metrics_address: :9299

databroker_storage_type: memory

authenticate_service_url: https://authenticate.example.com

client_ca_file: "/etc/pomerium/client-ca.pem"

certificates:
   - cert: /etc/pomerium/fullchain.pem
     key: /etc/pomerium/privkey.pem

shared_secret: "REDACTED"
cookie_secret: "REDACTED"

# IDP configuration
idp_provider: "google"
idp_client_id: "REDACTED"
idp_client_secret: "REDACTED"
idp_service_account: "REDACTED"

jwt_claims_headers: "user,email,groups"

policy:
  - from: https://example-a.example.com
    to: http://host.example.local
    tls_downstream_client_ca_file: "/etc/pomerium/client-ca.pem"
    allowed_users:
      - REDACTED
  - from: https://example-b.example.com
    to: http://host.example.local
    allowed_users:
      - REDACTED
```

## What did you see in the logs?

```logs
Apr 16 13:58:22 pomerium.local pomerium[16326]: {"level":"info","service":"authorize","request-id":"8f0653dd-57a8-433e-aca0-d054a176e889","check-request-id":"75daa5cf-2a61-4f37-b15b-a72fca6e2baa","method":"GET","path":"/","host":"host.example.com","query":"","allow":false,"status":495,"message":"invalid client certificate","user":"","groups":[],"time":"2021-04-16T13:58:22Z","message":"authorize check"}
Apr 16 13:58:22 pomerium.local pomerium[16326]: {"level":"error","service":"envoy","name":"lua","time":"2021-04-16T13:58:22Z","message":"script log: [string \\\"function envoy_on_request(request_handle)...\\\"]:16: attempt to index a nil value"}
```

**Comment by calebdoxsey** [comment]
@ventris Have you added both certificates to your browser? When I test this locally I'm prompted to choose the certificate I want to use. I was able to get it to work with two routes on different domains:

```yaml
  - from: https://mtls-a.example.com
    to: http://httpbin.org
    path: "/uuid"
    allow_public_unauthenticated_access: true
    tls_downstream_client_ca_file: "a-ca-cert.pem"

  - from: https://mtls-b.example.com
    to: http://httpbin.org
    path: "/uuid"
    allow_public_unauthenticated_access: true
    tls_downstream_client_ca_file: "b-ca-cert.pem"

```

This can be somewhat tricky to test because browsers seem to cache your choice, with no easy way to change it. Have you tried in an incognito window?
