### ISSUE TITLE
Cache pod reboot puts authorize into a bad state

### ISSUE THREAD

**Issue by bjoernw** [pomerium/pomerium#2137]
## What happened?
If cache instances reboot the authorize service will complain with 
```
{"level":"warn","error":"rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection failure","time":"2021-04-21
 T20:56:22Z","message":"sync error"}
```
and won't stop even after fresh cache pods come up as healthy. In order to resolve the issue we also have to restart the authorize pods at which point everything works fine again.

## What's your environment like?

- Helm chart version 18.0.0
- pomerium version 0.13.5
- Deployed on Kubernetes 1.18

**Comment by travisgroth** [comment]
Hi @bjoernw - I'm not able to easily reproduce this currently.  Please share as much as you can about your configuration; especially helm values.  Thanks!

**Comment by bjoernw** [comment]
`values.yaml`
(routes/policies are defined in an env override)
``` yaml
tracing:
  enabled: false
  provider: ""
  debug: false
  jaeger:
    collector_endpoint: ""
    agent_endpoint: ""

serviceMonitor:
  enabled: true

metrics:
  enabled: true
  port: 9090

config:
  forceGenerateSigningKey: true
  generateTLS: true
  insecure: true

ingress:
  enabled: false

extraEnv:
  JWT_CLAIMS_HEADERS: email,groups,user
  LOG_LEVEL: warn

resources:
  requests:
    cpu: 60m
    memory: 128Mi

cache:
  replicaCount: 3

authorize:
  replicaCount: 3

authenticate:
  replicaCount: 3

proxy:
  replicaCount: 3

redis:
  image:
    registry: "artifactory:6555"
  master:
    resources:
        requests:
          cpu: 50m
          memory: 64Mi
  slave:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
```
