### ISSUE TITLE
JWT_CLAIMS_HEADERS=email won't generate X-Pomerium-Claim-Email

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#2185]
It looks like `JWT_CLAIMS_HEADERS=email` no longer generates `X-Pomerium-Claim-Email` header to the backend since 0.14.0.

Reading the relevant doc, it looks like the header can be customized now but I did not expect the old config to stop working.

**Comment by calebdoxsey** [comment]
I'm not able to reproduce this issue. I see:

```
"X-Pomerium-Claim-Email": "cdoxsey@pomerium.com",
```

In the headers being sent, with a config like:

```yaml
  pomerium-authorize:
    environment:
      - SERVICES=authorize
      - JWT_CLAIMS_HEADERS=email
```

The email comes from the session or user claims. @yegle Do you have more details about what might be different or a redacted config?
