### ISSUE TITLE
Populating the kubernetes impersonation headers with group claims

### ISSUE THREAD

**Issue by Ptyool** [pomerium/pomerium#2221]
**Is your feature request related to a problem? Please describe.**

Hi, as discussed here https://github.com/pomerium/pomerium/issues/1638#issuecomment-843158590 , when using "kubernetes_service_account_token_file" to impersonate user to access kubernetes-dashboard, I would like the Impersonate-group header to be populated by groups claim from the access token.

Currently, v0.13.4 does not populated at all the header, and v0.14.1 seems to populated only the last group of groups claim list, it does not create multiple Impersonate-Group header per entry in groups claim.

Moreover, do you think it is possible to add a parameter to prefix the group name in the impersonate header ?
We are using --oidc-username-prefix and --oidc-groups-prefix on the api server (https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server) to be sure there is no group name overlap and it is more "visual" in rbac policies (easy to see it is "external" from k8s).

**Comment by travisgroth** [comment]
Thanks @Ptyool.

The missing groups may be a bug in v0.14.  

WRT prefixing - do you have multiple group sources?  We'd like to understand the reasons for prefixing oidc groups and users better.  The more you could share on the reason for that configuration, the better we can understand the use case.  It might fit into larger features.

**Comment by travisgroth** [comment]
Just to follow up on the group claims themselves - I'm not able to reproduce missing group headers.  Config snippet:

```yaml
idp_provider: oidc
idp_provider_url: https://xxxxxxx
idp_scopes: profile,email,groups,openid

policy:
  - from: https://httpbin.localhost.pomerium.io
    to: http://localhost:444
    pass_identity_headers: true
    tls_skip_verify: true
    allowed_domains:
      - pomerium.com
    kubernetes_service_account_token: XXXXXXXXXXXX
```

Request headers:

```
Impersonate-Group:              Everyone
Impersonate-Group:              group-107
Impersonate-Group:              group-92
Impersonate-Group:              group-101
Impersonate-Group:              admins
Impersonate-User:               tgroth@pomerium.com
```

**Comment by vanhtuan0409** [comment]
Hi @travisgroth , I would like to bring up this issue again since I experienced the same thing with pomerium 0.16.2
This is my config:
```
services: all
jwt_claims_headers:
  - email
  - groups
  - user

routes:
  - from: http://httpbin.baphouse.internal
    to: http://httpbin.default
    allow_any_authenticated_user: true
    pass_identity_headers: true
    kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  - from: http://k3s.baphouse.internal
    to: http://homelab-kubernetes-dashboard.kubernetes-dashboard
    pass_identity_headers: true
    allow_any_authenticated_user: true
    kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
```

Testing with httpbin showed that the `Impersonate-Group` is merged into 1 header instead of multiple headers
```
"Impersonate-Group": "rol_974Mb5Eu6woTZxpo,rol_UGSqVhZKksyLegBN,k3s:admin,monitoring:admin"
```

Testing with k8s dashboard directly also failed to authorized
