### ISSUE TITLE
Pomerium seems to redirect to the wrong URL after authentication

### ISSUE THREAD

**Issue by ChristianKlass** [pomerium/pomerium#2288]
Hi everyone, I need some help with Pomerium.

Here's the gist of it:
I'm trying to use Pomerium with Dex on Kubernetes (with Istio). I am being redirected to the wrong page after logging in. I am not sure what I can do to fix this. So far, I can confirm that the Dex authentication portion works. I can go to https://authenticate.wfh.com/.pomerium after logging in (and being redirected to the wrong page) to see the user info endpoint, where I can log out with no issue.

**What I expect to happen:**
```
Visiting https://monitor.wfh.com/whoami sends the user to the pomerium-proxy service and should result in one of two things:
1. If the user is not authenticated:
  a. Redirect to the Dex login page (works)
  b. Log in. (works)
  c. Redirect (via reverse proxy) to the http://whoami service (doesn't work)
2. If the user is authenticated:
  a. Redirect (via reverse proxy) to the http://whoami service (works)
  i.e. if the user is already logged in by completing 1b, manually going to https://monitor.wfh.com/whoami will redirect to the http://whoami service.
```

**What actually happens:**
```
1. If the user is not authenticated:
  a. Redirect to the Dex login page (works)
  b. Log in. (works)
  c. User is redirected to something like: 
    https://monitor.wfh.com/.pomerium/callback/?pomerium_expiry=1622641439&pomerium_issued=1622641139&pomerium_redirect_uri=https%3A%2F%2Fmonitor.wfh.com%2Fwhoami&pomerium_session_encrypted=S9pw2qakLRzDxAMwfkpGLtLPyQfSdefAmWkMb7HRKQAYrSYx5pyqeJ0bH8okS-1P_U9LO7iqerzF9DmvrzERt-XWULtP0ljvCFVmEHiq6ekmfOg_V9QroAGswAX7Q6LHw4L5sJvFh4PYkK2YWym8i_d23C-ACcQmzO_B4hiyrsWS3nxnhFQ2uT6Vozz_FLPksEw4hx7st1PBE7Iblddztu58ZOaIMGcv-8sfJSDA8EL3cXPgjDddo9o0TL7RMu4nA45wuI9LOxeRhT-naI0YfR6n0etUFubziyio1lWAz3LXiBwgRM3UbT79FXnOoYu2MS-KUEmyy3D7a_wWUIhbyQAdQHsRnuVT_eix2yarSegC2s4Zlnk6a1_QkCTbMBZE7S9qik6XZCyIBh0pqSyC5NHwBNN_9ugWN0k5RSRHgdFogC_EvKUKkm5lL7LFtDp44QFOhe4o0XEoyTHkTzoVITP_aEIS56PwJrSg__8mD_HuXkQiZonK_j6bfPyLgKoRUb8VhZg1IBfqtSD_WCReBZaEORYqcY8qvYTpV7C_B6R9RT25QakhBn9-MaQTt7RsoaJvvJ-42PXjuN0QnvW54toUOEpQUQs8YmnrH&pomerium_signature=yZWtkpUA5t_8EyW5_3cwwJs-Szf6qKGpnUAOAkdLbQw%3D
I am not sure which setting I should use to redirect the flow properly. (edited) 
```

Currently, I am using Helm to install and configure Pomerium, and this is my `values.yaml`:
```
authenticate:
  idp:
    provider: oidc
    url: http://idp.wfh.com/dex
    clientID: pomerium-app
    clientSecret: <redacted>
  # authenticateServiceUrl: "https://authenticate.wfh.com"
  # redirectURL: https://authenticate.wfh.com/oauth2/callback
  existingTLSSecret: wfh-ssl-certs
# proxy:
#   # authenticateServiceUrl: "https://authenticate.wfh.com"
#   # authorizeServiceUrl: "http://pomerium-authorize"
#   existingTLSSecret: wfh-ssl-certs
config:
  rootDomain: wfh.com
  insecure: true
  generateTLS: false
  policy:
    - from: https://monitor.wfh.com
      prefix: /whoami
      to: http://whoami:80
      # redirect:
      #   host_redirect: https://monitor.wfh.com                                                                 
      #   path_redirect: /whoami
      allowed_users:
        - batman
        - superman
        - mark
      pass_identity_headers: true
      tls_skip_verify: true
ingress:
  enabled: false
extraEnv:
  JWT_CLAIMS_HEADERS: email
  COOKIE_SECURE: false
  COOKIE_SECRET: <redacted>
  COOKIE_DOMAIN: .wfh.com
  LOG_LEVEL: debug
  POMERIUM_DEBUG: true
  INSECURE_SERVER: true
  GRPC_INSECURE: true
  CODEC_TYPE: http1
  AUTHENTICATE_SERVICE_URL: https://authenticate.wfh.com
  AUTHORIZE_SERVICE_URL: http://pomerium-authorize
  AUTHENTICATE_CALLBACK_PATH: /oauth2/callback
  # DEFAULT_UPSTREAM_TIMEOUT: 1m
  # SERVICES: AUTHENTICATE, PROXY
  # HTTP_REDIRECT_ADDR: ":80"
image:
  repository: "pomerium/pomerium"
  # tag: "v0.14.0"
  tag: "debug"
  pullPolicy: "IfNotPresent"
```

I've been stuck on this for quite some time, if anyone could help (or even point me in the right direction) I'd really appreciate it.

Thank you!

**Comment by travisgroth** [comment]
Hi @ChristianKlass,

```
  c. User is redirected to something like: 
    https://monitor.wfh.com/.pomerium/callback/?pomerium_expiry=1622641439&pomerium_issued=1622641139&pomerium_redirect_uri=https%3A%2F%2Fmonitor.wfh.com%2Fwhoami&pomerium_session_encrypted=[SNIP]%3D
```

That redirect appears normal as part of auth flow.  What occurs at that point?  Are you receiving an error in the browser or the proxy service?  Could you share logs from `authenticate` and `proxy` services from when a user attempts a fresh login to a protected endpoint?

**Comment by ChristianKlass** [comment]
Sorry, I've stopped working on this, we went with another solution. 

Thanks for the response. Maybe it can be reopened if someone else encounters this issue.

**Comment by JokerQyou** [comment]
I had the exact same issue.

> That redirect appears normal as part of auth flow. What occurs at that point? Are you receiving an error in the browser or the proxy service? Could you share logs from `authenticate` and `proxy` services from when a user attempts a fresh login to a protected endpoint?

The error is: the domain `monitor.wfh.com` is not the one handling pomerium-related services, so it triggers a 404 error. The redirect happens like this:

- Visit `https://monitor.wfh.com/some_path/`
- Got redirect to `https://pomerium-autenticate-domain/.pomerium/sign_in?pomerium_expiry=1628524128&pomerium_issued=1628523828&pomerium_redirect_uri=https%3A%2F%2Fmonitor.wfh.com%2Fsome_path%2F&pomerium_signature=XXX%3D`
- Got redirect again, to `https://monitor.wfh.com/.pomerium/callback/?pomerium_expiry=1628524129&pomerium_issued=1628523829&pomerium_redirect_uri=https%3A%2F%2Fmonitor.wfh.com%2Fsome_path%2F&pomerium_session_encrypted=YYY&pomerium_signature=ZZZ%3D`

I think it happens when only proxying `monitor.wfh.com/whoami` to a container. For example, I want the user to be able to access an app via `monitor.wfh.com/whoami`, but do not care about `monitor.wfh.com/`. In this case `https://monitor.wfh.com/.pomerium/` will result in 404 error, since there is no matching router in traefik. However, I have not yet figured a way to workaround this issue.

**Comment by paul-bormans** [comment]
I'm facing the same issue (version pomerium:v0.20.0):

`https://authenticate.my-tenant-ingress-6.com/.pomerium/sign_in?pomerium_expiry=...&pomerium_idp_id=...&pomerium_issued=...&pomerium_redirect_uri=https%3A%2F%2Fmy-tenant-ingress-6.com%2Fgrafana&pomerium_signature=...
`
302 to:

`https://my-tenant-ingress-6.com/.pomerium/callback/?pomerium_expiry=...&pomerium_issued=...&pomerium_redirect_uri=https%3A%2F%2Fmy-tenant-ingress-6.com%2Fgrafana&pomerium_session_encrypted=...
`

But since there isn't a proxy path to https://my-tenant-ingress-6.com/ (only to https://my-tenant-ingress-6.com/grafana) it gives 404.

I guess the /.pomerium on any app path is handled by pomerium-authorize to 302 to the actual site (pomerium_redirect_uri)

I could workaround this by simply adding an Ingress route, i just need to feed it to pomerium i guess.

Another thought i had is missing trailing slash; perhaps its as easy as pomerium taking the basepath + /.pomerium?

Paul

**Comment by calebdoxsey** [comment]
Pomerium expects a callback after authenticate to `/.pomerium/callback/`. This request needs to be received by the Pomerium proxy. We bypass external authorization for this route in our Envoy config, so requests should not be sent to Authorize. If there is another HTTP proxy in front of Pomerium than that will likely cause problems and will need to be carefully configured so as to preserve the request so that Pomerium can handle it.

**Comment by paul-bormans** [comment]
It looks like this is where the callback url is build: https://github.com/pomerium/pomerium/blob/main/internal/handlers/sign_in.go#L40

It just takes the redirect_url (if no callback_url is given) and sets the path:

`callbackURL.Path = "/.pomerium/callback/"
`

**Comment by paul-bormans** [comment]
@calebdoxsey right, and indeed i have Traefik in front, but i expected the pomerium helm chart to render the required ingress'es; but by setting:
```
ingressController:
  enabled: false

forwardAuth:
  enabled: true
  internal: true
```
I only get the ingress for the authenticate service (for the callback from the external idp), but there is no ingress for the redirect issued by pomerium sign-in. I guess before i didn't notice because my app is running at / and so /.pomerium/callback was using the same ingress and it got 302'ed through the forwardauth...

Let me take another look in the helm ingress template maybe it is there but just not rendering given my config.

**Comment by paul-bormans** [comment]
I couldn't find the ingress definition in the chart template.

When i add following manually it works:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: pomerium-sign-in-callback
  namespace: pomerium
spec:
  ingressClassName: traefik
  rules:
  - host: my-tenant-ingress-6.com
    http:
      paths:
      - backend:
          service:
            name: pomerium-proxy
            port:
              name: https
        path: /.pomerium/callback
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - my-tenant-ingress-6.com
    secretName: pomerium-tls
```

And authorize the route:
```
config:
  routes:
    - from: https://my-tenant-ingress-6.com
      prefix: /.pomerium/callback/
      to: http://pomerium-proxy.pomerium.svc
      allow_any_authenticated_user: true
```
