### ISSUE TITLE
Identity verification failed

### ISSUE THREAD

**Issue by cfanbo** [pomerium/pomerium#2300]
## config.yaml

```
pomerium_debug: true
proxy_log_level: debug

authenticate_service_url: https://authenticate.localhost.pomerium.io/

autocert: false
autocert_use_staging: true


certificate_file: /home/sxf/mkcert/_wildcard.localhost.pomerium.io.pem # optional, defaults to `./cert.pem`
certificate_key_file: /home/sxf/mkcert/_wildcard.localhost.pomerium.io-key.pem # optional, defaults to `./certprivkey.pem`
certificate_authority_file: /home/sxf/mkcert/_wildcard.localhost.pomerium.io.pem

cookie_secret: NGkUAjzFyDiMnQ7DkYbgvuKAu/3qWVTBLsy8Xs36Df8=
shared_secret: 80ldlrU2d7w+wVpKNfevk6fmb8otEx6CqOfshj2LwhQ=

signing_key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUFVbVVPSGl5Rlg3M2RpcTJYcHNScThQcjBDMUxqeEo0ZVczLzVxbjMrTjJvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFeVFyQ1dJenhyQk4wNXcvSUFWUVhPb3J4a0xaNGlSWHRpbzFEOEFXelFEcGZnMzdtZXd4eApPNlJCS281OGtaRlRsdUEzYTFVWTBUNFdLSitOY05LdzR3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
signing_key_algorithm: ES256


idp_provider: oidc
idp_provider_url: http://localhost:8080/auth/realms/myrealm # keycloak
idp_client_id: myidp
idp_client_secret: myidp


idp_service_account: ewoJImNsaWVudF9pZCI6ICJteWlkcCIsCgkiY2xpZW50X3NlY3JldCI6ICJteWlkcCIKfQ==

jwt_claims_headers:
  - user
  - email
  - name

policy:
  - from: https://verify.localhost.pomerium.io
    to: https://verify.pomerium.com
    allowed_domains:
      - pomerium.io
    allowed_users:
      - sxf@test.com
    pass_identity_headers: true

```

===================================================
when user loginned success, url https://verify.localhost.pomerium.io/ display content is wrong, why?

```
## Identity verification failed
We tried to verify the incoming user, but failed with the following error: couldn't get json web key: Get "https://authenticate.localhost.pomerium.io/.well-known/pomerium/jwks.json": dial tcp 127.0.0.1:443: connect: connection refused


-------------------------------------
## Signed Identity Token

    No attestation JWT!


Pomerium adds a signed JWT token to the incoming request headers (X-Pomerium-Jwt-Assertion) which can then be used to assert a user's identity details.

-------------------------------------
## Unsigned Identity Headers
### Header 	
X-Pomerium-Claim-Email 	sxf@test.com
....
```

when access url https://authenticate.localhost.pomerium.io/.well-known/pomerium/jwks.json,  output text

> {"keys":[{"use":"sig","kty":"EC","kid":"1b43aa1e8413e53bd6117f9d88b5661de0187d20a237822671dc27653fb2e796","crv":"P-256","alg":"ES256","x":"yQrCWIzxrBN05w_IAVQXOorxkLZ4iRXtio1D8AWzQDo","y":"X4N-5nsMcTukQSqOfJGRU5bgN2tVGNE-FiifjXDSsOM"}]}
