### ISSUE TITLE
pomerium cann't provide service when listen 80

### ISSUE THREAD

**Issue by cfanbo** [pomerium/pomerium#2301]
pomerium can only listen port 443, can't it listenport 80?

now in my config file **config.yaml**
```
policy:
  - from: https://verify.localhost.pomerium.io
    to: https://verify.pomerium.com
```
is ok, but change to
```
address: ":80"
policy:
  - from: http://http.localhost
    to: http://backend
```
 Unable to provide service , why?
