### ISSUE TITLE
Identity Provider：keycloak, but not found group 

### ISSUE THREAD

**Issue by cfanbo** [pomerium/pomerium#2302]
config.yaml
```
authenticate_service_url: https://authenticate.localhost.pomerium.io/

autocert: false
autocert_use_staging: true

certificates:
  - cert: /home/sxf/mkcert/_wildcard.localhost.pomerium.io.pem
    key: /home/sxf/mkcert/_wildcard.localhost.pomerium.io-key.pem
  - cert: /home/sxf/mkcert/blog.localhost.pem
    key: /home/sxf/mkcert/blog.localhost-key.pem

# insecure_server: true

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
cookie_secret: NGkUAjzFyDiMnQ7DkYbgvuKAu/3qWVTBLsy8Xs36Df8=

shared_secret: 80ldlrU2d7w+wVpKNfevk6fmb8otEx6CqOfshj2LwhQ=

# If set, a JWT based signature is appended to each request header `x-pomerium-jwt-assertion`
signing_key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUFVbVVPSGl5Rlg3M2RpcTJYcHNScThQcjBDMUxqeEo0ZVczLzVxbjMrTjJvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFeVFyQ1dJenhyQk4wNXcvSUFWUVhPb3J4a0xaNGlSWHRpbzFEOEFXelFEcGZnMzdtZXd4eApPNlJCS281OGtaRlRsdUEzYTFVWTBUNFdLSitOY05LdzR3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
signing_key_algorithm: ES256

# keycloak
idp_provider: oidc
idp_provider_url: http://localhost:8080/auth/realms/myrealm # keycloak
idp_client_id: myidp # from the application the users login to
idp_client_secret: myidp # from the application the users login to

idp_service_account: ewoJImNsaWVudF9pZCI6ICJteWlkcCIsCgkiY2xpZW50X3NlY3JldCI6ICJteWlkcCIKfQ==

policy:
  - from: https://verify.localhost.pomerium.io
    to: https://verify.pomerium.com
    allowed_groups:
      - /techGroup
      - /group1
    pass_identity_headers: true
    time: 10s

```
I confirm that the group techGroup already exists in keycloak.  

![group](https://user-images.githubusercontent.com/887910/122735599-c3be3900-d2b1-11eb-8f4d-edb562b757e1.png)  

but output is no group found, why?

![err](https://user-images.githubusercontent.com/887910/122735957-1861b400-d2b2-11eb-829f-63b83f682897.png)

**Comment by cfanbo** [comment]
i'm using oidc，i found a message in source code 

```
// GetProvider gets the provider for the given options.
func GetProvider(options Options) (provider Provider) {
	globalProvider.Lock()
	defer globalProvider.Unlock()

	ctx := context.TODO()
	if globalProvider.provider != nil && cmp.Equal(globalProvider.options, options) {
		log.Debug(ctx).Str("provider", options.Provider).Msg("directory: no change detected, reusing existing directory provider")
		return globalProvider.provider
	}
	defer func() {
		globalProvider.provider = provider
		globalProvider.options = options
	}()

	var providerURL *url.URL
	// url.Parse will succeed even if we pass an empty string
	if options.ProviderURL != "" {
		providerURL, _ = url.Parse(options.ProviderURL)
	}
	switch options.Provider {
	case auth0.Name:
		serviceAccount, err := auth0.ParseServiceAccount(options)
		if err == nil {
			return auth0.New(
				auth0.WithDomain(options.ProviderURL),
				auth0.WithServiceAccount(serviceAccount))
		}
		log.Warn(ctx).
			Str("service", "directory").
			Str("provider", options.Provider).
			Err(err).
			Msg("invalid service account for auth0 directory provider")
	case azure.Name:
		serviceAccount, err := azure.ParseServiceAccount(options)
		if err == nil {
			return azure.New(azure.WithServiceAccount(serviceAccount))
		}
		log.Warn(ctx).
			Str("service", "directory").
			Str("provider", options.Provider).
			Err(err).
			Msg("invalid service account for azure directory provider")
	case github.Name:
		serviceAccount, err := github.ParseServiceAccount(options.ServiceAccount)
		if err == nil {
			return github.New(github.WithServiceAccount(serviceAccount))
		}
		log.Warn(ctx).
			Str("service", "directory").
			Str("provider", options.Provider).
			Err(err).
			Msg("invalid service account for github directory provider")
	case gitlab.Name:
		serviceAccount, err := gitlab.ParseServiceAccount(options.ServiceAccount)
		if err == nil {
			if providerURL == nil {
				return gitlab.New(gitlab.WithServiceAccount(serviceAccount))
			}
			return gitlab.New(
				gitlab.WithURL(providerURL),
				gitlab.WithServiceAccount(serviceAccount))
		}
		log.Warn(ctx).
			Str("service", "directory").
			Str("provider", options.Provider).
			Err(err).
			Msg("invalid service account for gitlab directory provider")
	case google.Name:
		serviceAccount, err := google.ParseServiceAccount(options.ServiceAccount)
		if err == nil {
			return google.New(google.WithServiceAccount(serviceAccount))
		}
		log.Warn(ctx).
			Str("service", "directory").
			Str("provider", options.Provider).
			Err(err).
			Msg("invalid service account for google directory provider")
	case okta.Name:
		serviceAccount, err := okta.ParseServiceAccount(options.ServiceAccount)
		if err == nil {
			return okta.New(
				okta.WithProviderURL(providerURL),
				okta.WithServiceAccount(serviceAccount))
		}
		log.Warn(ctx).
			Str("service", "directory").
			Str("provider", options.Provider).
			Err(err).
			Msg("invalid service account for okta directory provider")
	case onelogin.Name:
		serviceAccount, err := onelogin.ParseServiceAccount(options.ServiceAccount)
		if err == nil {
			return onelogin.New(onelogin.WithServiceAccount(serviceAccount))
		}
		log.Warn(ctx).
			Str("service", "directory").
			Str("provider", options.Provider).
			Err(err).
			Msg("invalid service account for onelogin directory provider")
	case ping.Name:
		serviceAccount, err := ping.ParseServiceAccount(options.ServiceAccount)
		if err == nil {
			return ping.New(
				ping.WithProviderURL(providerURL),
				ping.WithServiceAccount(serviceAccount))
		}
		log.Warn(ctx).
			Str("service", "directory").
			Str("provider", options.Provider).
			Err(err).
			Msg("invalid service account for ping directory provider")
	}

	log.Warn(ctx).
		Str("provider", options.Provider).
		Msg("no directory provider implementation found, disabling support for groups")
	return nullProvider{}
}
```
 not support get user group for oidc provider

**Comment by travisgroth** [comment]
Hi @cfanbo,

`allowed_groups` does indeed only work with directory sync enabled providers.  However, we support setting policy based on oidc claims.  

You need to add this to your config:

```yaml
idp_scopes: profile,email,groups,openid
```

You should see groups as a _claim_ rather than a group list on the user info endpoint:

![image](https://user-images.githubusercontent.com/6198562/122947163-f31f8500-d347-11eb-8f45-16dd79ac7423.png)

At that point you can set policy like so:

```yaml
policy:
  - from: https://httpbin.localhost.pomerium.io
    to: https://httpbin.org
    allowed_idp_claims:
      groups:
        - admins
```
