### ISSUE TITLE
Reload of certificates when Re-issued/Renewed

### ISSUE THREAD

**Issue by davidcollom** [pomerium/pomerium#2308]
## What happened?
When the mTLS certificates are rotated (stored in a secret) the certificates are not reloaded, resulting in a 500 response.

## What did you expect to happen?
Certificates should be reloaded from disk and service should continue to work uninterupted.

## How'd it happen?

1. Create a SelfSigned Cert of 1 hour (we used cert-manager to handle generation and renewal)
2. Start up Pomerium (we use individual pods for each component (authorize, authenticate, cache etc...)
3. Authenticate with service Successfully
4. Wait for Certificate to expire
5. Attempt to access original service

## What's your environment like?

- Pomerium version: `v0.14.2`
- Server Operating System/Architecture/Cloud: GKE - `v1.19.9-gke.1900`

## What's your config.yaml?

```config.yaml
  config.yaml: |-
    address: ":443"
    grpc_address: ":443"
    certificate_file: "/pomerium/cert.pem"
    certificate_key_file: "/pomerium/privkey.pem"
    certificate_authority_file: "/pomerium/ca.pem"
    authenticate_service_url: https://login.xxxxx
    authorize_service_url: https://pomerium-authorize.authentication.svc.cluster.local
    databroker_service_url: https://pomerium-cache.authentication.svc.cluster.local
    databroker_storage_type: memory
    idp_provider: oidc
    idp_scopes: [openid email groups profile]
    idp_provider_url: https://xxxxxxxxxxxxxxxxxx
    forward_auth_url: https://forwardauth.xxxx
    idp_client_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    policy:
      - allowed_idp_claims:
          perms:
          - xxxxxxxxxxxxxxxxxxx
          - yyyyyyyyyyyyyyyyyy
        from: https://test-endpoint.xxxxxxxxxxxxx
        to: https://test-endpoint.xxxxxxxxxxxxx
```

## What did you see in the logs?

```logs
pomerium-proxy-7bcb9d48cd-7hbgt pomerium {"level":"info","service":"envoy","upstream-cluster":"","method":"GET","authority":"forwardauth.xxxxxxxxxxxxxxxxx","path":"/verify","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36","referer":"https://test-endpoint.xxxxxxxxxxxxx","forwarded-for":"10.68.2.34,10.68.5.47","request-id":"def332c9-469a-4bef-b601-8443d2c7b9af","duration":9.926126,"size":11249,"response-code":401,"response-code-details":"ext_authz_denied","time":"2021-06-23T08:34:32Z","message":"http-request"}
pomerium-proxy-7bcb9d48cd-fxq9n pomerium {"level":"info","service":"envoy","upstream-cluster":"","method":"GET","authority":"forwardauth.xxxxxxxxxxxxx","path":"/verify","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36","referer":"https://test-endpoint.xxxxxxxxxxxxx","forwarded-for":"10.64.0.4,10.68.2.34","request-id":"b40cc7cd-f1a4-4e7c-9c69-9eb8251cf7d5","duration":6.174099,"size":11249,"response-code":401,"response-code-details":"ext_authz_denied","time":"2021-06-23T08:34:32Z","message":"http-request"}
```

I do however see the following log lines:
```
pomerium-authenticate-748d49648b-r9qdl pomerium {"level":"warn","time":"2021-06-23T08:37:12Z","msg":"stapling OCSP","service":"autocert","error":"no OCSP stapling for [pomerium-authenticate pomerium-authenticate.authentication pomerium-authenticate.authentication.svc pomerium-authenticate.authentication.svc.cluster.local]: no OCSP server specified in certificate"}
```
But I would still expect this to reload the certificate.

I never see any requests 

## Additional context

Cert-Manager resources:
```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: pomerium-issuer
  namespace: authentication
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: pomerium-ca
  namespace: authentication
spec:
  ca:
    secretName: pomerium-ca-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-ca
  namespace: authentication
spec:
  isCA: true
  commonName: pomerium
  secretName: pomerium-ca-tls
  issuerRef:
    name: pomerium-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-databroker-client-tls
  namespace: authentication
spec:
  duration: "1h"
  dnsNames:
  - pomerium-cache
  - pomerium-cache.authentication
  - pomerium-cache.authentication.svc
  - pomerium-cache.authentication.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: pomerium-ca
    group: cert-manager.io
  secretName: pomerium-databroker-client-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-authenticate-tls
spec:
  duration: "1h"
  dnsNames:
  - pomerium-authenticate
  - pomerium-authenticate.authentication
  - pomerium-authenticate.authentication.svc
  - pomerium-authenticate.authentication.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: pomerium-ca
    group: cert-manager.io
  secretName: pomerium-authenticate-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-authorize-tls
spec:
  duration: "1h"
  dnsNames:
  - pomerium-authorize
  - pomerium-authorize.authentication
  - pomerium-authorize.authentication.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: pomerium-ca
    group: cert-manager.io
  secretName: pomerium-authorize-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-proxy-tls
spec:
  duration: "1h"
  dnsNames:
  - pomerium-proxy
  - pomerium-proxy.authentication
  - pomerium-proxy.authentication.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: pomerium-ca
    group: cert-manager.io
  secretName: pomerium-proxy-tls
```
