### ISSUE TITLE
404 issue after authentication 

### ISSUE THREAD

**Issue by amolvishwakarma** [pomerium/pomerium#2342]
I have three subdomains basically which are running on https on port 443:
1.) authenticate.example.com
2.) verify.example.com
3.) pomerium.example.com
All shows 404 google authentication is working properly.

**Comment by amolvishwakarma** [comment]
# log: 
INF http-request authority=pomerium.example.com duration=0.829666 forwarded-for=someip method=GET path=/ referer= request-id=5496ccc7-46f2-4a58-90be-4aad50b62e0a response-code=404 response-code-details=route_not_found service=envoy size=0 upstream-cluster= user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"

**Comment by amolvishwakarma** [comment]
PFA verify.example.com
![image](https://user-images.githubusercontent.com/57523705/124894197-11001180-dff9-11eb-8055-c096f4b7942d.png)

**Comment by travisgroth** [comment]
Hi,

Please share your redacted configuration, version, environment details, etc.  The [bug template](https://github.com/pomerium/pomerium/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) is a good list of things that would be helpful in debugging.

**Comment by amolvishwakarma** [comment]
Hi @travisgroth ,
I am using docker compose version:1.21.2 . Please find the details below : 

Below is my config.yaml file .  

pomerium_debug: true
proxy_log_level: debug
authenticate_service_url: https://authenticate.example.com
forward_auth_url: https://verify.example.com
certificates:
- cert: "/pomerium/pomerium.pem"
  key: "/pomerium/pomeriumkey.pem"
- cert: "/pomerium/authenticate.pem"
  key: "/pomerium/authkey.pem"
- cert: "/pomerium/verify.pem"
  key: "/pomerium/verifykey.pem"

# identity provider settings : https://www.pomerium.io/docs/identity-providers.html
idp_provider: google
idp_provider_url: https://accounts.google.com
idp_client_id: xxxxxxxxxxx.apps.googleusercontent.com
idp_client_secret: xxxxxxxxxxx

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
cookie_secret: 256 bit random string
jwt_claims_headers:
- email
- groups
- user
# https://www.pomerium.io/configuration/#policy
policy:
  - from: https://verify.example.com
    to: https://pomerium.example.com
    allowed_domains:
      - example.com
    allowed_users:
      - amol.vishwakarma@example.com
    pass_identity_headers: true
    cors_allow_preflight: true
    timeout: 30s
    
 # Docker-compose yaml config file
 
 version: "3"
services:
  pomerium:
    image: pomerium/pomerium:master
    environment:
      # Generate new secret keys. e.g. `head -c32 /dev/urandom | base64`
      - COOKIE_SECRET= base64randomstrings
    volumes:
      # Mount your domain's certificates : https://www.pomerium.io/docs/reference/certificates
      - ~/pomerium/certs/authenticate.pem:/pomerium/authenticate.pem:ro
      -  ~/pomerium/certs/authkey.pem:/pomerium/authkey.pem:ro
      - ~/pomerium/certs/verify.pem:/pomerium/verify.pem:ro
      -  ~/pomerium/certs/verifykey.pem:/pomerium/verifykey.pem:ro
      - ~/pomerium/certs/pomerium.pem:/pomerium/pomerium.pem:ro
      -  ~/pomerium/certs/pomeriumkey.pem:/pomerium/pomeriumkey.pem:ro
      # Mount your config file : https://www.pomerium.io/docs/reference/reference/
      - ~/pomerium/config.yaml:/pomerium/config.yaml:ro
    ports:
      - 443:443

  # https://verify.corp.beyondperimeter.com --> Pomerium --> http://verify
  verify:
    image: pomerium/verify:latest
    expose:
      - 80

**Comment by amolvishwakarma** [comment]
Please reply how can i fix this @travisgroth @calebdoxsey

**Comment by travisgroth** [comment]
It's very difficult to read your configuration since it isn't block quoted.  However, you have a `forward_auth_url` configured to overlap with the route definition in `from`.  

> forward_auth_url: https://verify.example.com

> from: https://verify.example.com


If you're not using another reverse proxy in conjunction with Pomerium, you should remove the `forward_auth_url` line from your configuration.

**Comment by amolvishwakarma** [comment]
Below is my config.yaml  file as per your suggestion ,I had removed forward_auth_url but it is still not working @travisgroth 
```
pomerium_debug: true
proxy_log_level: debug
authenticate_service_url: https://authenticate.example.in

certificates:
- cert: "/pomerium/pomerium.pem"
  key: "/pomerium/pomeriumkey.pem"
- cert: "/pomerium/authenticate.pem"
  key: "/pomerium/authkey.pem"
- cert: "/pomerium/verify.pem"
  key: "/pomerium/verifykey.pem"

idp_provider: google
idp_provider_url: https://accounts.google.com
idp_client_id: 225154033206-bb953c4rff0ogmde5e9ggpudme6ahn2t.apps.googleusercontent.com
idp_client_secret: dPkcYIsHbv-BJGlyRLDUBCQB

cookie_secret: rE+0d1WIXcVKkXH5WZeUm8ZaiFTRfsQ4y0ar4iKFrvs=

policy:
  - from: https://verify.example.in
    to: https://pomerium.example.in
    allowed_domains:
      - focalworks.in
```
