### ISSUE TITLE
Websocket not working if the upstream is HTTPS

### ISSUE THREAD

**Issue by xlejo** [pomerium/pomerium#2388]
## What happened?

Pomerium fails when try upgrade the connection if the upstream is HTTPS. Pomerium return me a HTTP 400.

If the upstream is HTTP Pomerium upgrade the connection without problems.

## What did you expect to happen?

Upgrade the connection successfully.

## How'd it happen?

1. Install Pomerium with the Helm chart.
2. Config the policy in Pomerium:

```yaml
 - from: https://cryptpad.example.com
   to: https://cryptpad.inside.example.com
   allow_any_authenticated_user: true
   preserve_host_header: true
   allow_websockets: true
   tls_client_cert_file: /pomerium/certs/tls.crt
   tls_client_key_file: /pomerium/certs/tls.key
   tls_custom_ca_file: /pomerium/certs/ca.crt
   tls_server_name: cryptpad.example.com
 - from: https://cryptpad-sandbox.example.com
   to: https://cryptpad-sandbox.inside.example.com
   allow_any_authenticated_user: true
   preserve_host_header: true
   allow_websockets: true
   tls_client_cert_file: /pomerium/certs/tls.crt
   tls_client_key_file: /pomerium/certs/tls.key
   tls_custom_ca_file: /pomerium/certs/ca.crt
   tls_server_name: cryptpad-sandbox.example.com
```
3. Setup a Ingress with HTTPS in the upstream.
4. Expose the 443/TCP of the Pomerium Proxy
5. Connect to  `https://cryptpad.example.com`
6. Try to register

## What's your environment like?

- Pomerium version 0.14.7
- Kubernetes v1.21.2
- Nginx Ingress Controller v0.47.0

## What's your config.yaml?

```config.yaml
address: ":443"
grpc_address: ":443"
certificate_file: "/pomerium/tls/tls.crt"
certificate_key_file: "/pomerium/tls/tls.key"
certificate_authority_file: "/pomerium/ca/ca.crt"
certificates:
  - cert: /etc/pomerium/tls/pomerium-tls/tls.crt
    key: /etc/pomerium/tls/pomerium-tls/tls.key
authenticate_service_url: https://authenticate.example.com
authorize_service_url: https://pomerium-authorize.pomerium.svc.cluster.local
databroker_service_url: https://pomerium-databroker.pomerium.svc.cluster.local
idp_provider: oidc
idp_scopes: [openid profile email]
idp_provider_url: https://keycloak.example.com/auth/realms/example-realm
cookie_secret: <hide>
shared_secret: <hide>
idp_client_id: <hide>
idp_client_secret: <hide>
databroker_storage_type: memory    
policy:
  - from: https://cryptpad.example.com
    to: https://cryptpad.inside.example.com
    allow_any_authenticated_user: true
    preserve_host_header: true
    allow_websockets: true
    tls_client_cert_file: /pomerium/certs/tls.crt
    tls_client_key_file: /pomerium/certs/tls.key
    tls_custom_ca_file: /pomerium/certs/ca.crt
    tls_server_name: cryptpad.example.com
  - from: https://cryptpad-sandbox.example.com
    to: https://cryptpad-sandbox.inside.example.com
    allow_any_authenticated_user: true
    preserve_host_header: true
    allow_websockets: true
    tls_client_cert_file: /pomerium/certs/tls.crt
    tls_client_key_file: /pomerium/certs/tls.key
    tls_custom_ca_file: /pomerium/certs/ca.crt
    tls_server_name: cryptpad-sandbox.example.com
```

## What did you see in the logs?

```logs
{"level":"info","service":"envoy","upstream-cluster":"route-b5e8a2273462802c","method":"GET","authority":"cryptpad.example.com","path":"/cryptpad_websocket","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36","referer":"","forwarded-for":"10.42.2.1","request-id":"7a668054-a6c6-4de7-b151-33ecaec69fe6","duration":21.280477,"size":150,"response-code":400,"response-code-details":"via_upstream","time":"2021-07-23T20:14:01Z","message":"http-request"}
```

## Additional context

I try other services like Buildbot or Nextcloud and is the same.

Thanks to all the people of Pomerium!

**Comment by travisgroth** [comment]
Hi - is there any error message from the upstream service?  The log indicates the upstream service isn't happy with the upgrade.  It would be helpful to know what the upstream had an issue with.

**Comment by wasaga** [comment]
in the first route, you are providing `tls_server_name` that is equal to server name in the `from` field. However the usage of this option is https://pomerium.io/reference/#tls-server-name 

_TLS Server Name overrides the hostname specified in the to field. If set, this server name will be used to verify the certificate name_

in order to rule out the mTLS issue between pomerium not trusting your upstream server `cryptpad.inside.example.com` certificate chain, you may temporarily disable upstream certificate checks using `tls_skip_verify` https://pomerium.io/reference/#tls-skip-verification

**Comment by wasaga** [comment]
> Setup an Ingress with HTTPS in the upstream.

in case of double-proxying, i.e. if you have the following configuration:

```
[external ingress] => [internal ingress] => [websocket server]
```

most websocket libraries would fail an upgrade request due to `Host` and `Origin` not matching, and you may need to manually adjust the Host header that reaches the websocket server to match the original request host. 

i.e. for pomerium used for both external and internal: 

*external*

```yaml
policies: 
   - from: https://site.example.com
      to: https://site.internal.example.com
      allow_websockets: true
```

*internal*
```yaml
policies: 
   - from: https://site.internal.example.com
      to: http://ws-server.internal.example.com
      allow_websockets: true
      host_rewrite: "site.example.com"
```
