### ISSUE TITLE
Upstream application doesn't get pomerium headers

### ISSUE THREAD

**Issue by rguichard** [pomerium/pomerium#2723]
## What happened?

My upstream application doesn't get any Pomerium headers, neither X-Pomerium-Jwt-Assertion or X-Pomerium-Claim-*.

## What did you expect to happen?

Some headers, please.

## What's your environment like?

- Pomerium version 0.15.2 
- Pomerium Helm chart 24.0.0 (operator enabled)

Pomerium is in forwardAuth mode and Traefik is my Ingress Controller
## What's your config.yaml?

```config.yaml
address: :443
grpc_address: :443
certificate_file: "/pomerium/tls/tls.crt"
certificate_key_file: "/pomerium/tls/tls.key"
certificate_authority_file: "/pomerium/ca/ca.crt"
authenticate_service_url: https://authenticate.tld
authorize_service_url: https://pomerium-authorize.pomerium-external.svc.cluster.local
databroker_service_url: https://pomerium-databroker.pomerium-external.svc.cluster.local
idp_provider: azure
idp_scopes: 
idp_provider_url: ***

set_response_headers:
  X-Test: X-Value
forward_auth_url: https://pomerium-proxy.pomerium-external
cookie_secret: ***
shared_secret: ***
idp_client_id: ***
idp_client_secret: ***
databroker_storage_type: memory    
policy:
  - allowed_domains:
    - kering.com
    from: https://napp-app-mr-119.napp.tld
    pass_identity_headers: true
    preserve_host_header: true
    to: http://napp-app-mr-119.napp-app-mr-119.svc.cluster.local
```

Traefik middleware:
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  annotations:
  name: internal-auth
  namespace: pomerium-external
spec:
  forwardAuth:
    address: https://pomerium-proxy.pomerium-external
    authResponseHeaders:
    - X-Pomerium-Authenticated-User-Email
    - x-pomerium-authenticated-user-id
    - x-pomerium-authenticated-user-groups
    - x-pomerium-jwt-assertion
    tls:
      insecureSkipVerify: true
    trustForwardHeader: true
  forwardHeaders:
    insecure: true
```

Application Ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    ingress.pomerium.io/allowed_domains: '["tld"]'
    ingress.pomerium.io/pass_identity_headers: "true"
    ingress.pomerium.io/preserve_host_header: "true"
    kubernetes.io/ingress.class: traefik-internal
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: pomerium-external-internal-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: napp-app-mr-119
  namespace: napp-app-mr-119
spec:
  rules:
  - host: app-mr-119.napp.tld
    - http:
      paths:
      - backend:
          serviceName: napp-app-mr-119
          servicePort: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - app-mr-119.napp.tld
    secretName: app-mr-119.napp.tld
```

(This issue was started on Slack https://pomerium-io.slack.com/archives/CK92MUAES/p1634911910003100)
