### ISSUE TITLE
docs: traefik example uses legacy claim names

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/pomerium#2728]
## What happened?
Our traefik example is using the legacy `x-pomerium-authenticated-user-` claim names:

```yaml
  verify:
    # A container that exposes an API to show its IP address
    image: pomerium/verify:latest
    labels:
      - "traefik.http.routers.verify.rule=Host(`verify.corp.example.com`)"
      # Create a middleware named `foo-add-prefix`
      - "traefik.http.middlewares.test-auth.forwardauth.authResponseHeaders=X-Pomerium-Authenticated-User-Email,x-pomerium-authenticated-user-id,x-pomerium-authenticated-user-groups,x-pomerium-jwt-assertion"
      - "traefik.http.middlewares.test-auth.forwardauth.address=http://forwardauth.corp.example.com/?uri=https://verify.corp.example.com"
      - "traefik.http.routers.verify.middlewares=test-auth@docker"
```

## What did you expect to happen?
It should be using `x-pomerium-claim-` names. See https://www.pomerium.io/reference/#jwt-claim-headers

> Use this option if you previously relied on x-pomerium-authenticated-user-{email|user-id|groups}.
