### ISSUE TITLE
Redirect loop with Redis databroker

### ISSUE THREAD

**Issue by dannytech** [pomerium/pomerium#2729]
## What happened?

When the Redis databroker is enabled, Pomerium is entering a redirect loop when I try to access any proxied service requiring authentication.

## What did you expect to happen?

Pomerium should redirect to its `authenticate_service_url` for authn/authz, then redirect back to the service successfully (i.e. a 302 to the service URL, a 302 back to a callback URL, a 302 back to what I was trying to originally access, and the service loads successfully at that point).

## How'd it happen?

1. Navigated to the URL of any service behind Pomerium (say, `service1.example.com`)
2. As expected, got redirected to my `authenticate_service_url` (`gateway.example.com`)
3. From there, redirected to my Keycloak service (`auth.example.com`), which is behind Pomerium but has public unauthenticated access enabled
4. Logged in, redirected back to `gateway.example.com`, and if I later go to `gateway.example.com/.pomerium/` it shows I am logged in

Everything up to this point is working fine. I am logged in successfully, I don't get sent back to Keycloak to log in again or anything. When it redirects me back to the service I was initially trying to access, that's when the issue happens.

5. Redirected to `service1.example.com/.pomerium/callback`, which sets the `_pomerium` cookie on the `service1.example.com` domain
6. Redirected to just `service1.example.com/` (which is what I was initially trying to access)
7. When the request is made to `service1.example.com/` (with the `_pomerium` cookie), the response is a 302 back to `gateway.example.com`, which then redirects back to `service1.example.com` and so on

The loop looks like this:

1. `GET service1.example.com/` > `302 gateway.example.com/.pomerium/sign_in?`
2. `GET gateway.example.com/.pomerium/sign_in?` > `302 service1.example.com/.pomerium/callback?` (`Set-Cookie: _pomerium` on `gateway.example.com`)
3. `GET service1.example.com/.pomerium/callback?` > `302 service1.example.com/` (`Set-Cookie: _pomerium` on `service1.example.com`)
4. Back to 1

## What's your environment like?

- Pomerium version:

```yaml
pomerium: 0.15.5-1634935076+3003e431
envoy: 1.19.1+c5ecc1e167273edac76f6c07f980ed5a728f4b7e077679d74cfbc59c087933e5
```

- Server Operating System/Architecture/Cloud: Ubuntu Server 20.04.1 with 5.8.0-1039-azure kernel (x86_64)

Other important info:

- Pomerium is running behind an Nginx reverse proxy (config below)
- Pomerium is using a Redis server on localhost

## What's your config?

Not my exact config, but able to reproduce the issue with the below config. Nginx config is also trimmed to remove a health check/metrics endpoint that is unrelated and not used by Pomerium.

Pomerium config:

```yml
address: "[::1]:8443"
metrics_address: "127.0.0.1:9090"

authenticate_service_url: https://gateway.example.com
insecure_server: true

debug: true

cookie_secret: <generated with openssl rand -base64 32>
shared_secret: <generated with openssl rand -base64 32>

databroker_storage_type: redis
databroker_storage_connection_string: redis://ip6-localhost/

idp_provider: oidc
idp_client_id: <removed>
idp_client_secret: <removed>
idp_provider_url: https://auth.example.com/auth/realms/<name>

log_level: debug

policy:
- from: &auth https://auth.example.com
  to: *auth
  allow_public_unauthenticated_access: true

- from: &service1 https://service1.example.com
  to: *service1
  allow_any_authenticated_user: true
```

Nginx configuration:

```nginx
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name *.example.com;

    ssl_certificate /etc/ssl/certs/*.example.com.crt;
    ssl_certificate_key /etc/ssl/private/*.example.com.pem;

    add_header X-Robots-Tag "none" always;
    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "same-origin" always;

    location / {
        proxy_pass http://ip6-localhost:8443/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_buffer_size 64k;
        proxy_buffers 8 64k;
        proxy_busy_buffers_size 64k;
    }

    location = /.metrics {
        proxy_pass http://localhost:9090/metrics;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        access_log off;
    }
}
```

## What did you see in the logs?

I have been unable to get Pomerium logging working properly (had to use systemd to output stdout to a file, which breaks a lot for some reason, not sure if there's a better way). I do have Nginx logs, though.

```logs
<removed IP> - - [31/Oct/2021:20:05:37 -0700] "GET / HTTP/2.0" 302 10665 "-" "<removed user agent>"
<removed IP> - - [31/Oct/2021:20:05:37 -0700] "GET /.pomerium/sign_in?pomerium_expiry=1635736237&pomerium_issued=1635735937&pomerium_redirect_uri=https%3A%2F%2Fservice1.example.com%2F&pomerium_signature=<removed> HTTP/2.0" 302 985 "-" "<removed user agent>"
<removed IP> - - [31/Oct/2021:20:05:37 -0700] "GET /.pomerium/callback/?pomerium_expiry=1635736237&pomerium_issued=1635735937&pomerium_redirect_uri=https%3A%2F%2Fservice1.example.com%2F&pomerium_session_encrypted=<removed>&pomerium_signature=<removed> HTTP/2.0" 302 56 "-" "<removed user agent>"
```

## Additional context

By capturing traffic on the loopback interface, I determined that the 302s are originating from Pomerium, not Nginx.
