### ISSUE TITLE
ENV interpolation/substitution in config settings

### ISSUE THREAD

**Issue by robertgates55** [pomerium/pomerium#2761]
Not all settings are settable directly with environment variables. Eg https://www.pomerium.com/reference/#set-request-headers

Others might require combinations (eg combining multiple ENVs into one setting var - `"${ONE)_${TWO}"`).

It'd be useful to be able to have this keys interpolated/substituted:

```
- from: https://verify.corp.example.com
  to: https://verify.pomerium.com
  policy:
    - allow:
        or:
          - email:
              is: user@example.com
  set_request_headers:
    # works auto-magically!
    # https://verify.corp.example.com/basic-auth/root/hunter42
    Authorization: "Basic ${SOME_BASIC_AUTH_ENV_VARIABLE}"
    X-Your-favorite-authenticating-Proxy: "Pomerium"
```

Is this possible?
