### ISSUE TITLE
Infinite redirect loop when users are authenticated but not authorized

### ISSUE THREAD

**Issue by sherifkayad** [pomerium/pomerium#2796]
## What happened?
**DISCLAIMER:** I know that similar issues have been reported in the past, however, here it's still happening with a relatively new version of Pomerium.

I setup Pomerium behind Nginx Ingress and using it in the `forwardauth` mode + the Pomerium Operator (OR even with the new Ingress Contoller as this issue here is relevant for both). I also do use the standard annotations e.g. `ingress.pomerium.io/allowed_idp_claims: '"groups": ["Group X", "Group Y"]'`

As long as the user is authorized, everything works like a charm and we are really happy about that! .. Problems occur though when people are authenticated but not authorized e.g. if the user neither belongs to group `Group X` nor `Group Y`. In that case we get an infinite redirect loop.

## What did you expect to happen?
The user should get a `403 (Forbidden)` and not an infinite redirect loop!

## How'd it happen?
Check the `What happened?` section above .. just some observations I had after some trials was that the reason for that infinite loop was basically the `401` code returned by the `/verify` endpoint of the forward auth when users aren't authorized. 
- Fresh session => user still not logged in => `/verify` returns a `401` code
- The `auth-signin` e.g. `https://forwardauth.mydomain.com/?uri=https://$host$request_uri` kicks in and redirects the user to the login screen of the underlying IDP
- After successful login, the Pomerium Token is generated, however, the `/verify` endpoint is still resulting in a `401`
- The user gets redirected again to the `auth-signin`, however this time the login screen is skipped and the user is redirected to the application endpoint
- Nginx checks the `/verify` endpoint => getting `401`, the loop kicks in indefinitely!

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 0.15.2 // Helm chart version: 24.0.0
- Server Operating System/Architecture/Cloud: AWS EKS + Ingress Nginx and Pomerium being used in `forwardauth` mode

## What's your config.yaml?

```config.yaml
shared_secret: somesecret=
address: :80
insecure_server: true
policy:
- from: https://demo2.mydomain.com
  to: http://demo.icon-sbx.svc.cluster.local:8080
  allowed_idp_claims:
    groups:
    - Team X
    - Team Y
authenticate_service_url: https://pomerium.mydomain.com
cookie_secret: secret=
idp_client_id: client
idp_client_secret: secret
idp_provider: oidc
idp_provider_url: https://myidp.com
idp_scopes:
- openid profile email groups offline_access
idp_service_account: pomerium-authenticate
idp_qps: 0
authorize_service_url: http://pomerium-authorize.pomerium.svc.cluster.local
tracing_zipkin_endpoint: ""
grpc_address: :80
grpc_insecure: true
forward_auth_url: https://forwardauth.mydomain.com
databroker_service_url: http://pomerium-databroker.pomerium.svc.cluster.local
databroker_storage_type: redis
databroker_storage_connection_string: rediss://:password@redis-server
databroker_storage_tls_skip_verify: true
```

## My Ingress
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-secure-ingress
  labels:
    app: base
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: "https://forwardauth.mydomain.com/?uri=https://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-url: "https://forwardauth.mydomain.com/verify?uri=https://$host$request_uri"
    ingress.pomerium.io/from: "https://demo.mydomain.com"
    ingress.pomerium.io/allowed_idp_claims: '"groups": ["Team X", "Team Y"]'
spec:
  ingressClassName: nginx
  rules:
  - host: demo.mydomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo
            port:
              number: 8080
```

## What did you see in the logs?
nothing interesting / relevant in my opinion.

## Additional context

I tried upgrading to the latest version of Pomerium and the Ingress Controller, however, that didn't work as well. In fact I had other bigger problems with the annotations so I reverted back.
