### ISSUE TITLE
authorize does not check 'to' field in policy configuration

### ISSUE THREAD

**Issue by pecigonzalo** [pomerium/pomerium#291]
**Describe the solution you'd like**

Currently the authorizer requires a minimal config as follows
```
policy:
  - from: https://httpbin.domain.tld
    to: http://httpbin
    allowed_domains:
      - domain.tld
  - from: https://external-httpbin.domain.tld
    to: http://httpbin
    allow_public_unauthenticated_access: true
```
If `to:` section is removed, it will complain that it is missing. Ideally, it should allow to be empty as  https://github.com/pomerium/pomerium/blob/master/authorize/identity.go#L64-L77 does not use the `to: ` field (which makes sense as policies are usually set for external domains).

This would allow for this sort of config, which simplifies and detaches `authz` and `authn` responsibilities completely, as they dont have to know about each other.
- **authz.yml**
```
policy:
  - from: https://httpbin.domain.tld
    allowed_domains:
      - domain.tld
```
- **proxy.yml**
```
authenticate_service_url: https://authn.domain.tld
authorize_service_url: https://authz.domain.tld
policy:
  - from: https://httpbin.domain.tld
    to: http://httpbin
  - from: https://external-httpbin.domain.tld
    to: http://httpbin
    allow_public_unauthenticated_access: true
```
- **authn.yml**
```
authenticate_service_url: https://authn.domain.tld
idp_provider: google
idp_client_id: REPLACE_ME
idp_client_secret: REPLACE_ME
# idp_service_account: REPLACE_ME
```

### Workaround
As a workaround, we can just set `authz` configuration to dummy values
```
policy:
  - from: https://httpbin.domain.tld
    to: https://domain.tld
    allowed_domains:
      - domain.tld
```
