### ISSUE TITLE
404 after WebAuthN Registration

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium#2920]
## What happened?

From the user info page on the authenticate service, I attempted to register a device.  During the subsequent flow, I received a 404 from `https://authenticate.localhost.pomerium.io/.pomerium/callback/?pomerium_expiry=1641914073&pomerium_issued=1641913773&pomerium_redirect_uri=[snip]`

## What did you expect to happen?

Not a 404

## How'd it happen?

1. Open to `https://authenticate.localhost.pomerium.io`
2. Scroll to `Register device with WebAuthn.`
3. Click WebAuthn link
4. Allow registration
5. Envoy 404 is displayed
6. The device is registered anyway

![image](https://user-images.githubusercontent.com/6198562/148970650-42d02be9-d8e6-4211-9369-7352f8e10ab2.png)

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): v0.16.0
- Server Operating System/Architecture/Cloud: Kubernetes Helm Chart v26.0.1

## What's your config.yaml?

```config.yaml
autocert: false
dns_lookup_family: V4_ONLY
address: :443
grpc_address: :443
certificate_authority_file: "/pomerium/ca/ca.crt"
certificates:
http_redirect_addr: :80
authenticate_service_url: https://authenticate.localhost.pomerium.io
authorize_service_url: https://pomerium-authorize.pomerium-test.svc.cluster.local
databroker_service_url: https://pomerium-databroker.pomerium-test.svc.cluster.local
idp_provider: okta
idp_scopes:
idp_provider_url: https://dev-xxxxx.okta.com
cookie_secret: XXXX
shared_secret: XXXX
idp_client_id: XXXX
idp_client_secret: XXXX
idp_service_account: XXXX
routes:
  - allowed_domains:
    - pomerium.com
    - gmail.com
    from: https://httpbin.localhost.pomerium.io
    pass_identity_headers: true
    to: https://httpbin.org
  - allow_websockets: true
    allowed_domains:
    - pomerium.com
    - gmail.com
    from: https://hello.localhost.pomerium.io
    kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_skip_verify: true
    to: http://nginx-hello
  - allow_websockets: true
    allowed_domains:
    - pomerium.com
    - gmail.com
    from: https://kubernetes.localhost.pomerium.io
    kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_skip_verify: true
```

Authenticate Ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.pomerium.io/allow_public_unauthenticated_access: "true"
    ingress.pomerium.io/preserve_host_header: "true"
    ingress.pomerium.io/secure_upstream: "true"
    ingress.pomerium.io/tls_server_name: authenticate.localhost.pomerium.io
    meta.helm.sh/release-name: pomerium
    meta.helm.sh/release-namespace: pomerium-test
  labels:
    app.kubernetes.io/instance: pomerium
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pomerium
    helm.sh/chart: pomerium-26.0.1
  name: pomerium-authenticate
  namespace: pomerium-test
spec:
  ingressClassName: pomerium
  rules:
  - host: authenticate.localhost.pomerium.io
    http:
      paths:
      - backend:
          service:
            name: pomerium-authenticate
            port:
              name: https
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: localhost
```

## What did you see in the logs?

```logs
pomerium-authenticate-7cdb559b48-hm4gk pomerium {"level":"info","service":"envoy","upstream-cluster":"pomerium-control-plane-http","method":"GET","authority":"authenticate.localhost.pomerium.io","path":"/.pomerium/callback/","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36","referer":"https://authenticate.localhost.pomerium.io/.pomerium/webauthn","forwarded-for":"192.168.65.3,10.1.0.178","request-id":"5e2c9ba0-a81a-44ce-b547-3b03080b4c91","duration":0.582042,"size":19,"response-code":404,"response-code-details":"via_upstream","time":"2022-01-11T15:18:17Z","message":"http-request"}
```

## Additional context

From previous testing, I think this only happens in distributed service mode.

Also the device registration is actually _processed_ in that it shows up in the user info page afterwards.  So I think is just cosmetic.
