### ISSUE TITLE
Docs: verify default port has switched from 80 to 8000

### ISSUE THREAD

**Issue by alexrudd2** [pomerium/pomerium#2930]
@calebdoxsey in https://github.com/pomerium/pomerium/pull/2895
> The default port for the verify service was changed from `80` to `8000`

The docs have not been updated, so following the default config or quickstart guides will not work.  Example: [here](https://github.com/pomerium/pomerium/blob/4583ecc730e900687575189525fdf736a5466752/examples/config/config.docker.yaml#L30)

**Comment by alexfornuto** [comment]
@alexrudd2 thanks for bringing this up!

**Comment by alexrudd2** [comment]
I believe the [quickstart page](https://www.pomerium.com/docs/install/quickstart) is still using 80.

```
  ## https://verify.localhost.pomerium.io --> Pomerium --> http://verify
  verify:
    image: pomerium/verify:latest
    expose:
      - 80
```
