### ISSUE TITLE
regex key does not accept ^ char

### ISSUE THREAD

**Issue by alexfornuto** [pomerium/pomerium#2952]
## What happened?

When creating routes in core with the regex key or in Enterprise with the regex matcher, values that start with `^` do not work.

## What did you expect to happen?

I expected the key to accept `^`, needed to ensure the pattern doesn't match when the path has other content before the match.

## How'd it happen?

Example routes:

```
  - from: https://route.example.com
    to: https://local-address
    regex: ^\/foo\/bar\/[0-9a-f]\/{0,1}$
    policy:
      - deny:
          or: 
            - email:
                is: afornuto@pomerium.com
  - from: /route.example.com
    to: https://local-address
    policy:
      - allow:
          or:
            - email:
                is: afornuto@pomerium.com
```

In the example above, going to a matching path is allowed for `afornuto@pomerium.com`. When `^` is removed the matching paths are denied.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`):
  ```
  $ docker exec -it pomerium /bin/pomerium --version
  pomerium: 0.16.0-1640214477+45a348de
  envoy: 1.19.1+c5ecc1e167273edac76f6c07f980ed5a728f4b7e077679d74cfbc59c087933e5
  ```

- Server Operating System/Architecture/Cloud: Docker

## What's your config.yaml?

See above

## What did you see in the logs?

```logs
# Without ^
2022-01-21T02:06:14.813271889Z {"level":"info","service":"authorize","request-id":"42e07f0b-e543-446b-bc89-7e5b15ace549","check-request-id":"cb49e914-765e-4474-be87-5810e34e6c68","method":"GET","path":"/foo/bar/123adb","host":"route.example.com","query":"","session-id":"350f9cfc-ba56-4ea4-8626-65d3127a325e","allow":false,"allow-why-false":["non-pomerium-route"],"deny":true,"deny-why-true":["email-ok"],"user":"108445263666202956835","email":"afornuto@pomerium.com","databroker_server_version":2697703461692766345,"databroker_record_version":13848,"time":"2022-01-21T02:06:14Z","message":"authorize check"}

# With ^
2022-01-21T02:07:54.392366461Z {"level":"info","service":"authorize","request-id":"dd45ebec-eb53-4100-82ec-9a43e7158f4b","check-request-id":"c9b80a14-5b56-41f6-926b-a4099d6caef6","method":"GET","path":"/foo/bar/123adb","host":"route.example.com","query":"","session-id":"350f9cfc-ba56-4ea4-8626-65d3127a325e","allow":true,"allow-why-true":["email-ok"],"deny":false,"deny-why-false":["valid-client-certificate-or-none-required"],"user":"108445263666202956835","email":"afornuto@pomerium.com","databroker_server_version":2697703461692766345,"databroker_record_version":14061,"time":"2022-01-21T02:07:54Z","message":"authorize check"}

```

**Comment by calebdoxsey** [comment]
To be clear

> needed to ensure the pattern doesn't match when the path has other content before the match.

The `^` and `$` should not be needed since the HTTP path matcher in Envoy is an `RE2::FullMatch` which doesn't allow matching of subsequences:

> `RE2::FullMatch` requires the regexp to match the entire input text

And the envoy docs also mention this:

> `safe_regex`: If specified, the route is a regular expression rule meaning that the regex must match the :path header once the query string is removed. The entire path (without the query string) must match the regex. The rule will not match if only a subsequence of the :path header matches the regex.

I spent some time reading the source code but don't have an explanation for why `^` isn't working. I believe it should be ok, as it just switches the mode in the regular expression engine, which will already have been set to matching only the beginning of the text, so should basically be a no-op. But it clearly breaks matching paths somehow.

Given that we don't have an explanation for why `^` doesn't work, and it's technically not needed, I suggest we just strip it from the beginning of the string if we see it.

**Comment by calebdoxsey** [comment]
Apparently the documented behavior described above is not the behavior we're actually seeing. I wonder if this is something that changed between versions. Envoy's latest is v1.21, but the issue was happening in v1.19. We need to investigate further by coming up with a pure envoy config to remove any Pomerium code from the equation. If the issue is still happening in v1.21 I will submit an upstream bug.

**Comment by calebdoxsey** [comment]
Using this config:

```yaml
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            safe_regex:
                              google_re2: {}
                              regex: "/match"
                          direct_response:
                            status: 200
                            body:
                              inline_string: "Match"
                        - match:
                            prefix: "/"
                          direct_response:
                            status: 200
                            body:
                              inline_string: "No Match"
                http_filters:
                  - name: envoy.filters.http.router
```

I see the same behavior in envoy 1.19, 1.20 and 1.21. `^` and `$` are unnecessary as it always does a full match. (eg `/before/match` and `/match/after` both won't match). And adding them also works as expected. `/match` still matches.

(run with `docker run -it -p 8080:8080 -p 9901:9901 -v "$(pwd)/envoy.yaml:/etc/envoy/envoy.yaml" envoyproxy/envoy:v1.19-latest --log-level debug -c /etc/envoy/envoy.yaml`)

This is not an envoy bug.
