### ISSUE TITLE
Databroker listener not selecting correct certificate with `address: :443`

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium#2972]
## What happened?

When running in distributed mode, the databroker listener is falling back to a certificate with a SAN subject of `*` even when a certificate that covers the databroker URL is present.

The issue appears to have started after upgrading to https://github.com/pomerium/pomerium/commit/95d6d97143c907ef1da82475dbcdd2b986b92ae4.

## What did you expect to happen?

Correct certificate to be selected.

## How'd it happen?

1. Provision `cert.pem` and `key.pem` for `*.localhost.pomerium.io`
2. Start Pomerium in databroker service mode
3. Receive TLS certificate errors

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`):` ace5bbb89a0414ed9c0f7dd8101bc27a39737a8d`
- Server Operating System/Architecture/Cloud: GKE 1.22

## What's your config.yaml?

It looks like `address: :443` is the important piece.  `address: 0.0.0.0:443` works correctly.

```
address: :443
services: databroker
databroker_service_url: https://databroker.localhost.pomerium.io
authenticate_service_url: https://authenticate.localhost.pomerium.io
certificates:
  - cert: cert.pem
    key: key.pem

shared_secret: XXX
cookie_secret: XXX

idp_client_id: YYYY
idp_client_secret: YYYY
idp_provider: okta
idp_provider_url: YYYY
idp_service_account: YYYY
```

## What did you see in the logs?

When databroker attempts to communicate with itself or authorize attempts to communicate with it:

```
{"level":"error","error":"rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED","time":"2022-01-25T22:54:01Z","message":"sync"}
```

## Additional context

This may be impacting additional listeners but this was the most obvious one.

This was first observed with helm as it defaults to a listener configuration as such:

```yaml
dns_lookup_family: V4_ONLY
address: :443
grpc_address: :443
```
