### ISSUE TITLE
Support ingress.kubernetes.io/rewrite-target

### ISSUE THREAD

**Issue by abh** [pomerium/pomerium#2979]
I converted an old Ingress object to use Pomerium and it appears `ingress.kubernetes.io/rewrite-target` isn't supported?

I had a configuration of `ingress.kubernetes.io/rewrite-target: "/"` to make the prefixes configured in the ingress object be stripped, for example

```
      paths:
      - backend:
          service:
            name: someapp
            port:
              number: 80
        path: /someapp
        pathType: ImplementationSpecific
```

will have requests for `pomerium.example.com/someapp/foo` be sent to `someapp.ns.svc.cluster.local/foo` (no path).

I thought first that I could use `host_path_regex_rewrite_pattern` for this, but that's all about rewriting the host header (only).
