### ISSUE TITLE
Unable to connect to target host when the Pomerium TCP client is used and mTLS is enabled

### ISSUE THREAD

**Issue by cfanbo** [pomerium/pomerium#2983]
## What happened?
Unable to connect to target host when the Pomerium TCP client is used and mTLS is enabled

pomerium TCP CLIENT for windows:
```
Destination Url: sshd.example.com:2222
Disable TLS Verification: Disable
Local Address: :9988
Alternate Pomerium Url: 
CA File Path: d:\\client.crt
CA File Text: 
```
if both of SERVER and Pomerium TCP client  disable mtls , no problem！

## What's your environment like?
Pomerium: v0.15.7
TCP client: v0.0.1
OS: ubuntu 20.0.4 Linux x86

## What's your config.yaml?
```
client_ca_file: /home/sxf/workspace/cert/ca.crt

cookie_secret: XXXX
idp_client_id: XXXX
idp_client_secret: XXXX
idp_provider: "auth0"
idp_provider_url: XXXX

routes:
  - from: tcp+https://sshd.example.com:2222
    pass_identity_headers: true
    to: tcp://192.168.3.140:22
    allow_public_unauthenticated_access: true
```

## What did you see in the logs?

```logs
{"level":"info","service":"authorize","request-id":"1cb9cf2d-6de2-4175-8a9f-08bd90df682c","check-request-id":"a578fa3d-8ef3-46f3-9d0b-69009292250b","method":"CONNECT","path":"","host":"sshd.example.com:2222","query":"","session-id":"dc256fe6-1d57-4c18-9610-e47bec0063bc","allow":true,"deny":{"Status":495,"Message":"invalid client certificate"},"user":"auth0|60cc461fd02f6500695cdbcf","email":"sun@test.com","databroker_server_version":6683481086097633070,"databroker_record_version":11,"time":"2022-01-30T09:29:04+08:00","message":"authorize check"}
```
