### ISSUE TITLE
Kubernetes dashboard shell exec error when behind the pomerium proxy

### ISSUE THREAD

**Issue by thuandt** [pomerium/pomerium#299]
If you are trying to use pomerium with [kubernetes dashboard](https://github.com/kubernetes/dashboard/), you should create dedicated ingress for your k8s dashboard backend and adjust service `kubernetes-dashboard` follow [this link](https://stackoverflow.com/questions/48993286/is-it-possible-to-route-traffic-to-a-specific-pod?rq=1)

![image](https://user-images.githubusercontent.com/847996/64805863-37e78b00-d5bc-11e9-82bc-66330484e230.png)

Here is example of ingress with nginx ingress controller
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "true"
    nginx.ingress.kubernetes.io/session-cookie-expires: "3600"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "3600"
    nginx.ingress.kubernetes.io/session-cookie-name: POMERIUM-BACKEND
  labels:
    app.kubernetes.io/instance: pomerium-devops
    app.kubernetes.io/name: pomerium
  name: kubernetes-dashboard
  namespace: monitor
spec:
  rules:
  - host: kube-dashboard.devops.xyz.com
    http:
      paths:
      - backend:
          serviceName: pomerium-devops-proxy
          servicePort: https
  - host: k8s-dashboard.devops.xyz.com
    http:
      paths:
      - backend:
          serviceName: pomerium-devops-proxy
          servicePort: https
  tls:
  - hosts:
    - '*.devops.xyz.com'
    secretName: devops-xyz-com-tls
```

For traefik, we can use this annotations: [ref](https://docs.traefik.io/configuration/backends/kubernetes/) 

```
traefik.ingress.kubernetes.io/affinity: "true"
traefik.ingress.kubernetes.io/session-cookie-name: POMERIUM-BACKEND
```
