### ISSUE TITLE
grpc: set client transport security from URL

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium#3037]
**Is your feature request related to a problem? Please describe.**

We currently use `grpc_insecure` to configure both our grpc listener and grpc client configuration.  This lack of granularity prevents configuration of some corner case architectures like:

1. secure listener but insecure client to one or more grpc services
2. insecure listener but secure client to one or more grpc services
3. insecure client to `authorize` service but secure client to `databroker`

**Describe the solution you'd like**

Use the scheme from the URL to determine if a grpc client should use transport security.  Originally suggested [here](https://github.com/pomerium/pomerium/issues/2386#issuecomment-885782843)

Example:

```yaml
authorize_service_url: http://localhost:5443
databroker_service_url: https://notlocalhost:5443
```

**Describe alternatives you've considered**

n/a

**Explain any additional use-cases**

n/A

**Additional context**

Implements fix proposed in https://github.com/pomerium/pomerium/issues/2386

This will be a potentially breaking change for users who use URLs with schemes implying different security posture than their `grpc_insecure` flag.  We can address that in upgrade documentation.

**Comment by calebdoxsey** [comment]
This seems to have changed significantly from when the original issue was submitted. `grpc_insecure` is now only used for the listener, though I'm not seeing it work properly locally. I will continue to investigate to find out where its going wrong, but I think `http` vs `https` is already implemented.

**Comment by calebdoxsey** [comment]
The issue I was running into locally is caused by an infinite ext_authz check on the authorize service when the proxy is fronting the authorize service. This appears not to be a supported use-case as we only have code to handle fronting of the authenticate service:

```go
func isProxyFrontingAuthenticate(options *config.Options, domain string) (bool, error) {
	authenticateURL, err := options.GetAuthenticateURL()
	if err != nil {
		return false, err
	}

	if !config.IsAuthenticate(options.Services) && hostMatchesDomain(authenticateURL, domain) {
		return true, nil
	}

	return false, nil
}
```

I will try to create a test case using two entirely separate pomerium clusters as described in the original issue. (though the original issue is also using istio and its doubful I will be able to reproduce such a complex setup based merely on a passing description)

**Comment by travisgroth** [comment]
> This seems to have changed significantly from when the original issue was submitted. `grpc_insecure` is now only used for the listener, though I'm not seeing it work properly locally. I will continue to investigate to find out where its going wrong, but I think `http` vs `https` is already implemented.

Interesting.  Thanks @calebdoxsey.

> I will try to create a test case using two entirely separate pomerium clusters as described in the original issue. (though the original issue is also using istio and its doubful I will be able to reproduce such a complex setup based merely on a passing description)

Istio shouldn't be needed, fortunately.  I believe it just happens to encourage patterns that lead to this (former?) issue.

**Comment by calebdoxsey** [comment]
I spent all day on this but I can't figure out how to configure it. The complexity of the requirements are beyond my ability to understand. Pomerium doesn't support operation without using TLS and the routing in envoy doesn't work properly if you try to set it up that way. There are apparently additional services sitting in front of Pomerium, but the configuration of those services isn't documented, so I was just guessing at what they were supposed to be. I guess you need to use forward auth traefik or nginx or something.

Perhaps someone else knows what changes to make, but until the requirements are better specified I don't know how to implement this. Strictly speaking we don't consult `GRPC_INSECURE` for cluster setup, so as far as I can tell there's nothing to do.

**Comment by travisgroth** [comment]
As @calebdoxsey indicated, it looks like this is already implemented.  When we reworked our inter-service communication to use envoy, the URL parsing behavior was likely updated.  Here's a very minimal test setup to show that a service (authorize) can be set up to _listen_ with an insecure socket but communicate to a databroker using secure transport.  

authorize:
```yaml
envoy_admin_address: 127.0.0.1:9902
grpc_address: :5443
services: authorize
databroker_service_url: https://databroker.localhost.pomerium.io:5444
authenticate_service_url: https://authenticate.localhost.pomerium.io
grpc_insecure: true
shared_secret: ww/GS72XV7Mp+zpzTSffqQN7dtX3XIaxoGvvjXMJiX4=
cookie_secret: uPGHo1ujND/k3B9V6yr52Gweq3RRYfFho98jxDG5Br8=
signing_key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVBkYjN0TXhNVExLeEF2bFplT0FBQktmbzFjRG5SMGlOQUppVU8wRDFmS2hvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFQlRrazZoU3hGekVrVDUrWXc3TGEyUS9jV2cremJwQlpsUDdMcEdPbStXWkFFelFKSDVBTQplZlhyVzk1eVdYQ0FXSGFkZVg2TnNtM20wdVdIQWYvYXJRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
certificate_authority_file: rootCA.pem
```

databroker:
```yaml
grpc_address: :5444
services: databroker
databroker_service_url: https://databroker.localhost.pomerium.io:5444
grpc_insecure: false
certificate_authority_file: rootCA.pem
certificates:
  - cert: cert.pem
    key: key.pem
authenticate_service_url: https://authenticate.localhost.pomerium.io
shared_secret: ww/GS72XV7Mp+zpzTSffqQN7dtX3XIaxoGvvjXMJiX4=
cookie_secret: uPGHo1ujND/k3B9V6yr52Gweq3RRYfFho98jxDG5Br8=
signing_key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVBkYjN0TXhNVExLeEF2bFplT0FBQktmbzFjRG5SMGlOQUppVU8wRDFmS2hvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFQlRrazZoU3hGekVrVDUrWXc3TGEyUS9jV2cremJwQlpsUDdMcEdPbStXWkFFelFKSDVBTQplZlhyVzk1eVdYQ0FXSGFkZVg2TnNtM20wdVdIQWYvYXJRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=

# Okta
idp_client_id: XXXXXX
idp_client_secret: XXXXXX
idp_provider: okta
idp_provider_url: https://XXXXXX
idp_scopes: XXXXXX
idp_service_account: XXXXXX

```

If these are both run on the same system, authorize should successfully connect to databroker and the latter will log put messages for the configuration events.  Authorize's socket will not have TLS, however:

```bash
% openssl s_client -connect localhost:5443
CONNECTED(00000005)
8632559104:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:332:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 293 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```
