### ISSUE TITLE
authenticate: oauth csrf errors

### ISSUE THREAD

**Issue by gregfr** [pomerium/pomerium#306]
Greetings and thanks for this nice project :)

I've installed Pomerium binary v0.3.0+bc72d08 on Debian 9.11

At first it was working, but after a few minutes I get only "Internal server errors", such as:
- oauth callback : csrf failure: %!w(<nil>)

I tried to restart Pomerium and clear cookies.

What did I do wrong?

Thanks in advance

**Comment by desimone** [comment]
Hi @gregfr -- could tell me a little bit more about your deployment? 

Looks like the CSRF session may be failing to be set. 

- What are you doing when this occurs? 
- What does your deployment look like? k8s/helm/ etc?
- Are you running in "all-in-one" mode or independent services? 
- What browser? Are you seeing any errors in your browser console? Do you have any plugins that may block cookies? Could you try another browser?
- Could you provide you config file with any sensitive data redacted?
- Could you provide your logs with any sensitive data redacted?

Thanks!

**Comment by desimone** [comment]
> FWIW, I've noticed the CSRF error myself, and I feel like it's easy to reproduce when simultaneously authenticating in multiple tabs:
> 0) sign out of session
> 1) Tab1: open foo.example.com, get auth screen, do not complete sign in
> 2) Tab2: open bar.example.com, get auth screen, do not complete sign in
> 3) Complete sign in in Tab1, get CSRF failure
> 4) All attempts to sign in now will get the 500 / CSRF failure error (old or new)

https://pomerium-io.slack.com/archives/CK6SVMPU0/p1568647242021900

**Comment by desimone** [comment]
See also: https://github.com/pomerium/pomerium/issues/178#event-2638441172

**Comment by gregfr** [comment]
Thanks for you answer.

I've configured a very basic setup of Pomerium (binary download on plain Debian) ; it stopped working at some point when I was trying to use "start-stop-server" to turn it into a service, but the problem may not be connected to that. I reverted to using it on the cli:
`./pomerium-linux-amd64 -config config.yaml`
I'm using Chrome but I've tried with another browser (Firefox), same error.

The config is also very basic:

```
authenticate_service_url: https://auth.mydomain
authorize_service_url: https://auth.mydomain

idp_provider: google
idp_client_id: ...
idp_client_secret: ...

policy:
        - from: https://stuff.mydomain
          to: http://internal.server
          allowed_domains:
                  - mydomain

```
