### ISSUE TITLE
Infinitely opening browser when using Pomerium with Pomerium-CLI for Kubernetes auth

### ISSUE THREAD

**Issue by sherifkayad** [pomerium/pomerium#3181]
## What happened?
After upgrading to Pomerium `v0.17.0`, using the CLI to authenticate / authorize Kubernetes and running any `kubectl` command e.g. `kubectl get pods`, browser windows are opening indefinitely after the login!

Until Pomerium `v0.16.4` this issue was never present.

## What did you expect to happen?
Login to Kubernetes should be working as expected!

## How'd it happen?

See above!

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): `0.17.0`
- Server Operating System/Architecture/Cloud: Installed Pomerium with Helm using the official chart and running on AWS EKS

## What's your config.yaml?

```config.yaml
autocert: false
dns_lookup_family: V4_ONLY
address: :80
grpc_address: :80
authenticate_service_url: https://pomerium.mydomain.com
authorize_service_url: http://pomerium-authorize.pomerium.svc.cluster.local
databroker_service_url: http://pomerium-databroker.pomerium.svc.cluster.local
idp_provider: oidc
idp_scopes: [openid profile email groups offline_access]
idp_provider_url: https://myidp.domain.com
insecure_server: true
grpc_insecure: true
forward_auth_url: https://forwardauth.mydomain.com
idp_client_id: REDACTED
idp_client_secret: REDACTED
idp_service_account: pomerium-authenticate
databroker_storage_tls_skip_verify: true    
routes:
  - allow_spdy: true
    allow_websockets: true
    allowed_idp_claims:
      groups:
      - Group A
      - Group B
    from: https://dashboard.mydomain.com
    kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    to: http://kubernetes-dashboard.kube-system.svc:443
  - allow_spdy: true
    allow_websockets: true
    allowed_idp_claims:
      groups:
      - Group A
      - Group B
    cors_allow_preflight: true
    from: https://kubernetes.mydomain.com
    kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_skip_verify: true
    to: https://kubernetes.default.svc
  - from: https://pomerium.mydomain.com
    to: http://pomerium-authenticate.pomerium.svc.cluster.local
    allow_public_unauthenticated_access: true
```

## What did you see in the logs?

Authenticate:
```logs
"error":"rpc error: code = Unknown desc = unknown directory provider oidc","time":"2022-03-23T10:58:12Z","message":"directory: failed to refresh user data"
```
Authorize, Data Broker and Proxy nothing.

## Additional context

My Kubeconfig file looks like:
```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://kubernetes.mydomain.com
    insecure-skip-tls-verify: true
  name: my-cluster-via-pomerium
contexts:
- context:
    cluster: my-cluster-via-pomerium
    user: my-cluster-via-pomerium
  name: my-cluster-via-pomerium
current-context: my-cluster-via-pomerium
kind: Config
preferences: {}
users:
- name: my-cluster-via-pomerium
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - k8s
      - exec-credential
      - --disable-tls-verification
      - https://kubernetes.mydomain.com
      command: pomerium-cli
      env: null
      provideClusterInfo: false
```

**Comment by sherifkayad** [comment]
@wasaga any idea why that might be happening? am I missing something in the configs?

**Comment by sherifkayad** [comment]
@travisgroth my values.yml is as follows:
```yaml
# For detailed explanation of each of the configuration settings see
# https://www.pomerium.io/reference/

# settings that are shared by all services
# settings that are shared by all services
config:
  # routes under this wildcard domain are handled by pomerium
  rootDomain: "mydomain.com"
  sharedSecret: "REDACTED"
  cookieSecret: "REDACTED"
  generateTLS: true
  extraOpts: {}
  insecure: true
  insecureProxy: false
  administrators: ""
  routes:
    - from: https://dashboard.mydomain.com
      to: http://kubernetes-dashboard.kube-system.svc:443
      allow_spdy: true
      allow_websockets: true
      allowed_idp_claims:
        groups:
          - Group A
          - Group B
      kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    - from: https://kubernetes.mydomain.com
      to: https://kubernetes.default.svc
      tls_skip_verify: true
      allow_spdy: true
      allow_websockets: true
      cors_allow_preflight: true
      allowed_idp_claims:
        groups:
          - Group A
          - Group B
      kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
authenticate:
  name: "pomerium"
  proxied: true
  # see https://www.pomerium.io/docs/identity-providers.html
  idp:
    provider: oidc
    clientID: "Hyc6cwZudoCV"
    clientSecret: "WbXngpSSDClOjop3e7MIAPKp"
    url: "https://myidp.domain.com"
    scopes:
      - openid
      - profile
      - email
      - groups
      - offline_access
    serviceAccount: pomerium-authenticate
  replicaCount: 2
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
  pdb:
    enabled: true
    minAvailable: 1
  service:
    annotations: {}
    nodePort: ""
    type: ClusterIP
  deployment:
    annotations: {}
    extraEnv: {}
    podAnnotations: {}
  serviceAccount:
    annotations: {}
    nameOverride: ""
authorize:
  replicaCount: 2
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
  pdb:
    enabled: true
    minAvailable: 1
  service:
    annotations: {}
    type: ClusterIP
    clusterIP: None
  deployment:
    annotations: {}
    extraEnv: {}
    podAnnotations: {}
  serviceAccount:
    annotations: {}
    nameOverride: ""
databroker:
  replicaCount: 2
  pdb:
    enabled: true
    minAvailable: 1
  service:
    annotations: {}
    type: ClusterIP
    clusterIP: None
  deployment:
    annotations: {}
    extraEnv: {}
    podAnnotations: {}
  serviceAccount:
    annotations: {}
    nameOverride: ""
  storage:
    type: "redis"
    connectionString: "REDACTED"
    tlsSkipVerify: true
    clientTLS:
      existingSecretName: ""
      existingCASecretKey: ""
      cert: ""
      key: ""
      ca: ""
proxy:
  replicaCount: 2
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
  pdb:
    enabled: true
    minAvailable: 1
  authenticateServiceUrl: ""
  authorizeInternalUrl: ""
  service:
    annotations: {}
    nodePort: ""
    type: ClusterIP
  deployment:
    annotations: {}
    extraEnv: {}
    podAnnotations: {}
  serviceAccount:
    annotations: {}
    nameOverride: ""
  redirectServer: true
apiProxy:
  enabled: true
  ingress: true
  name: "kubernetes"
ingressController:
  enabled: true
  ingressClassResource:
    enabled: false
    default: false
    name: pomerium
    controllerName: pomerium.io/ingress-controller
    parameters: {}
    defaultCertSecret: ""
  image:
    repository: "pomerium/ingress-controller"
    tag: "v0.17.0"
  deployment:
    annotations: {}
    extraEnv: {}
  serviceAccount:
    annotations: {}
    nameOverride: ""
  config:
    namespaces: []
    ingressClass: k8s.io/ingress-nginx
    updateStatus: true
    operatorMode: true
  service:
    annotations: {}
    type: ClusterIP
forwardAuth:
  name: ""
  enabled: true
  # Will not create an ingress. ForwardAuth is ony accessible as internal service.
  internal: false
service:
  # externalPort defaults to 80 or 443 depending on config.insecure
  externalPort: ""
  annotations: {}
  # ===  GKE load balancer tweaks; default on until I can figure out
  # how the hell to escape this string from the helm CLI
  # cloud.google.com/app-protocols: '{"https":"HTTPS"}'
  labels: {}
  grpcTrafficPort:
    nameOverride: ""
  httpTrafficPort:
    nameOverride: ""
ingress:
  secretName: ""
  secret:
    name: "pomerium-tls"
    cert: ""
    key: ""
  tls: {}
  enabled: true
  hosts: []
  # Sets Ingress/ingressClassName. This way ingress resources are able to bound specific ingress-controllers. Kubernetes version >=1.18 required.
  # Ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
  # Ingress pathType (e.g. ImplementationSpecific, Prefix, .. etc.) might also be required by some Ingress Controllers
  pathType: ImplementationSpecific
resources: {}
# limits:
#   cpu: 1
#   memory: 600Mi
# requests:
#   cpu: 100m
#   memory: 300Mi

priorityClassName: ""
# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []
# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}
podAnnotations: {}
podLabels: {}
replicaCount: 1
# For any other settings that are optional. for a complete listing see:
# https://www.pomerium.io/docs/config-reference.html
extraEnv:
  CERTIFICATE_AUTHORITY_FILE: "/ca-cert/MYCERT.crt"
  AUTOCERT: "false"
  LOG_LEVEL: "error"
extraEnvFrom: []
extraArgs: {}
extraVolumes:
  - name: ca-cert
    secret:
      secretName: ca-cert
extraVolumeMounts:
  - name: ca-cert
    mountPath: /ca-cert/
extraTLSSecrets: []
annotations: {}
imagePullSecrets: ""
image:
  repository: "pomerium/pomerium"
  tag: "v0.17.0"
  pullPolicy: "IfNotPresent"
metrics:
  enabled: true
  port: 9090
tracing:
  enabled: false
  provider: ""
  debug: false
  jaeger:
    collector_endpoint: ""
    agent_endpoint: ""
serviceMonitor:
  enabled: true
  namespace: ""
  labels:
    app: pomerium
rbac:
  create: true
redis:
  enabled: false
```

**Comment by travisgroth** [comment]
I'm able to reproduce this with a pretty minimal config.  It looks like we're redoing the browser auth flow for every request, but they do actually _succeed_.  I suspect something is up with either the storage or retrieval of the session credential cache on the cli side.

values:

```yaml
authenticate:
  idp:
    provider: XXXXXX
    url: XXXXXX
    clientID: XXXXXX
    clientSecret: XXXXXX
    serviceAccount: XXXXXX
config:
  rootDomain: localhost.pomerium.io
  sharedSecret: XXXXXX
  cookieSecret: XXXXXX
ingress:
  enabled: false
ingressController:
  enabled: true
```
