### ISSUE TITLE
docs: kubernetes/helm guide updates

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/pomerium#3213]
## What happened?
Recent changes to the helm chart mean that the https://www.pomerium.com/docs/k8s/helm.html guide needs some updates.

1. The helm values file needs:
    ```yaml
    authenticate:
      ingress:
        tls:
          secretName: pomerium-tls
    ```

2. The helm values file needs:
    ```
    ingress:
      enabled: false 
    ```
