### ISSUE TITLE
Why subpath didn't it work

### ISSUE THREAD

**Issue by cfanbo** [pomerium/pomerium#3229]
```
  - from: https://test.example.com
    pass_identity_headers: true
    to: http://127.0.0.1:8080
    allowed_users:
    - tom
    - jack
    policy:
    - allow:
        and:
          - http_path:
              is: /test
```
is this case, tom can still access other url paths?
No usage documentation for subpath was found（`http_path` and `http_method`）
