### ISSUE TITLE
invalid memory address

### ISSUE THREAD

**Issue by heywoodlh** [pomerium/pomerium#3349]
## What happened?
When I run the container on my Raspberry Pi it crashes with the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc59f04]

goroutine 113 [running]:
github.com/pomerium/pomerium/internal/directory/github.(*Provider).listOrganizationTeamsWithMemberIDs(0x4000486230, {0x1a46770, 0x4004454c60}, {0x4000cb5a30, 0xd})
        /go/src/github.com/pomerium/pomerium/internal/directory/github/graphql.go:136 +0x254
github.com/pomerium/pomerium/internal/directory/github.(*Provider).UserGroups(0x4000486230, {0x1a46770, 0x4004454c60})
        /go/src/github.com/pomerium/pomerium/internal/directory/github/github.go:142 +0x630
github.com/pomerium/pomerium/internal/identity/manager.(*Manager).refreshDirectoryUserGroups(0x4000734180, {0x1a46700, 0x4000758800})
        /go/src/github.com/pomerium/pomerium/internal/identity/manager/manager.go:219 +0x170
github.com/pomerium/pomerium/internal/identity/manager.(*Manager).refreshLoop(0x4000734180, {0x1a46700, 0x4000758800}, 0x4000734de0, 0x400077c2a0)
        /go/src/github.com/pomerium/pomerium/internal/identity/manager/manager.go:173 +0x5a0
github.com/pomerium/pomerium/internal/identity/manager.(*Manager).RunLeased.func2()
        /go/src/github.com/pomerium/pomerium/internal/identity/manager/manager.go:115 +0x48
golang.org/x/sync/errgroup.(*Group).Go.func1(0x400076d350, 0x400076d380)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x60
```

## What did you expect to happen?

Pomerium container to run without crashing (or at least provide more informative error)

## How'd it happen?

This is my config: 

```
# See detailed configuration settings : https://www.pomerium.com/docs/reference/


# this is the domain the identity provider will callback after a user authenticates
authenticate_service_url: xxx

####################################################################################
# Certificate settings:  https://www.pomerium.com/docs/reference/certificates.html #
# The example below assumes a certificate and key file will be mounted to a volume #
# available to the  Docker image.                                                  #
####################################################################################
certificate_file: /letsencrypt/fullchain.pem
certificate_key_file: /letsencrypt/privkey.pem

##################################################################################
# Identity provider settings : https://www.pomerium.com/docs/identity-providers/ #
# The keys required in this section vary depending on your IdP. See the          #
# appropriate docs for your IdP to configure Pomerium accordingly.               #
##################################################################################
idp_provider: "xxx"
idp_client_id: "xxx"
idp_client_secret: "xxx"
idp_service_account: "xxx"

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
cookie_secret: xxx

routes:
  - from: xxx
    to: xxx
    policy:
      - allow:
          or:
            - email:
                is: user@example.com
    pass_identity_headers: true

```

This is how I'm running pomerium:

```
docker run -d --name=pomerium \
        -v /opt/pomerium/letsencrypt/etc/live/<omitted>/fullchain.pem:/letsencrypt/fullchain.pem:ro \
        -v /opt/pomerium/letsencrypt/etc/live/<omitted>/privkey.pem:/letsencrypt/privkey.pem:ro \
        -v /opt/pomerium/config.yaml:/pomerium/config.yaml:ro \
        --restart=unless-stopped \
        -p 443:443 \
        pomerium/pomerium:git-02e30093
```

## What's your environment like?

- Raspberry Pi
- Ubuntu 20.04 64 bit ARM flavor

## What's your config.yaml?
See above 

Any help would be appreciated! :D
