### ISSUE TITLE
Allow setting request headers for back-end requests

### ISSUE THREAD

**Issue by mleklund** [pomerium/pomerium#338]
**Is your feature request related to a problem? Please describe.**
I would like to allow the proxy to pass headers to the backend service, and be able to set these headers based on the policy configuration.

**Describe the solution you'd like**

```
policy:
  - from: https://httpbin.mydomain.com
    to: http://backend.namespace.svc.cluster.local
    headers:
       foo: bar
       Authorization: Basic SOMEBASE64HERE
    allowed_groups:
      - admins
```

I would like to be able to set headers to send to backend services based on policy routes.

**Describe alternatives you've considered**

I attempted to pass authorization based on uri, but that does not seem to be supported ether:

```
policy:
  - from: https://httpbin.mydomain.com
    to: http://user@password:backend.namespace.svc.cluster.local
    allowed_groups:
      - admins
```

**Explain any additional use-cases**

Would be especially magical if we could set differing `Authorization:  Basic` headers based on the incoming user/group, but I do not see a clear path to do that based on the current policy definitions.
