### ISSUE TITLE
500 server error - sessions corrupted after network disconnect

### ISSUE THREAD

**Issue by alexrudd2** [pomerium/pomerium#3431]
## What happened?

A localized partial power/network outage occurred.  We believe all-in-one pomerium stayed running but it may have lost network connectivity to its Redis backend.  (It's also possible one or both of those containers rebooted.). Users which had an active session got a 500 error and could not do anything further.  Users without an active session could create one without problems.
![image](https://user-images.githubusercontent.com/52292902/174131305-dd2ce5f4-9b73-4a4b-9887-61b266757759.png)

I could only fix by rebooting Redis.

## What did you expect to happen?
Normal functionality, or at least the ability to logout and start a new session.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): `0.17.3-1651784655+f4bad550`
- Server Operating System/Architecture/Cloud: Docker Swarm on Linux, behind nginx.  redis `7.0.2` (upgraded 6.0 -> 6.2 -> 7.0.2 yesterday)

## What's your config.yaml?

```yaml
#address: ":8443"
# pomerium_debug: true # optional, default is false
#service: "all"
# log_level: info # optional, default is debug
authenticate_service_url: https://authenticate.<domain>.com
autocert: true
<secrets and such>
jwt_claims_headers:
- name
- email
- picture
- groups
- given_name
- family_name

# Use redis databroker backend
databroker_storage_type: redis
databroker_storage_connection_string: redis://base_pomerium-redis:6379

# Identity Provider Settings
## GOOGLE
idp_provider: "google"
idp_client_id: <foo>
idp_client_secret: <bar>

idp_service_account:  <baz>
<routes>
```

## What did you see in the logs?

<details><summary>logs</summary>
2022-06-16 10:00:16 | {   "level": "info",   "service": "envoy",   "upstream-cluster": "pomerium-control-plane-http",   "method": "GET",   "authority": "authenticate.<domain>.com",   "path": "/oauth2/callback",   "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36",   "referer": "https://accounts.google.com/",   "forwarded-for": "10.0.0.4",   "request-id": "6e461558-b734-4394-bdcb-b8332299e16b",   "duration": 198.359305,   "size": 605,   "response-code": 500,   "response-code-details": "via_upstream",   "time": "2022-06-16T10:00:16-05:00",   "message": "http-request" }
-- | --
  |   | 2022-06-16 10:00:10 | {   "level": "info",   "service": "envoy",   "upstream-cluster": "pomerium-control-plane-http",   "method": "GET",   "authority": "authenticate.<domain>.com",   "path": "/oauth2/callback",   "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36",   "referer": "https://accounts.google.com/",   "forwarded-for": "10.0.0.4",   "request-id": "f6ef9f96-6c2f-4ea4-95d6-69deea882553",   "duration": 47.21618,   "size": 653,   "response-code": 500,   "response-code-details": "via_upstream",   "time": "2022-06-16T10:00:10-05:00",   "message": "http-request" }
</details>

## Additional context

This happened to us once before, two weeks ago during our deploy.  We did not investigate further then, as blowing away all the containers and datafiles solved it.

**Comment by alexrudd2** [comment]
<details><summary> redis logs </summary>
2022-06-16 10:46:03 | 1:M 16 Jun 2022 15:46:03.371 * Ready to accept connections

  |   | 2022-06-16 10:46:03 | 1:M 16 Jun 2022 15:46:03.371 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
  |   | 2022-06-16 10:46:03 | 1:M 16 Jun 2022 15:46:03.370 * DB loaded from append only file: 0.564 seconds
  |   | 2022-06-16 10:46:03 | 1:M 16 Jun 2022 15:46:03.370 * DB loaded from incr file appendonly.aof.1.incr.aof: 0.078 seconds
  |   | 2022-06-16 10:46:03 | 1:M 16 Jun 2022 15:46:03.292 * DB loaded from base file appendonly.aof: 0.306 seconds
  |   | 2022-06-16 10:46:03 | 1:M 16 Jun 2022 15:46:03.065 * Reading the remaining AOF tail...
  |   | 2022-06-16 10:46:03 | 1:M 16 Jun 2022 15:46:03.065 * Done loading RDB, keys loaded: 12, keys expired: 0.
  |   | 2022-06-16 10:46:02 | 1:M 16 Jun 2022 15:46:02.986 * RDB has an AOF tail
  |   | 2022-06-16 10:46:02 | 1:M 16 Jun 2022 15:46:02.986 * RDB memory usage when created 17.95 Mb
  |   | 2022-06-16 10:46:02 | 1:M 16 Jun 2022 15:46:02.986 * RDB age 1067022 seconds
  |   | 2022-06-16 10:46:02 | 1:M 16 Jun 2022 15:46:02.986 * Loading RDB produced by version 6.2.7
  |   | 2022-06-16 10:46:02 | 1:M 16 Jun 2022 15:46:02.986 * Reading RDB preamble from AOF file...
  |   | 2022-06-16 10:46:02 | 1:M 16 Jun 2022 15:46:02.723 # Server initialized
  |   | 2022-06-16 10:46:02 | 1:M 16 Jun 2022 15:46:02.723 * Running mode=standalone, port=6379.
  |   | 2022-06-16 10:46:02 | 1:M 16 Jun 2022 15:46:02.722 * monotonic clock: POSIX clock_gettime
  |   | 2022-06-16 10:46:02 | 1:C 16 Jun 2022 15:46:02.722 # Configuration loaded
  |   | 2022-06-16 10:46:02 | 1:C 16 Jun 2022 15:46:02.722 # Redis version=7.0.2, bits=64, commit=00000000, modified=0, pid=1, just started
  |   | 2022-06-16 10:46:02 | 1:C 16 Jun 2022 15:46:02.722 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
  |   | 2022-06-16 10:46:02 | redis 15:46:02.71 INFO  ==> ** Starting Redis **
  |   | 2022-06-16 10:46:02 | redis 15:46:02.69 INFO  ==> ** Redis setup finished! **
  |   | 2022-06-16 10:46:02 | redis 15:46:02.66 INFO  ==> Setting Redis config file
  |   | 2022-06-16 10:46:02 | redis 15:46:02.65 INFO  ==> Initializing Redis
  |   | 2022-06-16 10:46:02 | redis 15:46:02.64 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
  |   | 2022-06-16 10:46:02 | redis 15:46:02.63 INFO  ==> ** Starting Redis setup **
  |   | 2022-06-16 10:46:02 | redis 15:46:02.63
  |   | 2022-06-16 10:46:02 | redis 15:46:02.62 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
  |   | 2022-06-16 10:46:02 | redis 15:46:02.62 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
  |   | 2022-06-16 10:46:02 | redis 15:46:02.62 Welcome to the Bitnami redis container
  |   | 2022-06-16 10:46:02 | redis 15:46:02.62
  |   | 2022-06-16 10:46:01 | 1:M 16 Jun 2022 15:46:01.173 # Redis is now ready to exit, bye bye...
  |   | 2022-06-16 10:46:01 | 1:M 16 Jun 2022 15:46:01.173 * Removing the pid file.
  |   | 2022-06-16 10:46:01 | 1:M 16 Jun 2022 15:46:01.173 * DB saved on disk
  |   | 2022-06-16 10:46:01 | 1:M 16 Jun 2022 15:46:01.128 * Saving the final RDB snapshot before exiting.
  |   | 2022-06-16 10:46:01 | 1:M 16 Jun 2022 15:46:01.126 * Calling fsync() on the AOF file.
  |   | 2022-06-16 10:46:01 | 1:M 16 Jun 2022 15:46:01.126 # User requested shutdown...
  |   | 2022-06-16 10:46:01 | 1:signal-handler (1655394361) Received SIGTERM scheduling shutdown...
  |   | 2022-06-16 09:53:53 | 1:M 16 Jun 2022 14:53:53.809 # Fail to fsync the AOF file: Transport endpoint is not connected
  |   | 2022-06-16 09:52:54 | 1:M 16 Jun 2022 14:52:54.024 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
  |   | 2022-06-16 09:49:26 | 1:M 16 Jun 2022 14:49:26.177 * Background saving terminated with success
  |   | 2022-06-16 09:49:26 | 112:C 16 Jun 2022 14:49:26.130 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
  |   | 2022-06-16 09:49:26 | 112:C 16 Jun 2022 14:49:26.129 * DB saved on disk
  |   | 2022-06-16 09:49:26 | 1:M 16 Jun 2022 14:49:26.076 * Background saving started by pid 112
  |   | 2022-06-16 09:49:26 | 1:M 16 Jun 2022 14:49:26.076 * 100 changes in 300 seconds. Saving...
  |   | 2022-06-16 09:47:35 | 1:M 16 Jun 2022 14:47:35.090 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
  |   | 2022-06-16 09:44:25 | 1:M 16 Jun 2022 14:44:25.694 * Background saving terminated with success
  |   | 2022-06-16 09:44:25 | 111:C 16 Jun 2022 14:44:25.643 * Fork CoW for RDB: current 1 MB, peak 1 MB, average 0 MB
  |   | 2022-06-16 09:44:25 | 111:C 16 Jun 2022 14:44:25.642 * DB saved on disk
  |   | 2022-06-16 09:44:25 | 1:M 16 Jun 2022 14:44:25.493 * Background saving started by pid 111
</details>

**Comment by desimone** [comment]
Thanks for the detailed report @alexrudd2 . Are you using redis in persistent mode?

**Comment by alexrudd2** [comment]
```yaml
<docker-stack.yml>
  pomerium-redis:
    image: bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - swarm
    volumes:
      - /media/glusterdata/pomerium-redis:/bitnami/redis/data
```

Yes, bitnami's [redis container](https://hub.docker.com/r/bitnami/redis/) uses AOF persistence by default, and I've put it on top of glusterFS on all nodes.  The idea is that we can move redis around freely between nodes, since the session data isn't very much and glusterFS is quite fast on a local network.  In theory this is fast enough where pomerium only notices a bit of latency on a redis move - although it's certainly possible my setup is causing this issue.

**Comment by EdgardGomez** [comment]
![Annotation 2022-07-28 130914](https://user-images.githubusercontent.com/93156387/181607521-6bbb1104-9980-46ba-847a-f2911fce270d.png)

**Comment by EdgardGomez** [comment]
![Annotation 2022-07-28 131018](https://user-images.githubusercontent.com/93156387/181607717-b10122c7-c1db-457a-a0e3-bb21b730fdbc.png)

**Comment by alexrudd2** [comment]
Some context here: somewhere around 12:30PM local time GlusterFS went down, which is used for storage by the databroker backend redis at `/media/glusterdata/pomerium-redis`. Redis therefore had its disk file handles yanked from under it, but its memory store would have been otherwise unaffected.
```
  pomerium-redis:
    image: bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - swarm
    volumes:
      - /media/glusterdata/pomerium-redis:/bitnami/redis/data
```

I brought back up GlusterFS after 1PM.  Some users (such as me) remained logged in fine.  Eddy received the above error.
