### ISSUE TITLE
Support secrets loaded from files in Docker Swarm or Kubernetes

### ISSUE THREAD

**Issue by alexrudd2** [pomerium/pomerium#3441]
**Is your feature request related to a problem? Please describe.**

On Docker there are only two options for storing e.g. [`idp_client_secret`](https://www.pomerium.com/docs/reference/identity-provider-client-secret): directly in a config file or in an environment variable (envvar).

Envvars are pomerium's [recommended solution](https://www.pomerium.com/docs/reference).   For Docker standalone, at least it's easy.  However, for Docker Swarm it's more complicated because the nodes used for creating a service and running it may not be the same.  This means the envvars must present on every possible Swarm node.  (Alternatively, store them directly in the Compose file... at which point why bother?).  In any case envvars are very easy to read and a slight security improvement at best.

It appears to be a pretty common containerized paradigm to use files of the name `<ENVVARNAME>_FILE` for secrets.  This works well with [Swarm secrets](https://docs.docker.com/engine/swarm/secrets/), which live encrypted and are accessed by containers at runtime as files.
Examples: 
- MongoDB [uses](https://medium.com/@leonfeng/set-up-a-secured-mongodb-container-e895807054bd) the envvar  `MONGO_INITDB_ROOT_PASSWORD_FILE`
- Postgres [uses](https://www.postgresql.org/docs/current/libpq-pgpass.html) can use the envvar `PGPASSFILE`

**Describe the solution you'd like**
Pomerium supports Docker Swarm secrets "natively" with either/both envvars or `config.yaml`
```yaml
<config.yaml>
# Identity Provider Settings
## GOOGLE
idp_provider: "google"
idp_client_id: "foobar.apps.googleusercontent.com"
idp_client_secret_file: "/run/secrets/IDP_SECRET_FILE"
```

**Describe alternatives you've considered**

My current solution is to write a custom Dockerfile ~~(untested)~~.  EDIT: It works.  This requires using the `-debug` images since pomerium's distroless image doesn't have a shell.  It also means building my own custom images rather than using the public one, which complicates updates.  Baking this into the official Docker image or pomerium binary would be an improvement for me.
```yaml
<my-stack.yaml>
  pomerium:
    image: localhost:5000/pomerium
    build:
      dockerfile: PomeriumDockerfile
    secrets:
      - GAUTH_CLIENT_SECRET
```
```
<PomeriumDockerfile>
FROM pomerium/pomerium:debug-v0.17.3
ADD entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "sh","/entrypoint.sh" ]
```
```bash
<entrypoint.sh>
#!/bin/bash
SWARM_SECRET=$(cat "/run/secrets/GAUTH_CLIENT_SECRET")
export "IDP_CLIENT_SECRET=$SWARM_SECRET"
/bin/pomerium -config /pomerium/config.yaml
```

**Explain any additional use-cases**
This would presumably be useful for secrets other than just `idp_client_secret`

**Additional context**

I don't know Kubernetes, but understand it has built-in secret management which pomerium uses.  Standalone Docker can't use swarm secrets. This is only for Docker Swarm (note it could be a swarm of 1 to use the Swarm Secrets).

**Comment by calebdoxsey** [comment]
@alexrudd2 The solution I typically use for this problem is to use a separate container which can build the configuration as a file on a shared volume which Pomerium can then access. We do this in docker-compose in our integration tests:

```yaml
services:
  fortio:
    depends_on:
      fortio-init:
        condition: service_completed_successfully
  fortio-init:
    command:
    - sh
    - -c
    - |
      echo "$$CERT" >/fortio_config/trusted.pem
      echo "$$KEY" >/fortio_config/trusted-key.pem
  
```

Unfortunately docker swarm apparently doesn't support `depends_on`. Docker swarm is not a technology I have ever used, so I don't know what the equivalent to kubernetes init containers would be. Personally I don't think we should add support to the product for loading data from files.

Not having a shell in the docker image was intentional.

**Comment by alexrudd2** [comment]
> Unfortunately docker swarm apparently doesn't support `depends_on`. 

Only replying to this part since I have to think through the rest of your reply.  Docker Swarm does [support](https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on) `depends_on`.  The only time it doesn't is when using `docker stack deploy`, in which case all the services are started anyway.

**Comment by calebdoxsey** [comment]
Kubernetes secrets can be loaded as environment variables which are compatible with Pomerium. We use this in the helm chart.

A similar problem exists for users of Hashicorp vault. They provide a program, [consul-template](https://github.com/hashicorp/consul-template), which does what I was suggesting above. It loads the secrets from vault, dumps them into a templated config file, and then you can start a legacy application which knows nothing about how to access the vault API. I think the Hashicorp solution is a good one, but perhaps my view is in the minority.

I am not familiar with Docker Swarm so can't speak to its security model. In Kubernetes the files in the temporary volume shared between containers would only be accessible by those containers, so there would not be a security concern. But I suppose if Docker Swarm can't provide guarantees like that, then it would not be a good solution.

Sorry I don't have a better solution. I don't relish maintaining and documenting 100 more config option variations, but I guess we could do that.

As for Pomerium Enterprise, we write config as protobuf and ship it to the databroker where it then gets loaded by every instance of Pomerium.

**Comment by alexrudd2** [comment]
> I am not familiar with Docker Swarm so can't speak to its security model.

Hmm, perhaps I should have led with this. :)
_Does pomerium "officially" support Docker Swarm, or not?_  

You publish docker config files, and the [Deploy guide](https://www.pomerium.com/docs/production/production-deployment) talks a lot about horizontal scaling with as "much physical and logical separation as possible."  Docker standalone can't do that; it has to be Swarm.  A fair answer would be to say "no, we only support k8s at scale".  In that case, I'd argue you should overhaul the documentation to make this clear!

> Kubernetes secrets can be loaded as environment variables which are compatible with Pomerium. We use this in the helm chart. [...]
> A similar problem exists for users of Hashicorp vault. They provide a program, [consul-template](https://github.com/hashicorp/consul-template), which does what I was suggesting above. It loads the secrets from vault, dumps them into a templated config file, and then you can start a legacy application which knows nothing about how to access the vault API. I think the Hashicorp solution is a good one, but perhaps my view is in the minority.

K8s and/or a secret store are definitely more robust, and I'm not complaining that bare Docker Swarm has fewer features.  In the medium term, I'd like to get a proper secret store.  Hell, maybe we'll go full k8s.  My hope is that the easier configuration of Swarm is the right size for our small deploy right now.  Swarm Secrets are a big improvement from secrets littered across our servers/repos, so I'm doing that first.

> In Kubernetes the files in the temporary volume shared between containers would only be accessible by those containers, so there would not be a security concern. But I suppose if Docker Swarm can't provide guarantees like that, then it would not be a good solution.

Apologies for a poor explanation of the underlying problem.  Volume mounts can indeed have per-container access control.  (I'm not sure how secure they are on the underlying physical disk.)  The problem is they only reside on one physical host, and so I'm using bind mounts to connect to a host filesystem, which is replicated across all of them.  This is not an insurmountable problem, it's just annoying.

> Sorry I don't have a better solution. I don't relish maintaining and documenting 100 more config option variations, but I guess we could do that.

I'm not sure what other people's use cases are, but I'm only asking for "sensitive" config options to get this treatment.  `idp_client_secret`, `shared_secret`, `cookie_secret`, and `signing_key` I think?.  Certificates are already loaded as files from configurable destinations, so they already work.

> As for Pomerium Enterprise, we write config as protobuf and ship it to the databroker where it then gets loaded by every instance of Pomerium.

Pomerium Enterprise is on my to-do list, since Bobby mentioned it may help with other things :)


Thank you for your assistance.  For the time being I'm going to see if I can switch my shell script wrapper to one with a compiled binary, so it won't require use of the `-debug` image.

**Comment by desimone** [comment]
This should be possible with #3453

**Comment by desimone** [comment]
Reopening because this still needs to be documented. \cc @alexfornuto

**Comment by alexrudd2** [comment]
> Pomerium loaded, but the authorizations started failing. Presumably I need to clear current user sessions.

Yup, I should have read the [Troubleshooting Guide](https://www.pomerium.com/docs/troubleshooting#redis-secret-mismatch).  o_0



I tried again using `idp_client_secret_file` instead, and it worked beautifully.

**Comment by alexfornuto** [comment]
@alexrudd2 thanks for all the useful feedback! If you don't mind, I'm going to use the content here as part of the docs updates for this feature.

**Comment by alexfornuto** [comment]
> (Alternatively, store them directly in the Compose file... at which point why bother?).

Just curious... Why not add these values as secrets and then use them to generate the env vars in the compose file? There's an example of this in the [Docker Swarm docs](https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose):

```yaml
version: "3.9"

services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_root_password
       - db_password

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_password


secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt

volumes:
    db_data:
```
