### ISSUE TITLE
Running into issue with cognito as identity provider

### ISSUE THREAD

**Issue by mohit2104** [pomerium/pomerium#3467]
I am using cognito identity provider to protect a simple nginx server. The authenticate phase works fine, i.e I am able to see the cognito login window and after login it redirects me to /.pomerium page showing all the details of the logged in user. However, when I navigate to nginx.example.com, it see the error 

### `**"upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111".**`

I checked the logs and I see a couple of issues:
`WRN failed to refresh directory users and groups error="unknown directory provider oidc" service=identity_manager`

`DBG syncer got record record_id=identity_manager_last_user_group_refresh_errors record_type=type.googleapis.com/pomerium.events.LastError record_version=10 syncer_id=authorize syncer_type=
`

When trying to directly connect to the nginx server on port 3000, it is working. 

I am pasting below my config.yaml and docker-compose.yml file. 

config.yaml
```
authenticate_service_url: https://authenticate.example.com
certificate_file: /pomerium/cert.pem
certificate_key_file: /pomerium/privkey.pem
idp_provider: "oidc"
idp_provider_url: "https://cognito-idp.<region>.amazonaws.com/<cognito_pool_id>"
idp_client_id: "<client_id>"
idp_client_secret: "<client_secret>"
idp_scopes: "openid,profile,email"
cookie_secret: V2JBZk0zWGtsL29UcFUvWjVDWWQ2UHExNXJ0b2VhcDI=
routes:
  - from: https://verify.example.com
    to: http://verify:8000
    policy:
      - allow:
          or:
            - email:
                is: test@example.com
    pass_identity_headers: true
  - from: https://nginx.example.com
    to: http://nginx:3000
    policy:
      - allow:
          or:
            - email:
                is: test@example.com
```

docker-compose.yml
```
version: "3"
services:
  pomerium:
    image: pomerium/pomerium:latest
    volumes:
      ## Mount your domain's certificates : https://www.pomerium.com/docs/reference/certificates
      - ./_wildcard.example.com.pem:/pomerium/cert.pem:ro
      - ./_wildcard.example.com-key.pem:/pomerium/privkey.pem:ro

      ## Mount your config file : https://www.pomerium.com/docs/reference/
      - ./config.yaml:/pomerium/config.yaml:ro
    ports:
      - 443:443
  verify:
    image: pomerium/verify:latest
    expose:
      - 8000
  nginx:
    image: nginx
    ports:
     - 3000:80
```
