### ISSUE TITLE
proxy: support path prefix stripping / url rewriting 

### ISSUE THREAD

**Issue by idaunis** [pomerium/pomerium#349]
**Is your feature request related to a problem? Please describe.**

Pomerium doesn't support a default path.

For example when using it as a IAP for Kibana. I can not handle direct calls https://logs.test-site.com. Ideally I want to authorize the users and then redirect them to https://logs.test-site.com/_plugin/kibana

**Describe the solution you'd like**

I would like to specify a base path or at minimum at default path for the destinations in the yaml policy so when the client doesn't specify a path, pomerium sends a 301 redirect to the default path. For example:

```
- from: https://logs.beyondperimeter.com
  to: http://localhost:9200
  default_path: /_plugin/kibana
  allowed_groups:
    - admins@pomerium.io
```

**Comment by desimone** [comment]
With the Envoy changes this should be pretty straight forward for paths and regex.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-redirectaction-prefix-rewrite

**Comment by devstein** [comment]
+1 on this. A common pattern we have previously used is to have the Frontend and the Backends be accessible through a single host, but use path rewriting to abstract it away behind the suffix `/api`.

For example,

```yaml
policies:
  # direct /api/users to the user review service
  - from: http://from.example.com
    prefix: /api/reviews
    to: http://reviews-service.example.com
  # direct /api/products to the product service
  - from: http://from.example.com
    prefix: /api/products
    to: http://products-service.example.com

 # Everything else is directed to the Frontend
  - from: http://from.example.com
    to: http://frontend.example.com
```
Where the backend services receive the request without the `/api/reviews` or `/api/products` prefix.

So `/api/products/categories/1` would be received by the product service as `/categories/1`
