### ISSUE TITLE
Infinite loop after switching from operator to ingress controller.

### ISSUE THREAD

**Issue by ftpd** [pomerium/pomerium#3721]
(Disclaimer: I know it's not a 'bug', but rather I don't understand something, but I decided to ask here, as it's kinda crucial to restore working Pomerium. Sorry for the mess).

I've updated my EKS cluster from 1.21 to 1.22. Unfortunately, this made the operator stop working because of v1beta1 removal on Ingress.

I've switched in my config (everything is managed by helm/helmfile) from:

```
operator:
  enabled: true
  config:
    ingressClass: traefik-{{ .Environment.Name }}
  replicaCount: 1
```

to:

```
ingressController:
  enabled: true
  ingressClassResource:
    default: true
  config:
    ingressClass: traefik-{{ .Environment.Name }}
    operatorMode: true
```

All pods are up & running, but I have infinite loop ('too may redirects' in Chrome, 'this page isn't redirected properly' in Firefox). Am I missing something here?

Additional info:
I also have a middleware named `forward-auth` configured in my `pomerium` namespace. It uses `http://pomerium-proxy.pomerium` as forwardAuth (`pomerium-proxy` is the name of service running proxy). All my Ingress has the annotations:

```
traefik.ingress.kubernetes.io/router.entrypoints: websecure
traefik.ingress.kubernetes.io/router.middlewares: pomerium-forward-auth@kubernetescrd
```

Versions:
- chart: 25.0.0 (I know it's a bit old, but for now I don't have time to upgrade to the most recent version, I need just this basic functionality working);
- pomerium version: 0.15.7

**Comment by wasaga** [comment]
The legacy operator (that's been deprecated for over a year) was only watching IngressV1beta1 resources and naturally does not support IngressV1. 

You cannot stay on the same chart version unfortunately and run a Kubernetes version that no longer uses IngressV1beta1 kind of resources. 

We also discourage use of forward auth and recommend using Pomerium as a first class ingress controller instead. 

Additionally, we migrated to a simpler all in one installation mode, please see https://www.pomerium.com/docs/k8s/quickstart

Helm based installations are still supported but are not recommended for new deployments or major upgrades.

**Comment by ftpd** [comment]
I'm aware that operator has been deprecated long time ago, I fully understand I can't run the old chart. I don't have v1beta1 Ingress anywhere anymore.

I would like to stay on helm, as everything else I manage via Helm and I just want/need my whole setup consistent. For now, we also don't have time and/or manpower to turn everything upside down and configure from scratch.

Ingress Controller was announced as a 'drop in' replacement for Operator (or at least I understood it this way). I have a ticket in the backlog to update to a new version and the new 'way' of doing it, but **for now** I would like to stay with working Pomerium with the least possible effort.

Can I do something 'quick' to achieve this?

**Comment by ftpd** [comment]
@wasaga any particular reason why GitLab is not in https://github.com/pomerium/ingress-controller/blame/main/deployment.yaml? I've checked the documentation here: https://www.pomerium.com/docs/reference/identity-provider-name and it's also not listed, but it's there: https://www.pomerium.com/docs/identity-providers/gitlab. So, is GitLab supported by Pomerium nowadays, or not?

I'm asking you directly, as it seems you were the person who commited `deployment.yaml` into ingress-controller repository.

**Comment by wasaga** [comment]
GitLab is a generic OIDC provider, you should be able to use it with the following [authenticate service settings](https://www.pomerium.com/docs/deploying/k8s/reference#identityprovider): 

```yaml
provider: oidc
scopes: ["openid","profile","email"]
url: https://gitlab.com
secret: namespace/gitlab-secret-name
```
