### ISSUE TITLE
Enterprise cannot connect to HTTP-only authenticate service

### ISSUE THREAD

**Issue by alexrudd2** [pomerium/pomerium#3885]
## What happened?
The Enterprise Console apparently cannot manage Core with `insecure_server: true`

## What did you expect to happen?
Either a functioning console, or documentation explaining that it cannot be done.

## How'd it happen?

1. My main production install (`git-3b2cc672`) handles external traffic from our gateway on `https://<my-domain>.com`, with `insecure_server: false` and proper certs, etc on a Docker Swarm
2. I established a test install (`0.20.0`) on a second Docker Swarm behind the main install, with `insecure_server: true`
3. I established a route for `https://<my-domain>-test.com` that passes to the second pomerium instance
4. I installed the Enterprise Console and pointed it at the test install

## What's your environment like?

- Pomerium version `0.20.0` on Docker Swarm on Ubuntu

## What's your config.yaml?

```yaml
authenticate_service_url: https://authenticate.localhost.pomerium.io
autocert: false
# alternatively, insecure mode can be used if behind a TLS terminating ingress,
# or when using a sidecar proxy
insecure_server: true
```
## What's your console-config.yaml?
```yaml
audience: console.localhost.pomerium.io
administrators: <>
database_encryption_key: <>
databroker_service_url: pomerium://pomerium_pomerium:5443
database_url: postgres://pomerium:pomerium@pomerium_pg-0/pomerium?sslmode=disable
shared_secret_file: "/run/secrets/POMERIUM_SHARED_SECRET"
license_key: <>
signing_key_file: "/run/secrets/POMERIUM_SHARED_SECRET"
authenticate_service_url: http://authenticate.localhost.pomerium.io
```
## What did you see in the logs?

```
{"level":"fatal","error":"Get \"https://authenticate.localhost.pomerium.io/.well-known/pomerium/jwks.json\": http: server gave HTTP response to HTTPS client","time":"2023-01-12T21:12:54Z"}
```
Various combinations of HTTP(S) in the two config files also don't work.

## Additional context

I had hoped to combine the console PSQL with the databroker PSQL.  The docs warn that problems with the Console, or attempting to access a database prematurely, may crash the PSQL container.  I am therefore trying to work out all the crashes on a test server first, before changing anything on my main install.  Unfortunately my gateway is not capable of sending traffic to different machines, so all external traffic must go through the secured pomerium instance.
