### ISSUE TITLE
Incomplete error handling/logging of config file parsing in Enterprise Console

### ISSUE THREAD

**Issue by alexrudd2** [pomerium/pomerium#3889]
## What happened?
I attempted to stand up Enterprise Console.  I tried to use Docker swarm secrets, which do not appear to be implemented (https://github.com/pomerium/pomerium/issues/3888).  The errors were incomplete and unhelpful.

## What did you expect to happen?
(A) A generic error on an invalid key in `console-config.yaml`.  (None was given)
(B) An error that `shared_secret` was empty/unset.  (None was given)
(C) More useful errors regarding the databroker.

For example, the error below doesn't make it obvious what is syncing (IDP?  license server?  databroker?) , or that I had a problem with the `databroker` connection.
```
{"level":"error","error":"failed to sync all external data sources: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.0.5.142:9443: connect: connection refused\"","time":"2023-01-13T18:08:35Z","message":"syncer"}
```
The error below doesn't make it obvious what is unauthenticated (the databroker connection), or what could go be failing (`shared_secret` was unset)
```
{"level":"fatal","error":"error running dashboard server: failed to sync all external data sources: error receiving record: rpc error: code = Unauthenticated desc = unauthenticated","time":"2023-01-12T23:15:43Z","message":"error running"}
```
(D) Clarity on `databroker_service_url` in documentation [here](https://docs.pomerium.com/docs/reference/data-broker-service-url) and [here](https://github.com/pomerium/documentation/blob/58930eae2c2e72ceaf642865acac72beb3f54e15/content/docs/releases/enterprise/install/quickstart.mdx).  Should it be `http://`, `https://`, `pomerium://`?  Should it include a port number?

## How'd it happen?

Troubleshooting the Console.

## What's your environment like?

- Pomerium version: Latest Enterprise console trying to connect to all-in-one `pomerium:git-3b2cc672` running in Docker Swarm on Ubuntu.

## What's your config.yaml?

```yaml
shared_secret_file: "/run/secrets/POMERIUM_SHARED_SECRET"
```

## What's your console-config.yaml?

```yaml
databroker_service_url: pomerium://pomerium_pomerium:9443. # TYPO, FAILS without good error message
databroker_service_url: https://pomerium_pomerium. #FAILS without good error message
databroker_service_url: pomerium://pomerium_pomerium:5443. #WORKS
shared_secret_file: "/run/secrets/POMERIUM_SHARED_SECRET". #FAILS SILENTLY
shared_secret: <blah>. # WORKS
```

## Additional context

I used the [pre-release documentation](https://github.com/pomerium/documentation/blob/58930eae2c2e72ceaf642865acac72beb3f54e15/content/docs/releases/enterprise/install/quickstart.mdx) for Docker Compose, and adapted to Swarm mode.
