### ISSUE TITLE
Enterprise: Traffic and Runtime unavailable (unknown service pomerium.dashboard.TimeSeriesDB)

### ISSUE THREAD

**Issue by alexrudd2** [pomerium/pomerium#3890]
## What happened?
![image](https://user-images.githubusercontent.com/52292902/212425999-b176313a-0290-4387-9a62-3233caca94b1.png)

## What did you expect to happen?
Working Traffic and Runtime reports

## How'd it happen?

1. Opened Console and clicked on Traffic
2. Observed error.
3. Opened Console and clicked on Runtime.
4. Observed same error.
5. Opened Console and clicked on Sessions
6. Observed useful data.

## What's your environment like?

- Pomerium version: Core `v0.19.0-28-g3b2cc672 + 3b2cc672`
Enterprise `0.20.0-1668477346 + e3316e4f + 2022-11-14T21:25:32Z`
Docker Swarm on Ubuntu
PSQL via `bitnami/postgresql-repmgr:15` only for Console (not shared with Core)

## What's your console-config.yaml?

```yaml
audience: pomerium.<domain>.com
administrators: <me>

database_encryption_key: <>
databroker_service_url: pomerium://pomerium_pomerium:5443
database_url: postgres://pomerium:pomerium@pomerium_pgc-1/pomerium?sslmode=disable
shared_secret: <>
license_key: <>
signing_key: <>
authenticate_service_url: https://authenticate.<domain>.com
```

## What did you see in the logs?

```logs
<startup>
{"level":"info","syncer_id":"pomerium-console-syncer","syncer_type":"","time":"2023-01-13T22:07:30Z","message":"listening for updates"}
{"level":"info","service":"syncer","time":"2023-01-13T22:07:36Z","message":"datasource: starting manager"}
<Click Traffic>
{"level":"info","grpc.duration":13.02447,"grpc.service":"pomerium.dashboard.RouteService","grpc.method":"ListRoutes","grpc.code":"OK","grpc.request":{"namespace":"9d8dbd2c-8cce-4e66-9c1f-c490b4a07243"},"grpc.response":{},"time":"2023-01-13T22:06:48Z","message":"finished unary call"}
<Click Runtime - no logs>
<Click Sessions>
{"level":"info","grpc.duration":195.21372,"grpc.service":"pomerium.dashboard.PomeriumSessionService","grpc.method":"ListPomeriumSessions","grpc.code":"OK","grpc.request":{},"grpc.response":{"sessions":[{"id":"MDRiYzVlNGEtODRlZS00YTA1LTlmYmYtMGYyODNjMjdlY2E5thNnmggU2ex3L5XXeMNfxf8Wl8STcVZTxscSFEKSxa0=",<snip>
```

## Additional context

I looked through the `0.20.0` release notes to see e.g. if these are new features that wouldn't be supported by `0.19.0` but found no indication.
