### ISSUE TITLE
Enterprise: Error on Create External Data Source (sql: no rows in result set)

### ISSUE THREAD

**Issue by alexrudd2** [pomerium/pomerium#3892]
## What happened?
![Screenshot 2023-01-13 at 4 57 02 PM](https://user-images.githubusercontent.com/52292902/212434119-02c03427-56d1-4998-8cc1-3df2b4f23f53.png)

I can see that the SQL database in fact has an entry in table `external_data_sources` (this came by default, something about Tor exit nodes)
![Screenshot 2023-01-13 at 5 05 36 PM](https://user-images.githubusercontent.com/52292902/212434894-3080188e-8c57-412e-a58d-516b343fd91a.png)

## What did you expect to happen?
Working page
## How'd it happen?

1. click Settings
2. Click Identity Providers
3. Click External Data Sources (in banner)

## What's your environment like?

- Pomerium version: Core `v0.19.0-28-g3b2cc672 + 3b2cc672`
Enterprise `0.20.0-1668477346 + e3316e4f + 2022-11-14T21:25:32Z`
Docker Swarm on Ubuntu
PSQL via `bitnami/postgresql-repmgr:15` only for Console (not shared with Core)

## What's your config.yaml?
```yaml
jwt_claims_headers:
- name
- email
- picture
- groups
- given_name
- family_name

# Use HA PSQL databroker backend
databroker_storage_type: postgres
databroker_storage_connection_string: postgres://pomerium:pomerium@pomerium_pg-0,pomerium_pg-1,pomerium_pg-2/pomerium?sslmode=disable&target_session_attrs=read-write

# Identity Provider Settings
## GOOGLE
idp_provider: "google"
idp_client_id: <>
idp_client_secret_file: "/run/secrets/POMERIUM_IDP_CLIENT_SECRET"
idp_service_account: <>

```

## What's your console-config.yaml?

```yaml
audience: pomerium.<domain>.com
administrators: <me>

database_encryption_key: <>
databroker_service_url: pomerium://pomerium_pomerium:5443
database_url: postgres://pomerium:pomerium@pomerium_pgc-1/pomerium?sslmode=disa>
shared_secret: <>
license_key: <>
signing_key: <>
authenticate_service_url: https://authenticate.domain.com
```

## What did you see in the logs?

```logs
{"level":"warn","error":"sql: no rows in result set","grpc.duration":9.74506,"grpc.service":"pomerium.dashboard.ExternalDataSourceService","grpc.method":"GetExternalDataSource","grpc.code":"Unknown","grpc.request":{"id":"NTg5MDQ1M2ItZDM0NS00OWEzLWE4ZmEtNjUzZWU0OGRjZDEwthNnmggU2ex3L5XXeMNfxf8Wl8STcVZTxscSFEKSxa0="},"grpc.response":{},"time":"2023-01-13T22:58:16Z","message":"finished unary call"}
```

## Additional context

The only reason I care about External Data Sources (or even the Enterprise Console at all) is to restore access control via group membership with Google as IDP.  This was [broken](https://discuss.pomerium.com/t/groups-changes-in-0-20-0/192/2) for whatever reason in `0.20.0`.
