### ISSUE TITLE
`Access-Control-Allow-Origin` and AJAX calls issue

### ISSUE THREAD

**Issue by mohsen0** [pomerium/pomerium#390]
## What happened?

So I am trying to secure an AWS s3 website by putting pomerium in front of it.
I have setup CORs and configured the two s3 endpoints correctly, I mean it works without proxy alright.

```yaml
  - from: https://reports.example.com
    to: http://my-reports.s3-website-eu-west-1.amazonaws.com
    allowed_groups:
      - developers@example.com
  - from: https://reports-s3.example.com
    to: https://my-reports.s3-eu-west-1.amazonaws.com
    allowed_groups:
      - developers@example.com
```

The index page is a simple HTML page, which there is some javascript code that read from the XML feed in `https://my-reports.s3-eu-west-1.amazonaws.com` by invoking an ajax call 

## What did you expect to happen?

So the setup works without the proxy, but when the proxy is in place, the `Access-Control-Allow-*` headers are not set.

```
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 0
```

and the underlying AJAX call redirected using 302 and it seems to be canceled by the browser when it tries to be authenticated by the `authenticate.example.com`.

## How'd it happen?

1. create a bucket
2. setup a website setup
3. upload https://github.com/rufuspollock/s3-bucket-listing
4. configure the pomerium as front to that bucket
5. try to access to the page.

## What's your environment like?

- Pomerium version : 0.4.0
- Server Operating System/Architecture/Cloud: kubernetes 1.12

## What's your config.yaml?

```config.yaml
  - from: https://reports.example.com
    to: http://my-reports.s3-website-eu-west-1.amazonaws.com
    allowed_groups:
      - developers@example.com
  - from: https://reports-s3.example.com
    to: https://my-reports.s3-eu-west-1.amazonaws.com
    allowed_groups:
      - developers@example.com
```

## What did you see in the logs?

browser console logs:

```logs
Access to XMLHttpRequest at 'https://reports-s3.example.com/?delimiter=/&prefix=reports/' from origin 'https://reports.example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

[reports.example.com.har.zip](https://github.com/pomerium/pomerium/files/3859780/reports.example.com.har.zip)

## Additional context

https://github.com/pomerium/pomerium/pull/387

**Comment by desimone** [comment]
@mohsen0 Thank you for the detailed issue!

Does enabling `cors_allow_preflight` help? [docs](https://www.pomerium.io/configuration/#policy)

**Comment by mohsen0** [comment]
No I have tried that

**Comment by desimone** [comment]
When you tried adding `cors_allow_preflight: true` to those handlers, you saw the same error?

That setting should be allowing the preflight requests to pass-through to to your application. 🤔

**Comment by mohsen0** [comment]
So I enabled the `cors_allow_preflight: true` too, and nothing changed, In the developer tools, I could see that there is no OPTION call, but there is GET AJAX call that gets redirected with 302 and since there is not `Access-Control-Allow-*` set, it fails.
I attached HAR file with `cors_allow_preflight` enable.
[reports.example.com-1.har.zip](https://github.com/pomerium/pomerium/files/3870425/reports.example.com-1.har.zip)

**Comment by desimone** [comment]
Thanks @mohsen0  I will investigate.

**Comment by mohsen0** [comment]
Loading Kibana this issue happens for this call which is weird. Since other AJAX calls do have their `Access-Control-Allow` set behind the proxy. only this call gets redirected.
it seems to be the first AJAX call on the page.
`GET https://kibana-dev.example.com/ui/favicons/manifest.json`

**Comment by mohsen0** [comment]
Any new discovery on this issue?

**Comment by desimone** [comment]
@mohsen0 I'm not exactly sure what's going on from the logs and the har file alone.

Do you mind posting more context both in the form of `har` and both your application and pomerium logs?  If sensitive, feel free to email me bdd@pomerium.io. `CORs` issues are an absolute pain to debug and isolate.

**Comment by commixon** [comment]
Hi everyone. Just wanted to say that we have the exact same problem.
We have one SPA portal and one api backend. They are exposed as follows:
```
     -  from: https://spa.my.root.domain
        to: http://spa.pomerium.svc.cluster.local
        allowed_domains:
          - domain.co
        cors_allow_preflight: true
     -  from: https://api.my.root.domain
        to: http://api.pomerium.svc.cluster.local
        allowed_domains:
          - domain.co
        cors_allow_preflight: true
```

When visiting each one of those separately everything works fine. But when the JS code in our SPA tries to perform AJAX calls, we get the error mentioned in the previous comments:

`Access to XMLHttpRequest at 'https://api.my.root.domain/api/v1/search?page=1&name=' from origin 'https://spa.my.root.domain' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
