### ISSUE TITLE
pomerium:debug image does not work

### ISSUE THREAD

**Issue by ssveta7ak** [pomerium/pomerium#3914]
## What happened?
pomerium: debug image does not work
## How'd it happen?

1. Run Pomerium with Docker compose
2. Set pomerium: debug image in the config
3. Debug image doesn't work.

## What's your environment like?
pomerium: 0.21.0-rc1-1674048966+e8004bbb

## What's your docker-compose.yaml?
```
version: "3"
services:
  pomerium:
    image: pomerium/pomerium:debug
    volumes:
      - ./_wildcard.localhost.pomerium.io.pem:/pomerium/cert.pem:ro
      - ./_wildcard.localhost.pomerium.io-key.pem:/pomerium/privkey.pem:ro
      - ./config.yaml:/pomerium/config.yaml:ro
    ports:
      - 443:443
```
## What did you see in the logs?

```logs
{"level":"info","config_file_source":"/pomerium/config.yaml","bootstrap":true,"path":"/tmp/pomerium-envoy3357010005/envoy","checksum":"05e1343657086268edaa16a1e8a1429d9c8f6e50a44f492cf629fdc71da2ecdc","time":"2023-01-23T17:31:38Z","message":"running envoy"}
pomerium_docker-pomerium-1  | {"level":"info","pid":17,"time":"2023-01-23T17:31:38Z","message":"envoy: start monitoring subprocess"}
pomerium_docker-pomerium-1  | {"service":"envoy","name":"envoy","time":"2023-01-23T17:31:38Z","message":"Error relocating /tmp/pomerium-envoy3357010005/envoy: fcntl64: symbol not found"}

pomerium_docker-pomerium-1  | {"level":"fatal","pid":17,"time":"2023-01-23T17:31:39Z","message":"envoy: subprocess exited"}
pomerium_docker-pomerium-1 exited with code 1

```
