### ISSUE TITLE
Quick start (docker compose) doesn't work 

### ISSUE THREAD

**Issue by ssveta7ak** [pomerium/pomerium#3915]
Need to add information about certificates.

```
{"level":"error","error":"hpke: error requesting jwks endpoint: Get \"https://authenticate.localhost.pomerium.io/.well-known/pomerium/jwks.json\": x509: certificate signed by unknown authority","request-id":"25dc688f-a130-48d5-b88e-f9ac882bdc7a","time":"2023-01-23T17:38:13Z","message":"grpc check ext_authz_error"}
```
https://www.pomerium.com/docs/quickstart

docker-compose.yaml
```version: "3"
services:
  pomerium:
    image: pomerium/pomerium:v0.21.0-rc1
    volumes:
      - ./_wildcard.localhost.pomerium.io.pem:/pomerium/cert.pem:ro
      - ./_wildcard.localhost.pomerium.io-key.pem:/pomerium/privkey.pem:ro
      - ./config.yaml:/pomerium/config.yaml:ro
    ports:
      - 443:443
  verify:
    image: pomerium/verify:latest
    expose:
      - 8000
```

config.yaml
```
authenticate_service_url: https://authenticate.localhost.pomerium.io
certificate_file: /pomerium/cert.pem
certificate_key_file: /pomerium/privkey.pem
dns_lookup_family: V4_ONLY

idp_provider: 'auth0'
idp_provider_url: 'https://dev-zecq6kxx.us.auth0.com'
idp_client_id: <>
idp_client_secret: <>
cookie_secret: <>
shared_secret: <>
routes:
  - from: https://verify.localhost.pomerium.io
    to: https://httpbin.org
    policy:
      - allow:
          or:
            - domain:
                is: gmail.com
            - domain:
                is: pomerium.com
```
