### ISSUE TITLE
footgun: set authenticate URL same as route

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#3953]
@wasaga commented on [Tue Feb 07 2023](https://github.com/pomerium/internal/issues/1263)

## What happened?

A naive user may set configuration to protect a single website with pomerium as follows: 

```yaml
authenticate_service_url: https://my-website.com

routes:
  - from: https://my-website.com
     to: http://localhost:8000
     allow_domains: ['my-website.com']
```

This, however would result in a broken configuration - user would land to `/.pomerium` all the time. 

I suspect this is this problem https://discuss.pomerium.com/t/forward-to-domain-pomerium/227/7 

We do not seem to have any documentation saying this is prohibited. https://www.pomerium.com/docs/reference/authenticate-service-url

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`):
- Server Operating System/Architecture/Cloud:
