### ISSUE TITLE
rewrite_response_headers doesn't handle `-` properly

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/pomerium#3960]
## What happened?
A configuration like:

```
- from: https://mediamorph-abc.pomerium.mydomain.com
  to: https://test-abc.mediamorph.com
  rewrite_response_headers:
  - header: Location
    prefix: https://test-abc.mediamorph.com/
    value: https://mediamorph-abc.pomerium.mydomain.com/
```

doesn't work, because the `replace_prefix` lua function uses `gsub` which doesn't handle `-` properly.

## What did you expect to happen?

For it to work!
