### ISSUE TITLE
IC: x-frame-options header always returns the default value

### ISSUE THREAD

**Issue by ssveta7ak** [pomerium/pomerium#4013]
## What happened?

**Pomerium Ingress Controller**: 
It is impossible to override the `x-frame-options` header - it will still return the default value of SAMEORIGIN."
The issue is only related to `x-frame-options` header; other headers work properly.

## What's your config?

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.pomerium.io/set_response_headers: '{"x-frame-options":"DENY", "hello":"there"}'
``` 

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```

## Additional context

Related https://github.com/pomerium/pomerium/issues/4014
