### ISSUE TITLE
IC: `disable: true` doesn't work for the `set_response_headers`  config file key as described in the documentation.

### ISSUE THREAD

**Issue by ssveta7ak** [pomerium/pomerium#4014]
## What happened?
**Ingress Controller:**
`disable: true` doesn't work for the `set_response_headers`  config file key as described in the documentation.
https://www.pomerium.com/docs/reference/set-response-headers

## What's your config?

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.pomerium.io/set_response_headers: '{"x-frame-options":"DENY", "hello":"there"}'
```

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```
