### ISSUE TITLE
Addition of X25519 key to JWKS endpoint causing issues with proxied services (e.g. Grafana)

### ISSUE THREAD

**Issue by timw6n** [pomerium/pomerium#4029]
## How'd it happen?

Have recently updated from v0.19.1 to v0.21.2. 

Since that point both Grafana (we followed the guide in the Pomerium docs) and an internal tool using PyJWT are unable to read JWT claim headers. The complaint is along the lines of "unknown curve X25519" for both, which leads me to think that it is https://github.com/pomerium/pomerium/pull/3762/files that is causing the problems.

Raising this as a bug as breaking existing integrations may have been an unforeseen consequence of adding the new key to the JWKS, especially as there's no entry in the upgrading guide.

Is there a setting we can choose to exclude the HPKE key from the JWKS file? 
If so can the Grafana guide and upgrading doc be updated?
If not, can some kind of setting (or query param to the JWKS endpoint) be added to make these work?

Unless we're doing something wrong, doubt we're the only user in this position atm.

## What's your environment like?

As above.

## What's your config.yaml?

Pomerium side:
```
          jwt_claims_headers: name

          routes:
            - from: https://grafana.XXX.net
              to: http://YYY:3000
              pass_identity_headers: true
              policy: ZZZ
```

Grafana side:
```
                # https://www.pomerium.com/docs/guides/grafana
                - GF_AUTH_JWT_ENABLED=true
                - GF_AUTH_JWT_HEADER_NAME=X-Pomerium-Jwt-Assertion
                - GF_AUTH_JWT_EMAIL_CLAIM=email
                - GF_AUTH_JWT_JWK_SET_URL=https://XXX/.well-known/pomerium/jwks.json
                - GF_AUTH_JWT_CACHE_TTL=60m
                - GF_AUTH_JWT_USERNAME_CLAIM=email
                - GF_AUTH_JWT_AUTO_SIGN_UP=true
                - GF_AUTH_JWT_ROLE_ATTRIBUTE_PATH=(email == 'AAA' || email == 'BBB') && 'Admin' || 'Editor'

```
