### ISSUE TITLE
Cloud Run guide doesn't work

### ISSUE THREAD

**Issue by JonnyDaenen** [pomerium/pomerium#4091]
## What happened?

Trying to setup the Cloud Run sample from [this guide](https://www.pomerium.com/docs/guides/cloud-run.html).

Note that there is also a guide on [Google Cloud](https://cloud.google.com/community/tutorials/cloud-run-with-pomerium-for-end-user-access), which has different instructions. I also tried these.

## What did you expect to happen?

Working setup

## How'd it happen?

1. Configured DNS subdomain cloudrun.mydomain.com
2. Executed all instructions
3. Set up web application in Google Cloud with callback to `https://authn.cloudrun.mydomain.com/oauth2/callback`
4. setup all urls: authn, httpbin, hello and verify - guide is unclear about httpbin vs verify

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): v0.13.1-cloudrun
- Server Operating System/Architecture/Cloud: Google Cloud

## What's your config.yaml?

```config.yaml
authenticate_service_url: "https://authn.cloudrun.mydomain.com"
shared_secret: "random genereted value"
cookie_secret: "random genereted value"
idp_provider: "google"
idp_client_id: "sample.apps.googleusercontent.com"
idp_client_secret: "secret from the GCP console"

```

policy:

```
- from: https://hello.cloudrun.mydomain.com
  to: https://hello-h2g2afqdba-uc.a.run.app
  allowed_domains:
    - gmail.com
  enable_google_cloud_serverless_authentication: true
- from: https://verify.cloudrun.mydomain.com
  to: https://verify.pomerium.com
  pass_identity_headers: true
  allowed_domains:
    - gmail.com
```

Also tried this with httpbin instructions.

## What did you see in the logs?

```logs
message: "grpc check ext_authz_error"
level: "error"
error: "hpke: error requesting hpke-public-key endpoint: Get "https://127.0.0.1/.well-known/pomerium/hpke-public-key": dial tcp 127.0.0.1:443: connect: connection refused"
```

## Additional context

- [x] cloud run is hit when hitting all the urls
