### ISSUE TITLE
Incompatibility between regex and pass_identity_headers

### ISSUE THREAD

**Issue by namelivia** [pomerium/pomerium#4168]
## What happened?

I [configured an application to work with JWT authentication](https://github.com/hay-kot/mealie/pull/2206).

My configuration would look like:
```yaml
jwt_claims_headers:
  - email
  - aud
  - email
  - email_verified
  - exp
  - family_name
  - given_name
  - iat
  - iss
  - locale
  - name
  - picture
  - sub

policy:

  - from: http://myapp.mydomain.com
    to: http://host1:80
    pass_identity_headers: true
    allowed_users:
      - myemail@gmail.com
```

And it was working so far, however, I wanted to allow public unauthenticated access for the `/api/*` paths so other non-web clients can request tokens and access the application without being prompted with the IdP login screen.

The way I was able to achieve this separation was by setting the following configuration:
```yaml
  - from: http://myapp.mydomain.com
    to: http://host1:80
    regex: ^/api/.*$
    allow_public_unauthenticated_access: true

  - from: http://myapp.mydomain.com
    to: http://host1:80
    pass_identity_headers: true
    allowed_users:
      - myemail@gmail.com
```

Then after rolling out that configuration, users could no longer login in the app, and I've done some debugging and apparently, the jwt header is now not being set, so that's why the automatic login failed.

Rolling back to the previous configuration (removing the api path rule) restored the login back to normal.

## What did you expect to happen?

I would expect the jwt header to be set for those calls that do not match the `/api` path regex after logging in in the IdP.

## What's your environment like?

- Pomerium v0.21.3

**Comment by calebdoxsey** [comment]
Each route is independent. We do not merge settings across matching routes. If the first route matches the second route's settings will not be applied. Add the `pass_identity_headers` setting to the first route.

```yaml
  - from: http://myapp.mydomain.com
    to: http://host1:80
    regex: ^/api/.*$
    allow_public_unauthenticated_access: true
    pass_identity_headers: true
```

However the identity header won't be useful for an unauthenticated route. We won't know the identity of the user, because there is no user.
