### ISSUE TITLE
pass access token or id token in a non-Authorization header

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/pomerium#4209]
**Is your feature request related to a problem? Please describe.**
The ability to pass the id token or access token was added in https://github.com/pomerium/pomerium/pull/3047. The token is always sent as the `Authorization` header.

Some applications already use the `Authorization` header for other reasons, so it would be nice to support passing the id token or access token in a different header.

**Describe the solution you'd like**
An option like `set_authorization_header` but the token would be in a different header.

**Comment by desimone** [comment]
Let's deprecate `set_authorization_header` and instead adopt this functionality in `set_request_headers` which takes a map instead of a string. 

```yaml
- from: https://verify.corp.example.com
  to: https://verify.pomerium.com
  policy:
    - allow:
        or:
          - email:
              is: user@example.com
  set_request_headers:
    x-pomerium-downstream-id-token: $pomerium.id_token
    x-pomerium-downstream-access-token: $pomerium.access_token
```

Let's warn that `set_authorization_header` is deprecated for a version. We can remove `set_authorization_header` after another release.
