### ISSUE TITLE
remove `set_authorization_header` in v0.24.0

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#4214]
Let's deprecate `set_authorization_header` and instead adopt this functionality in `set_request_headers` which takes a map instead of a string. 

```yaml
- from: https://verify.corp.example.com
  to: https://verify.pomerium.com
  policy:
    - allow:
        or:
          - email:
              is: user@example.com
  set_request_headers:
    x-pomerium-downstream-id-token: $pomerium.id_token
    x-pomerium-downstream-access-token: $pomerium.access_token
```

Let's warn that `set_authorization_header` is deprecated for a version. We can remove `set_authorization_header` after another release.

_Originally posted by @desimone in https://github.com/pomerium/pomerium/issues/4209#issuecomment-1570608757_
