### ISSUE TITLE
feature: support passing client credential details upstream

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#4259]
**Is your feature request related to a problem? Please describe.**

Pomerium does not currently have a good way to link device identity with device state from an external system.  

WebAuthN provides device identity linked to a user and registration event. However, because WebAuthN (understandably) does not want device attestation to be used as a super cookie, it is not possible to link webauthn registrations to an linkable external identifier. 

As we wait for more progress in this space, the most obvious way to link device identity, with device state (usually through another mdm/ endpoint protection solution), and user identity is through client certificates. 

**Describe the solution you'd like**

In core, Pomerium should support passing down client certificate details to upstream services as an assertion header similar to what we recently supported with id_token, and access_token. For example:

```yaml
- from: https://verify.corp.example.com
  to: https://verify.pomerium.com
  policy:
    - allow:
        or:
          - email:
              is: user@example.com
  set_request_headers:
    x-pomerium-client-cert-fingerprint: $pomerium.client_cert_fingerprint
```

In enterprise & zero, we should add support to write policy against the incoming `client_cert_fingerprint` as a PPL criterion matcher. 

**Describe alternatives you've considered**

N/A

**Explain any additional use-cases**

N/A

**Additional context**

- https://github.com/pomerium/pomerium/issues/4209
- https://smallstep.com/docs/step-cli/reference/certificate/fingerprint/
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#envoy-v3-api-msg-extensions-transport-sockets-tls-v3-certificatevalidationcontext

**Comment by desimone** [comment]
Instead of just providing fingerprint of the client cert, I think it makes sense to follow envoy's spec of XFCC

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-client-cert

**Comment by kenjenkins** [comment]
I have a few questions:

1. Do we want to provide guidance on how to ensure that upstream services can trust this information?
   - is this something that we would want to include in the Pomerium attestation JWT?
   - or should we recommend that this only be used in combination with upstream mTLS?
2. I have some mild hesitation around extending the `$pomerium.XXX` syntax we recently added. If we might end up adding a bunch of different variable substitutions, would it be better to use something like `${pomerium.XXX}`, so we don't run into ambiguities around where variable names end?

I think the idea of exposing Envoy's `X-Forwarded-Client-Cert` feature is interesting, but I'm not sure what the best syntax for it would be. Maybe something like this?
```yaml
- from: https://verify.corp.example.com
  to: https://verify.pomerium.com
  policy: {...}
  forward_client_cert_details:
    - hash
    - cert
    - chain
    - subject
    - uri
    - dns
```

Although the format of the `X-Forwarded-Client-Cert` header is a little annoying to parse (comma-separated list of semicolon-separate values, which may be double-quoted). I'm also not sure I quite understand Envoy's `By` value.
