### ISSUE TITLE
Feature request: stricter client certificate enforcement

### ISSUE THREAD

**Issue by kenjenkins** [pomerium/pomerium#4353]
Add a configuration option to enable stricter enforcement of downstream mTLS: when a connection is made without a valid client certificate, reject the connection attempt altogether, instead of serving a Pomerium error page.

Note that this would apply not just to routes defined in the Pomerium configuration but also to internal Pomerium routes (such as the HPKE public key endpoint and the JWKS endpoint).

~~Depends on #4352.~~

**Comment by kenjenkins** [comment]
Note: the current plan is to add support for three new settings.
```yaml
downstream_mtls:
  enforcement: "reject_connection" | "policy_with_default_deny" | "policy"
  max_verify_depth: 1
  match_subject_alt_names:
    - dns: '.*\.corp\.example\.com'
```

Setting `enforcement: reject_connection` will trigger the new behavior of rejecting connection attempts during the initial TLS handshake. The default behavior will continue to be `enforcement: policy_with_default_deny`.

The `max_verify_depth` setting will behave just as the [Envoy setting](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto.html#envoy-v3-api-field-extensions-transport-sockets-tls-v3-certificatevalidationcontext-max-verify-depth) of the same name.

The `match_subject_alt_name` settings will allow for regex matching of certificate Subject Alternative Name entries.
