### ISSUE TITLE
OPENSSL_internal:CERTIFICATE_VERIFY_FAILED using self-managed CA, despite tls_custom_ca_file

### ISSUE THREAD

**Issue by cmrtdev** [pomerium/pomerium#4366]
## What happened?

I am trying to set up Grafana authentication using Pomerium (following [the guide](https://www.pomerium.com/docs/guides/grafana), then enabling HTTPS for Grafana); Grafana is running HTTPS on port 3000 on a different host than Pomerium.

I use [`cfssl`](https://github.com/cloudflare/cfssl) to maintain an internal CA for my network and distribute certificates to internal services that need it (including Grafana). Pomerium is configured with a wildcard cert from Let's Encrypt.

When I try to connect to `https://grafana.mydomain.tld` I get this error

```
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

## What did you expect to happen?

Grafana appears

## How'd it happen?

1. Configured the Grafana route as shown in the config below
2. I confirmed the CA is trusted using `curl` (`ca-certificates.crt` is mounted)
3. Opened `grafana.mydomain.tld`, got the error

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): Docker image `pomerium/pomerium:debug` updated 2 days ago.
```
root@60cca1c0b241:/pomerium# pomerium --version
pomerium: v0.0.0
envoy: 1.25.5+b1095c058415dfb2261e695a0f144311a7dc346b6eb47ecbb0a01b7de2c7299f
```

- Server Operating System/Architecture/Cloud: Debian 12, Kernel 6.1.0-9-amd64, Docker version 24.0.4, build 3713ee1

## What's your config.yaml?

```config.yaml
# See detailed configuration settings : https://www.pomerium.com/docs/reference/


# this is the domain the identity provider will callback after a user authenticates
authenticate_service_url: https://authenticate.<REDACTED>

####################################################################################
# Certificate settings:  https://www.pomerium.com/docs/reference/certificates.html #
# The example below assumes a certificate and key file will be mounted to a volume #
# available to the  Docker image.                                                  #
####################################################################################
certificates:
  - cert: /pomerium/fullchain.pem
    key: /pomerium/key.pem

##################################################################################
# Identity provider settings : https://www.pomerium.com/docs/identity-providers/ #
# The keys required in this section vary depending on your IdP. See the          #
# appropriate docs for your IdP to configure Pomerium accordingly.               #
##################################################################################
idp_provider: google
idp_client_id: <REDACTED>
idp_client_secret: <REDACTED>

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
cookie_secret: <REDACTED>

# https://www.pomerium.com/docs/reference/signing-key
# https://www.pomerium.com/docs/topics/getting-users-identity
signing_key: <REDACTED>

shared_secret_file: /pomerium/shared.secret

databroker_storage_type: postgres
databroker_storage_connection_string: postgres://<REDACTED>/pomerium?sslmode=disable

# DEBUG ENVOY
#log_level: debug
proxy_log_level: debug
#pomerium_debug: true
# END DEBUG

# https://pomerium.com/reference/#routes
routes:
  # [other routes here]
  # Grafana
  - from: https://grafana.<REDACTED>
    to: https://192.168.x.y:3000
    host_rewrite_header: true
    tls_custom_ca_file: /pomerium/cas/ca-certificates.crt
    policy:
      - allow:
          or:
            - email:
                is: <REDACTED>
    pass_identity_headers: true
  # [more routes here]
```

### docker-compose.yaml
```yaml
version: "3"
services:
  pomerium:
    #image: pomerium/pomerium:latest
    image: pomerium/pomerium:debug
    volumes:
      ## Mount your domain's certificates : https://www.pomerium.com/docs/reference/certificates
      - /etc/acme.sh/data/<REDACTED>/fullchain.pem:/pomerium/fullchain.pem:ro
      - /etc/acme.sh/data/<REDACTED>/key.pem:/pomerium/key.pem:ro
      - /etc/ssl/certs/:/pomerium/cas:ro # DEBUG (?)
      - /etc/ssl/:/etc/ssl:ro # DEBUG
      - /usr/share/ca-certificates/:/usr/share/ca-certificates:ro # Needed by /etc/ssl
      - /usr/local/share/ca-certificates/:/usr/local/share/ca-certificates # DEBUG (
      #- /opt/pomerium/rsaroot-test.pem:/pomerium/rsaroot-test.pem # DEBUG
      - /tmp/bin:/usr/local/bin # DEBUG (contains curl)
      #- /usr/bin/openssl:/usr/local/bin/openssl:ro  # DEBUG
      #- /usr/lib:/usr/lib:ro # DEBUG
      #- /lib:/usr/local/lib:ro # DEBUG

      ## Mount your config file : https://www.pomerium.com/docs/reference/
      - /opt/pomerium/config.yaml:/pomerium/config.yaml:ro
      ## Mount the shared secret
      - /opt/pomerium/shared.secret:/pomerium/shared.secret:ro
    ports:
      - 443:443
      - 4444:4444
    restart: unless-stopped
    networks:
      pomerium:
    environment:
      - ENVOY_ADMIN_ADDRESS=0.0.0.0:4444
      - ENVOY_ADMIN_ACCESS_LOG_PATH=/tmp/envoyaccess.log

  ## https://verify.localhost.pomerium.io --> Pomerium --> http://verify
  verify:
  <not relevant>

networks:
  pomerium:
    ipam:
      config:
        - subnet: 172.18.0.0/24

```
## What did you see in the logs?

[full log here](https://gist.github.com/cmrtdev/d1a399fa867b71b3790f80192ce99239)

```logs
{
    "level": "info",
    "service": "envoy",
    "upstream-cluster": "route-680959ae2bd3b434",
    "method": "GET",
    "authority": "grafana.<REDACTED>",
    "path": "/",
    "user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0",
    "referer": "",
    "forwarded-for": "192.168.a.b",
    "request-id": "a9ff648f-5327-4628-aab7-23cc43820a9c",
    "duration": 18.021338,
    "size": 195,
    "response-code": 503,
    "response-code-details": "upstream_reset_before_response_started{connection_failure,TLS_error:_268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED}",
    "time": "2023-07-16T11:16:14Z",
    "message": "http-request"
}
```

### Grafana logs
```
grafana-loki-grafana-1  | server.go:3217: http: TLS handshake error from <pomerium IP>:56150: remote error: tls: unknown certificate
```

## Additional context

I've been trying to fix this for a while (~months; I work on it sporadically and access Grafana directly in the meantime) and I've tried a lot of things, which is why there's commented directives (and in general weird things) in my `docker-compose.yaml`.

It's also why I'm using the debug image: it allowed me to `docker exec -it pomerium /bin/bash` into the container and try things there.

Watchtower has been upgrading the Docker image automatically since I started using Pomerium, so this affects different versions.

`ca-certificates.crt` was created by `update-ca-certificates` after adding the custom CA in `/usr/local/share/ca-certificates`. This is pretty standard and it's working fine everywhere else (I also tested it, described below).

I tried removing `tls_custom_ca_file` and just mounting the system trust store (`/etc/ssl` & others; the CA is trusted by it) but that didn't work either.

From the ENVOY_ADMIN > certs page I see that ca-certificates.crt has been loaded correctly (see below).

My internal CA is `ecdsa`; I thought that may have been a problem so I just created an RSA CA and leaf cert for Grafana, loaded the CA in Pomerium as `tls_custom_ca_file`, confirmed it was loaded from ENVOY_ADMIN and still got the TLS error.

I loaded a statically compiled `curl` into the running container and successfully used it to `curl https://192.168.x.y:3000` (I get a `302 found` redirecting me to `/login`). I tried to load `openssl` (to check with `openssl s_client`) but couldn't find a statically linked one and mounting my system's `/lib` over the container's broke everything (but if `curl` worked so should've Pomerium).

### Envoy Admin > certs
```json
{
 "certificates": [
  {
   "ca_cert": [
    {
     "path": "/root/.cache/pomerium/envoy/files/ca-certificates-<random_number>.crt",
     "serial_number": "<REDACTED>",
     "subject_alt_names": [],
     "days_until_expiration": "2724",
     "valid_from": "2011-05-05T09:37:37Z",
     "expiration_time": "2030-12-31T09:37:37Z"
    }
   ],
   "cert_chain": []
  },
  {
   "ca_cert": [],
   "cert_chain": [
    {
     "path": "/root/.cache/pomerium/envoy/files/tls-crt-<random_number>.pem",
     "serial_number": "<REDACTED>",
     "subject_alt_names": [
      {
       "dns": "*.<REDACTED>"
      }
     ],
     "days_until_expiration": "<REDACTED>",
     "valid_from": "<REDACTED>",
     "expiration_time": "<REDACTED>"
    },
    {
     "path": "/root/.cache/pomerium/envoy/files/tls-crt-<random_number>.pem",
     "serial_number": "<REDACTED>",
     "subject_alt_names": [
      {
       "dns": "*"
      }
     ],
     "days_until_expiration": "9999",
     "valid_from": "2022-12-01T00:00:00Z",
     "expiration_time": "2050-12-01T00:00:00Z"
    }
   ]
  },
  {
   "ca_cert": [
    {
     "path": "/root/.cache/pomerium/envoy/files/ca-certificates-<random_number>.crt",
     "serial_number": "<REDACTED>",
     "subject_alt_names": [],
     "days_until_expiration": "2724",
     "valid_from": "2011-05-05T09:37:37Z",
     "expiration_time": "2030-12-31T09:37:37Z"
    }
   ],
   "cert_chain": []
  }
 ]
}

**Comment by kenjenkins** [comment]
Hi @cmrtdev, thanks for reporting this issue. I suspect that the certificate verification failure may be related to a server name matching condition.

Specifically, it looks like Pomerium will configure the upstream cluster in Envoy with a SAN matcher, based on the domain in the route's `to` URL. From your config.yaml file, it looks like you've configured the route to Grafana using an IP address, so I believe Pomerium is going to expect the upstream certificate for that route to include that 192.168.x.y value as a DNS Subject Alternative Name (SAN).[^1]

[^1]: Side note: this might be a bug in its own right, as 192.168.x.y is not a DNS name.

You can override the server name used for this match by setting [`tls_upstream_server_name`](https://www.pomerium.com/docs/reference/routes/tls#tls-upstream-server-name) on the route.

For example, if your Grafana certificate included `grafana.mydomain.tld` as a SAN you should be able to configure this route like so:
```yaml
  - from: https://grafana.<REDACTED>
    to: https://192.168.x.y:3000
    host_rewrite_header: true
    tls_custom_ca_file: /pomerium/cas/ca-certificates.crt
    tls_upstream_server_name: grafana.mydomain.tld
    policy:
      - allow:
          or:
            - email:
                is: <REDACTED>
    pass_identity_headers: true
```

Let me know if that makes sense.
