### ISSUE TITLE
Integration with Tiddlywiki doesn't work

### ISSUE THREAD

**Issue by ssveta7ak** [pomerium/pomerium#4449]
## What happened?
Integration with Tiddlywiki doesn't work.

Now Tiddlywiki requires URI-decoded authenticated-user-header. 
https://tiddlywiki.com/static/WebServer%2520Parameter%253A%2520authenticated-user-header.html

So Pomerium integration with Tiddlywiki is not working now. 
It redirect to the HTTP Basic Authenticator intead of IdP.

![Screenshot from 2023-08-09 17-37-39.png](https://images.zenhubusercontent.com/63bc6de617e71f0442fdda1c/472686b4-b393-46b9-84d5-4ff5dd0ec1d9)

## How'd it happen?

1. Ran `x`
2. Clicked `y`
3. Saw error `z`

## What's your environment like?
pomerium: 0.22.2

## What's your docker-compose.yaml?

```
grafana:
    image: grafana/grafana:latest
    user: "1000:1000"
    networks:
      main: {}
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_SIGNOUT_REDIRECT_URL=https://grafana.localhost.pomerium.io/.pomerium/sign_out
      - GF_AUTH_JWT_ENABLED=true
      - GF_AUTH_JWT_HEADER_NAME=X_POMERIUM_JWT_ASSERTION
      - GF_AUTH_JWT_EMAIL_CLAIM=email
      - GF_AUTH_JWT_JWK_SET_URL=https://grafana.localhost.pomerium.io/.well-known/pomerium/jwks.json
      - GF_AUTH_JWT_CACHE_TTL=60m
      - GF_AUTH_JWT_AUTO_SIGN_UP=true
    volumes:
      - ./grafana-storage:/var/lib/grafana/plugins:rw
```

##What's your config.yaml?
```
  - from: https://grafana.localhost.pomerium.io
    to: http://grafana:3000
    host_rewrite_header: true
    pass_identity_headers: true
    policy:
      - allow:
         or:
          - domain:
                is: gmail.com
          - domain:
                is: pomerium.com
```

## What did you see in the logs?

```
grafana_core-pomerium-1  | {"level":"info","service":"authorize","request-id":"06985ae7-cb6e-4894-a25d-02b638db3c0b","check-request-id":"06985ae7-cb6e-4894-a25d-02b638db3c0b","method":"GET","path":"/","host":"grafana.localhost.pomerium.io","query":"","ip":"172.31.0.1","session-id":"38dab363-cc2d-474d-a7c9-3a3a7560d430","allow":true,"allow-why-true":["domain-ok"],"deny":false,"deny-why-false":["valid-client-certificate-or-none-required"],"user":"google-oauth2|104583909997507305030","email":"srekuts@pomerium.com","time":"2023-08-09T17:03:29Z","message":"authorize check"}
grafana_core-grafana-1   | logger=context userId=0 orgId=0 uname= t=2023-08-09T17:03:29.569601649Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=172.31.0.1 time_ms=0 duration=487.182µs size=29 referer= handler=/

```
