### ISSUE TITLE
v0.23.0 seg faults on k8s

### ISSUE THREAD

**Issue by ThorbenJ** [pomerium/pomerium#4587]
## What happened?
Running v0.22.3 fine, upgrade to v0.23.0 and the pod seg faults

## What did you expect to happen?
Run without crashing

## How'd it happen?

1. Changed the version string in the resource path from v0.22.3 to v0.23.0

kustomization.yaml:
```
---
resources:
  - https://raw.githubusercontent.com/pomerium/ingress-controller/v0.22.3/deployment.yaml
patchesStrategicMerge:
  - external-dns.yaml
 ```
2. Ran kubectl apply -k . as usual
3. Saw the pod in a crashloop:
```
pod/pomerium-6ff6c85767-7kwcg               0/1     CrashLoopBackOff   2 (25s ago)   89s
```

## What's your environment like?

- GKE

## What's your Pomerium/Global

```
apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  name: global
spec:
  authenticate:
    url: https://xxxx
  certificates:
    - pomerium/xxx
  jwtClaimHeaders:
    X-Pomerium-Claim-Fullname: name
    X-Pomerium-Claim-Forename: given_name
    X-Pomerium-Claim-Surname: family_name
    X-Pomerium-Claim-EMail: email
    X-Pomerium-Claim-Groups: groups
  identityProvider:
    provider: okta
    secret: pomerium/xxx
    url: "xxx"
    requestParams:
      scope: "openid groups email profile"
  secrets: pomerium/bootstrap
```

## What did you see in the logs?

```
{"level":"info","ts":"2023-09-22T07:42:53Z","msg":"Starting workers","controller":"pomerium-ingress","controllerGroup":"networking.k8s.io","controllerKind":"Ingress","worker count":1}
{"level":"info","type":"type.googleapis.com/pomerium.config.Config","id":"pomerium-crd","time":"2023-09-22T07:42:53Z","message":"get"}
{"level":"info","type":"type.googleapis.com/pomerium.config.Config","id":"ingress-controller","time":"2023-09-22T07:42:53Z","message":"get"}
{"level":"info","type":"type.googleapis.com/pomerium.config.Config","time":"2023-09-22T07:42:53Z","message":"sync latest"}
{"level":"info","syncer_id":"databroker","syncer_type":"type.googleapis.com/pomerium.config.Config","time":"2023-09-22T07:42:53Z","message":"listening for updates"}
{"level":"info","server_version":1763779748159598214,"record_version":0,"time":"2023-09-22T07:42:53Z","message":"sync"}
{"level":"info","ts":"2023-09-22T07:42:53Z","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"pomerium-crd","controllerGroup":"ingress.pomerium.io","controllerKind":"Pomerium","Pomerium":{"name":"global"},"namespace":"","name":"global","reconcileID":"5fbbd715-1bf1-4cc4-8e23-9d671d38fa13"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x205ca33]

goroutine 757 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x2d7d540, 0x945cbe0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/pomerium/ingress-controller/pomerium.applyTimeouts({0x3b80b40?, 0xc001308810?}, 0xc001943140, 0xc001337b00?)
	/workspace/pomerium/config.go:84 +0xd3
github.com/pomerium/ingress-controller/pomerium.applyConfig({0x3b80b40, 0xc001308810}, 0xc001943140, 0xc001337b00)
	/workspace/pomerium/config.go:55 +0x434
github.com/pomerium/ingress-controller/pomerium.(*DataBrokerReconciler).SetConfig(0xc000b4bb90, {0x3b80b40, 0xc001308810}, 0x0?)
	/workspace/pomerium/sync.go:102 +0xb1
github.com/pomerium/ingress-controller/controllers/settings.(*settingsController).Reconcile(0xc001060a00, {0x3b80b40, 0xc0013087b0}, {{{0x0, 0x0}, {0xc0014096c0, 0x6}}})
	/workspace/controllers/settings/controller.go:145 +0x634
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x3b80b40?, {0x3b80b40?, 0xc0013087b0?}, {{{0x0?, 0x2c36b20?}, {0xc0014096c0?, 0x3b68360?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000e7d5e0, {0x3b80a98, 0xc000e87a90}, {0x2f15ba0?, 0xc000b9e520?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x377
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000e7d5e0, {0x3b80a98, 0xc000e87a90})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x587
```

## Additional context

Switching back to v0.22.3 in kustomization.yaml and everything works fine.
