### ISSUE TITLE
Route ordering/prioritization documentation

### ISSUE THREAD

**Issue by nareddyt** [pomerium/pomerium#4721]
I cannot find any documentation on how Pomerium decides which routes to match. If I have multiple routes that have overlapping definitions, which route config takes priority?

I did see [a note](https://www.pomerium.com/docs/reference/routes/from#wildcard-from-routes) about how wildcard routes take higher priority, but I can't find any similar docs for non-wildcard routes.

Example config:

```yaml
  # More specific rule, only matches /api
  - from: https://a.example.com:8080
    to: http://backend:8080
    prefix: /api
    allow_public_unauthenticated_access: true

  # General rule to catch any other paths (other than /api)
  - from: https://a.example.com:8080
    to: http://backend:8080
    policy: ...
```

In this case, are routes matched in the route definition order?
