### ISSUE TITLE
set_request_headers does not take effect when allow_public_unauthenticated_access enabled

### ISSUE THREAD

**Issue by ohdarling** [pomerium/pomerium#477]
## What happened?

UniFi Controller service will check Origin and Referer header for CORS protection (see https://community.ui.com/questions/Controller-v5-11-behind-reverse-proxy-gives-403-on-login/f98c3c5c-74c2-4cd5-80c1-24af498940aa
), and it has its own user authentication flow.
So I will set allow_public_unauthenticated_access to true, then set set_request_headers to

```
set_request_headers
  - Origin: https://unifi:8443
  - Refrer: https://unifi:8443
```

But Pomerium will ignore set_request_headers when enabled allow_public_unauthenticated_access, then visit unifi controller through Pomerium will always failed because CORS protection.

## What did you expect to happen?

Bypass CORS and login successfully

## What's your environment like?

pomerium/pomerium:latest on Docker

## What's your config.yaml?

Add policy like below:
```
policy:
  - from: https://unifi.example.com:8443
    to: https://unifi:8443
    set_request_headers:
      Origin: https://unifi:8443
      Refrer: https://unifi:8443
    allow_public_unauthenticated_access: true
    allow_websockets: true
    tls_skip_verify: true
```

## Additional context

I checked function reverseProxyHandler in proxy/proxy.go (https://github.com/pomerium/pomerium/blob/master/proxy/proxy.go#L223), if policy configured as public access, it will return directly, but set request header code was behind it.

https://github.com/pomerium/pomerium/blob/master/proxy/proxy.go#L263

Please confirm that is it by design or is it a bug should be fixed, thanks :)
