### ISSUE TITLE
robots.txt Disallow / for public routes

### ISSUE THREAD

**Issue by stuba** [pomerium/pomerium#4912]
**robots.txt is always responding with content that disallows crawling.**

I was blaming framework for this, but now it seems that Pomerium replies to all robots.txt requests automatically. I did read that during 0.11 there should have been fix for this https://github.com/pomerium/pomerium/pull/1361. 

**When public domain robots.txt should get passed to backend service.**

**Setup rules in pomerium config**

**No other use cases**

If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Here is my config for this route**
```
  - name: Default route
    from: https://my_service.url
    to: http://nginx
    preserve_host_header: true
    policy:
      allow:
        and:
          - accept: true

```

**Comment by kenjenkins** [comment]
Hi @stuba,

It looks like currently the logic from https://github.com/pomerium/pomerium/pull/1361 is based on the [allow_public_unauthenticated_access](https://www.pomerium.com/docs/reference/routes/public-access) option. Please try updating your route configuration to set `allow_public_unauthenticated_access` instead of `policy`, something like this:
```yaml
  - name: Default route
    from: https://my_service.url
    to: http://nginx
    preserve_host_header: true
    allow_public_unauthenticated_access: true
```

**Comment by stuba** [comment]
Surely this works. I do not know why I had understood this allow_public_unauthenticated_access is all ready deprecated in flavour of new policy. Thank you for clarifying this!

**Comment by calebdoxsey** [comment]
I agree we should update the logic to also work with PPL.

**Comment by kenjenkins** [comment]
Per Caleb: we could refactor this logic to move it to the authorizer service-- if we get a request for /robots.txt and the request is not authorized, we could directly return the "disallow" response. (This should avoid some of the complication of recognizing equivalent PPL policies.)

**Comment by calebdoxsey** [comment]
The logic around robots.txt handling has been updated to happen in the authorize service so that any policy that allows access without requiring a login should behave the same.

The example route:

```
 - name: Default route
    from: https://my_service.url
    to: http://nginx
    preserve_host_header: true
    policy:
      allow:
        and:
          - accept: true
```

Should forward requests to the backend. Whereas a route with an authorization policy should return 

```
User-agent: *
Disallow: /
```
