### ISSUE TITLE
core/config: support direct response

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/pomerium#4954]
**Is your feature request related to a problem? Please describe.**

Sometimes a route needs a small, static response. For example the process for domain validation is to return a well-defined response at `/.well-known/acme-challenge/` or `/.well-known/pki-validation/`. Currently to support this a user would have to start a backend HTTP server and then configure a route with a `to` that points to it.

**Describe the solution you'd like**

In addition to a `to` URL or a `redirect` action we should support a direct, hardcoded response:

```yaml
routes:
- from: https://example.com
  response:
    status: 200
    body: "text"
```

The content type could be set with the existing `set_response_headers` option.

**Describe alternatives you've considered**

We could support a direct response via a `to` data URL:

```yaml
routes:
- from: https://example.com
  to: data:text/plain;base64,SGVsbG8sIFdvcmxkIQ==
```
