### ISSUE TITLE
Policy processing - conditional behaviour

### ISSUE THREAD

**Issue by samcgarry** [pomerium/pomerium#502]
**Is your feature request related to a problem? Please describe.**

This is more of a question than a feature request. I'm curious whether the policy processing can be configured to provide conditional routing? 

For example:
```
policy:
  - from: https://dashboard.example.com
    to: http://admin.example.com
 allowed_groups:
      - admins
  - from: https://dashboard.example.com
    to: http://dashboard.example.com
    allowed_groups:
    - users
```

So what happens if the policy contains the same from address in to policy definitions? Do they 'fall through' to the next one, or does pomerium reject if the user doesn't belong to the admin group?
Could pomerium be used in this way to route to different endpoints based on users' group membership?
