### ISSUE TITLE
Supporting non-standard ports

### ISSUE THREAD

**Issue by venkatamutyala** [pomerium/pomerium#5038]
**Is your feature request related to a problem? Please describe.**

Yes.

A clear and concise description of what the problem is. 

It seems like pomerium can only support standard ports 80 and 443. If i do example.com:8443 it'll give me a 404.

**Describe the solution you'd like**

I'd like to be able to specify 8443 or another non-standard port

**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**

I'd like to keep port 80/443 for apps that use ingress-nginx ingress controller and i'd like to avoid having to get a second ipv4 address just to use pomerium

**Additional context**
N/A

**Comment by calebdoxsey** [comment]
@venkatamutyala you can have Pomerium listen on a different port using the [`address`](https://www.pomerium.com/docs/reference/address) option. Does this fix your issue?

**Comment by venkatamutyala** [comment]
Thanks @calebdoxsey. It looks like it's not customizable in kubernetes. Is that accurate? I'm using your customize deployment method currently. Do i just need to shove that environment variable into the container some how?

**Comment by calebdoxsey** [comment]
Hi @venkatamutyala 

I think you can adjust the LoadBalancer service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: pomerium-proxy
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    - name: http
      targetPort: http
      protocol: TCP
      port: 80
```

Changing `443` to `8443` would mean incoming URLs would come on `example.com:8443` and then the route should match.
