### ISSUE TITLE
Verify application: Identity verification failed due to not connecting to custom port

### ISSUE THREAD

**Issue by fduran** [pomerium/pomerium#5199]
## What happened?

I'm running the "verify" container on a custom (not :443) port :7899. It properly authenticates me at `https://verify.<domain>.pomerium.app:7899/` but after about 5 seconds it shows the message:

```
Identity verification failed
We tried to verify the incoming user, but failed with the following error: failed to retrieve signature key for Pomerium JWT assertion: Get "https://verify.<domain>.pomerium.app/.well-known/pomerium/jwks.json": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

If I add my port to that URL `https://verify.<domain>.pomerium.app:7899/.well-known/pomerium/jwks.json` , I can connect and see the json, so it looks like upon the ~5 s refresh time it loses the custom port value and fails the connection.

## docker-compose.yml

```
services:
  pomerium:
    image: pomerium/pomerium:v0.26.1
    ports:
      - 7899:7899
    restart: always
    environment:
      POMERIUM_ZERO_TOKEN: AMf-...
      XDG_CACHE_HOME: /var/cache
    volumes:
      - pomerium-cache:/var/cache
    networks:
      main:
        aliases:
        - verify.<domain>.pomerium.app
  verify:
    image: cr.pomerium.com/pomerium/verify:latest
    networks:
      main:
        aliases:
        - verify

networks:
  main: {}

volumes:
  pomerium-cache:
```
