### ISSUE TITLE
feature: support TLS termination for upstream insecure GRPC servers

### ISSUE THREAD

**Issue by kralicky** [pomerium/pomerium#5213]
**Is your feature request related to a problem? Please describe.**

Currently, there is no way to put Pomerium in front of an insecure GRPC server expecting TLS to be terminated by Envoy. This is because envoy uses ALPN to negotiate protocols with upstream services, but ALPN is a TLS extension. Insecure GRPC servers use the h2c protocol and cannot handle ALPN, but still require clients to use http/2. Therefore, clients are required to have so-called "prior knowledge" that the server expects http/2 and cannot negotiate an upgrade from http/1. 

Envoy supports this automatically as long as we enable http/2 for the relevant clusters. However, there is no way to configure a Pomerium route for both TLS termination _and_ http/2 support (at least, for routes defined in the configuration file - some of the internal routes are set up in this way already)

**Describe the solution you'd like**

I would like to be able to use the scheme `h2c`, as Traefik does, to support this use case. For example:

```yaml
routes:
  - from: https://grpc.localhost.pomerium.io
    to: h2c://localhost:9090
```

If all URLs in the `to` section use the `h2c` scheme, Envoy will connect to the upstream server without TLS but always over http/2, never http/1. 

**Describe alternatives you've considered**

Alternatively, we could allow explicitly controlling the upstream protocol for each route with a separate option, for example:

```yaml
routes:
  - from: https://grpc.localhost.pomerium.io
    to: http://localhost:9090
    upstream_protocol: h2c
```

This does not seem to have any clear advantages, and would require new configuration. However, such an option could be necessary if/when we support QUIC in the future.
