### ISSUE TITLE
ppl: more flexible matchers

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/pomerium#5335]
**Is your feature request related to a problem? Please describe.**

Currently some PPL criteria match a value directly, like `claim`:

```yaml
- allow:
    and:
      - claim/family_name: Smith
```

Whereas other PPL criteria use a `string matcher` or a `string list matcher`:

```yaml
- allow:
    or:
      - domain:
          is: domain1.com
```

```yaml
allow:
  and:
    - groups:
        has: '00gv40ki4gmtCyl5d4x6'
```

Sometimes users are confused by these differences and end up using a string matcher where they should be using a value directly, or vice-versa.

**Describe the solution you'd like**

With some small changes we can ease this:

1. For a `string matcher`, in addition to the existing options, we can support using a string instead of an object, and if this is done, it will be the same as `is`:

  ```yaml
  domain: domain1.com
  # same as
  domain:
    is: domain1.com  
  ```

2. For a `string list matcher`, in addition to the existing `has` operator, we can support an `is` operator which does the same thing as `has`, and like with the `string matcher`, support using a string, which would be the equivalent of has:

  ```yaml
  groups: '00gv40ki4gmtCyl5d4x6'
  # same as 
  groups:
    is: '00gv40ki4gmtCyl5d4x6'
  # same as 
  groups:
    has: '00gv40ki4gmtCyl5d4x6'
  ```

3. Convert the `claim` criterion to use a `string list matcher`.
