### ISSUE TITLE
Allow local IP to skip authentication

### ISSUE THREAD

**Issue by carmatana** [pomerium/pomerium#5410]
Hello,

I am a home user, using synology-docker with pomerium to access my docker containers and NAS  when out of home.

When in home I access my docker containers through: "192.168.1.150:port" with no more authentication than the container's, if any.

When abroad: "conatiner1.mydomain.com" and I authenticate myself using okta

Everything works great !

How can I use ""conatiner1.mydomain.com" when in home and skip authentication ?

Is it possible ?

The above explanations are beyond my understanding.

For each container I have something like the following in my policy

- from: https://n8n.XXX.synology.me
  to: http://172.17.0.1:5678
  allowed_users:
    - cxxxxxxx@gmail.com
    - dxxxxxxx@gmail.com 

Thank you very much.

_Originally posted by @carmatana in https://github.com/pomerium/pomerium/issues/1943#issuecomment-2565994516_
 
I think that an alternative could be to authenticate using my fingerprint, so I will have to authenticate with okta only when using a different pc/phone, but no idea how to implement it.

**Comment by kenjenkins** [comment]
Hi @carmatana, the next version of Pomerium (v0.31) adds support for a `source_ip` PPL criterion. If I understand correctly, I think a policy like this would satisfy your use case:

```yaml
 - from: https://n8n.xxx.synology.me/
   to: http://172.17.0.1:5678/
   policy:
     allow:
       or:
         - email:
             is: cxxxxxxx@gmail.com
         - email:
             is: dxxxxxxx@gmail.com
         - source_ip: 192.168.1.0/24  # <- put your trusted IP range here
```

With this policy, requests from an IP address in the range 192.168.1.0 – 192.168.1.255 would be allowed outright, without any login required.
