### ISSUE TITLE
policy routing by path instead of subdomain

### ISSUE THREAD

**Issue by mkohns** [pomerium/pomerium#547]
**This is a question, no bug or feature requests**

Subdomain routing like

```
  - from: https://httpbin.example.com
    to: http://httpbin
    allowed_groups:
     - super_admin
```
works great! 

What about a feature to use paths instead of subdomains?

```
  - from: https://www.example.com/httpbin
    to: http://httpbin
    allowed_groups:
     - super_admin
```
This use-case is often used to make multiple containers/microservices available under one common name.
I tested this but did not work out of the box. Am I missing some syntax or configuration?
