### ISSUE TITLE
Redirect Loop in Pomerium w/Traefik v2 and ForwardAuth.

### ISSUE THREAD

**Issue by ekarlso** [pomerium/pomerium#549]
## What did you expect to happen?
Success login from IDP from ForwardAuth

## How'd it happen?
Went to url behind Traevik V2 with ForwardAuth Middleware enabled
Redirect loop happened in Browser (You have the HAR log)

1. Ran `x`
2. Clicked `y`
3. Saw error `z`

## What's your environment like?
Kubernetes 1.15.5
Azure AD App Reg
Traefik V2 2.1 w/Forward Auth
Pomerium 6.0.2

## Traefik V2 helm config
``` 
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik-v2
  namespace: kube-system
spec:
  releaseName: traefik-v2
  chart:
    repository: https://containous.github.io/traefik-helm-chart
    version: "5.6.0"
    name: traefik
  values:
    service:
      spec:
        loadBalancerIP: "x"
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-resource-group: rg-x-prod
    additionalArguments:
      - "--providers.kubernetesingress=true"
      - "--serverstransport.insecureskipverify=true"
      - --entryPoints.metrics.address=:8082
      - --metrics.prometheus.entryPoint=metrics
      - --metrics.prometheus=true
```

## AlertManager IngressRoute & MiddleWare
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-forward
  namespace: monitoring
spec:
  forwardAuth:
    address: https://forwardauth.x.cloud/?uri=https://alertmanager.x.cloud
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alarmmanager
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`alertmanager.x.cloud`)
      kind: Rule
      services:
      - name: alertmanager-operated
        port: 9093
      middlewares:
      - name: auth-forward
        namespace: monitoring
  tls:
    secretName: alertmanager-tls
```

## What's your config.yaml?
metrics_address: :9090
forward_auth_url: https://forwardauth.x.cloud
policy:
      
  - from: https://alertmanager.x.cloud
    to: http://alertmanager-operated:9093

## What did you see in the logs?
Logs provided in Gist.
