### ISSUE TITLE
redirection problem

### ISSUE THREAD

**Issue by tirelibirefe** [pomerium/pomerium#5497]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Explain any additional use-cases**

If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by tirelibirefe** [comment]
Nobody has any idea. Pls advise...
If I cannot find a solution, I will have to replace pomerium or istio with something else.

**Comment by nickytonline** [comment]
Hi @tirelibirefe!

Thanks for opening an issue. One thing that stands out in your configuration is that you have `- public: true` set for the routes in your loop. Because they're set to public it won't cause a redirect to login. Try removing that line.

**Comment by tirelibirefe** [comment]
Hello @nickytonline thank you for answer.
I put it there to check the result temporary; I removed it; nothing changed; the current config below:

```
config:
  rootDomain: "${var.domain_name}"
  cookieSecret: "${local.pomerium.cookie_secret_base64}"
  databroker:
    storage:
      connectionString: "redis://redis-master.${var.redis_namespace}.svc.cluster.local:6379" 
  routes:
%{for app, details in var.apps~}
    - from: "https://${details.subdomain}.${var.domain_name}"
      to: "http://${details.destination_service}.${details.namespace}.svc.cluster.local:${details.port}"
      policy:
      - allow:
          or:
          - claim:
              groups: "${details.group}"
          - claim:
              email: "lvcleef@opscode.pro"
      pass_identity_headers: true
      preserve_host_header: true
%{endfor~}

authenticate:
  idp:
    provider: "oidc"
    clientID: "${local.pomerium["name"]}"
    clientSecret: "${random_string.clientsecret.result}"
    url: "https://${var.keycloak_subdomain}.${var.domain_name}/realms/${var.realm_name}"
    scopes: "openid email profile roles"
proxy:
  deployment:
    podAnnotations:
      traffic.sidecar.istio.io/excludeInboundPorts: '80,443' # allow external connections to terminate directly on the Pomerium proxy rather than the sidecar
    authenticateServiceUrl: https://${local.pomerium_vs["subdomain"]}.${var.domain_name}
service:
  authorize:
    headless: false # send traffic to the Pomerium Authorize through the Istio service rather than to individual pods
  databroker:
    headless: false # send traffic to the Pomerium Databroker through the Istio service rather than to individual pods
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
redis:
  enabled: false
  auth:
    existingSecret: "redis"
    existingSecretPasswordKey: "redis-password"
    createSecret: true
  generateTLS: true
  forceGenerateTLS: false
  replica:
    replicaCount: 1
extraEnv:
  JWT_CLAIMS_HEADERS: email
```
