### ISSUE TITLE
Kubernetes trace settings timeout not set properly

### ISSUE THREAD

**Issue by nareddyt** [pomerium/pomerium#5652]
## Setup

Follow the kubernetes CR configuration for tracing in https://www.pomerium.com/docs/reference/tracing

```
apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  name: example
spec:
  ...
  otel:
    endpoint: http://jaeger-collector:4317
    protocol: grpc
    headers:
      key: value
    timeout: 10s
    sampling: 1.0
    resourceAttributes:
      key: value
    bspScheduleDelay: 5s
    bspMaxExportBatchSize: 512
    logLevel: info
```

## Problem

The `timeout` field is not propagated to the Envoy configuration properly.

In the `tracing` section of the Envoy configuration, we see the following:

```
"grpc_service": {
  "envoy_grpc": {
    "cluster_name": "pomerium-control-plane-grpc"
  },
"timeout": "10000000s"
},
```

## Workaround

Change the format of the timeout in the CR to:

```
    timeout: "10000ns"
```

Somehow, this sets the originally intended timeout in the tracing config 😕 

```
"grpc_service": {
  "envoy_grpc": {
    "cluster_name": "pomerium-control-plane-grpc"
  },
"timeout": "10s"
},
```
