### ISSUE TITLE
Feature request: Model Context Protocol (MCP) Support

### ISSUE THREAD

**Issue by wasaga** [pomerium/pomerium#5672]
# Feature Request: Model Context Protocol (MCP) Support in Pomerium

## Summary

Request to add first-class support for the [Model Context Protocol (MCP)](https://modelcontextprotocol.io/) in Pomerium, enabling secure, policy-driven access to internal MCP servers and tools for AI agents and applications.

## Background

MCP is an open standard that allows AI agents and LLM-powered applications to securely connect to internal data sources and tools via standardized interfaces. Integrating MCP support into Pomerium would allow organizations to safely expose internal APIs, databases, and services to external AI clients (e.g., Claude, OpenAI, custom apps) while maintaining strict authentication and authorization controls.

## Use Cases

- Securely expose internal MCP servers to external AI clients via Pomerium as a gateway
- Handle upstream OAuth flows and token management for MCP servers that require third-party authentication (e.g., GitHub, Google Drive, Notion)
- Provide external tokens to internal applications for calling MCP servers through LLM APIs
- Apply fine-grained, policy-based access control to individual MCP tools and methods

## Key Requirements

- **MCP Route Support:** Add MCP configuration options for routes
- **OAuth Integration:** Support upstream OAuth2 flows for MCP servers, including token refresh and secure credential handling
- **Token Management:** Issue external tokens for AI clients and manage internal tokens for upstream authentication
- **Policy Enforcement:** Enable fine-grained access control using Pomerium Policy Language (PPL), including the `mcp_tool` criterion for tool-level authorization
- **Observability:** Log MCP method/tool calls and parameters for auditing and monitoring
- **API Endpoints:** Expose endpoints for listing available MCP servers and initiating OAuth flows

## Example Configuration

```yaml
routes:
  - from: https://my-mcp-server.your-domain.com
    to: http://my-mcp-server.int:8080/mcp
    name: My MCP Server
    mcp:
      server: {}
    policy: {}
  - from: https://mcp-app-demo.your-domain.com
    to: http://mcp-app-demo:3000
    mcp:
      client: {}
    policy: {}
```

## Benefits

- Secure, auditable access to internal tools for AI agents
- Centralized authentication and authorization for all MCP endpoints
- Seamless integration with upstream OAuth providers
- Fine-grained policy controls for tool-level access
- Improved observability of AI agent activity
