### ISSUE TITLE
Bug: authorize_log_fields not always respected in authz logs for denied requests

### ISSUE THREAD

**Issue by nickytonline** [pomerium/pomerium#5673]
## What happened?

Fields listed in `authorize_log_fields` (specifically mcp-method, mcp-tool, and mcp-tool-parameters) are missing in denied authorization log entries, even though they're present for successful ones.

## What did you expect to happen?

Expected all fields listed in authorize_log_fields to be present in every authorize log entry, regardless of whether the request was allowed or denied.

## How'd it happen?

- Defined custom authorize_log_fields including MCP-relevant fields.
- Ran Pomerium built from latest main.
- Observed that denied requests were missing expected fields in the logs.

## What's your environment like?

Pomerium version (main branch as of 2025-06-25)

Server Operating System/Architecture/Cloud: Docker on DigitalOcean Ubuntu 22.04 x86_64

## What's your config.yaml?

```yaml
root@pomerium-et-all:~/pomdemo# cat config.yaml
databroker_storage_type: postgres
databroker_storage_connection_string: postgres://postgres:postgres@postgres:5432/pomerium?sslmode=disable

authenticate_service_url: ${AUTHENTICATE_SERVICE_URL}
idp_provider: ${IDP_PROVIDER}
idp_provider_url: ${IDP_PROVIDER_URL}
idp_client_id: ${IDP_CLIENT_ID}
idp_client_secret: ${IDP_CLIENT_SECRET}

cookie_domain: demo.maisonlab.dev

address: :443

runtime_flags:
  mcp: true

autocert: true

# OTEL config
# https://docs.pomerium.com/docs/reference/tracing#config-file
# running in enterprise console? go to settings/tracing, set type to otlp and
# otel_exporter_otlp_endpoint: http://jaeger:4317
otel_exporter_otlp_traces_endpoint: http://jaeger:4317
otel_exporter_otlp_protocol: grpc
otel_traces_exporter: otlp

# for MCP observability
authorize_log_fields:
  - request-id
  - user
  - email
  - mcp-method
  - mcp-tool
  - mcp-tool-parameters
  - host
routes:
  - from: https://dev.demo.maisonlab.dev
    to: http://mcp-demo-app:5173
    name: App Demo
    timeout: 60s
    mcp:
      client: {}
    policy:
      allow:
        or:
          - domain:
              is: pomerium.com
          - domain:
              is: nickyt.co

  - from: https://app.demo.maisonlab.dev
    to: https://lvchfqkw-5173.use.devtunnels.ms
    name: App Demo
    timeout: 60s
    mcp:
      client: {}
    policy:
      allow:
        or:
          - domain:
              is: pomerium.com
          - domain:
              is: nickyt.co

  - from: https://jaeger.demo.maisonlab.dev
    to: http://jaeger:16686/
    name: jaeger
    pass_identity_headers: true
    policy:
      allow:
        or:
          - domain:
              is: pomerium.com
          - domain:
              is: nickyt.co

  - from: https://verify.demo.maisonlab.dev
    to: http://verify:8000
    name: verify
    pass_identity_headers: true
    policy:
      allow:
        or:
          - domain:
              is: pomerium.com
          - domain:
              is: nickyt.co

  - from: https://northwind.demo.maisonlab.dev
    to: http://mcp-sqlite:8080/mcp
    name: Northwind
    mcp:
      server: {}
    policy:
      allow:
        or:
          - domain:
              is: pomerium.com
          - domain:
              is: nickyt.co
      deny:
        or:                                         
          - mcp_tool:                                                                        
              is: read_query
```

## What did you see in the logs?

Successful request log:

```json
{
  "level": "info",
  "service": "authorize",
  "request-id": "e04e8e28-a695-9176-82cd-88c4ba0f0ce1",
  "user": "google-oauth2|110679203791094235151",
  "email": "ntaylor@pomerium.com",
  "mcp-method": "tools/call",
  "mcp-tool": "read_query",
  "mcp-tool-parameters": { "query": "SELECT ..." },
  "host": "northwind.demo.maisonlab.dev",
  "allow": true,
  "deny": false
}
```

Denied request log:

```json
{
  "level": "info",
  "service": "authorize",
  "request-id": "b45d6258-14b4-9941-b9b9-ddcf18b0495f",
  "user": "google-oauth2|110679203791094235151",
  "email": "ntaylor@pomerium.com",
  "host": "northwind.demo.maisonlab.dev",
  "allow": true,
  "deny": false,
  "deny-why-false": ["mcp-tool-unauthorized"]
}
```

## Additional context

This was working earlier in the day (before latest main pull). Might be a regression?

**Comment by wasaga** [comment]
Policy: 

```yaml
policy:
  allow:
    and:
      - email: 
          in: ["xxxxx@pomerium.com"]
      - mcp_tool:
          in: ["describe_table", "read_query"]
```

produces
```json
{
  "level": "info",
  "server-name": "all",
  "service": "authorize",
  "mcp-method": "tools/call",
  "mcp-tool": "list_tables",
  "mcp-tool-parameters": {},
  "request-id": "383a282d-d039-9a6e-8ff5-6479e98bc582",
  "allow": false,
  "allow-why-false": ["mcp-tool-unauthorized"],
  "deny": false,
  "deny-why-false": [],
  "time": "2025-07-04T12:16:14-04:00",
  "message": "authorize check"
}
```

the policy from this ticket with denial 
```yaml
policy:
  allow:
    and:
      - email: 
          in: ["dmishin@pomerium.com"]
  deny:
    or:
      - mcp_tool:
          in: ["list_tables"]
```

would yield 
```json
{
  "level": "info",
  "server-name": "all",
  "service": "authorize",
  "mcp-method": "tools/call",
  "mcp-tool": "list_tables",
  "mcp-tool-parameters": {},
  "request-id": "7b9431c5-fe50-9d9c-b749-362cd2401833",
  "allow": true,
  "allow-why-true": ["email-ok"],
  "deny": true,
  "deny-why-true": ["mcp-tool-ok"],
  "time": "2025-07-04T12:20:23-04:00",
  "message": "authorize check"
}
```

and the `mcp-method`, `mcp-tool`, `mcp-tool-parameters` are present in the authorize log output. 

what i do find odd is the `"deny-why-true": ["mcp-tool-ok"]` so I would probably change that to match result `mcp-tool-match`, and `mcp-tool-no-match`.
