### ISSUE TITLE
Hot Reload Not Working for config.yaml During Local Development

### ISSUE THREAD

**Issue by nickytonline** [pomerium/pomerium#5674]
## What happened?

While developing locally with Docker Compose, I updated my Pomerium policy/config (e.g., route or access control) and expected the change to take effect immediately. However, the change was not reflected until I manually restarted the Pomerium container.

## What did you expect to happen?

I expected Pomerium to automatically detect the change in `config.yaml` and reload the configuration without requiring a container restart.

## How'd it happen?

1. Ran `docker compose up`
2. Edited `config.yaml` to change a route policy
3. Refreshed the page and saw no change
4. Restarted the container manually
5. Verified that the config changes were now applied

## What's your environment like?

- Pomerium version (main branch Docker image as of 2025-06-25)
- Server Operating System/Architecture/Cloud: 2 GB Memory / 25 GB Disk / TOR1 - Ubuntu 24.10 x64 Digital Ocean droplet

## What's your config.yaml?

```yaml
databroker_storage_type: postgres
databroker_storage_connection_string: postgres://postgres:postgres@postgres:5432/pomerium?sslmode=disable

authenticate_service_url: ${AUTHENTICATE_SERVICE_URL}
idp_provider: ${IDP_PROVIDER}
idp_provider_url: ${IDP_PROVIDER_URL}
idp_client_id: ${IDP_CLIENT_ID}
idp_client_secret: ${IDP_CLIENT_SECRET}

cookie_domain: demo.maisonlab.dev

address: :443

runtime_flags:
  mcp: true

autocert: true

# OTEL config
# https://docs.pomerium.com/docs/reference/tracing#config-file
# running in enterprise console? go to settings/tracing, set type to otlp and
# otel_exporter_otlp_endpoint: http://jaeger:4317
otel_exporter_otlp_traces_endpoint: http://jaeger:4317
otel_exporter_otlp_protocol: grpc
otel_traces_exporter: otlp

# for MCP observability
authorize_log_fields:
  - request-id
  - user
  - email
  - mcp-method
  - mcp-tool
  - mcp-tool-parameters
  - host
routes:
  - from: https://dev.demo.maisonlab.dev
    to: http://mcp-demo-app:5173
    name: App Demo
    timeout: 60s
    mcp:
      client: {}
    policy:
      allow:
        or:
          - domain:
              is: pomerium.com
          - domain:
              is: nickyt.co

  - from: https://app.demo.maisonlab.dev
    to: https://lvchfqkw-5173.use.devtunnels.ms
    name: App Demo
    timeout: 60s
    mcp:
      client: {}
    policy:
      allow:
        or:
          - domain:
              is: pomerium.com
          - domain:
              is: nickyt.co

  - from: https://jaeger.demo.maisonlab.dev
    to: http://jaeger:16686/
    name: jaeger
    pass_identity_headers: true
    policy:
      allow:
        or:
          - domain:
              is: pomerium.com
          - domain:
              is: nickyt.co

  - from: https://verify.demo.maisonlab.dev
    to: http://verify:8000
    name: verify
    pass_identity_headers: true
    policy:
      allow:
        or:
          - domain:
              is: pomerium.com
          - domain:
              is: nickyt.co

  - from: https://northwind.demo.maisonlab.dev
    to: http://mcp-sqlite:8080/mcp
    name: Northwind
    mcp:
      server: {}
    policy:
      allow:
        or:
          - domain:
              is: pomerium.com
          - domain:
              is: nickyt.co

```

compose.yml

```
services:
  postgres:
    image: postgres:17
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - pom-network

  pomerium:
    image: pomerium/pomerium:main
    env_file:
      - .env
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config.yaml:/pomerium/config.yaml
      - ./pomerium-autocert:/data/autocert
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "mcp-demo-app:159.203.24.86"
    networks:
      - pom-network

  verify:
    image: pomerium/verify:latest
    expose:
      - 8000
    networks:
      - pom-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_GRPC_ENABLED=true
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:16686 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pom-network

  mcp-sqlite:
    build:
      context: db-mcp
      dockerfile: Dockerfile
    volumes:
      - ./db-mcp/northwind.db:/northwind.db
    environment:
      PORT: 8080
      DB_FILE: /northwind.db
      BASE_URL: https://northwind.demo.maisonlab.dev
    expose:
      - 8080
    networks:
      - pom-network

volumes:
  postgres-data:
  pomerium-autocert:
  langflow-data:
  wait-for-it:                                                                                                                                          networks:                                                                     pom-network:
    name: pom-network
```
