### ISSUE TITLE
trace not getting captured in jaeger-all-in-one 

### ISSUE THREAD

**Issue by RaghavendraP** [pomerium/pomerium#579]
## What happened?
Configured jaeger trace for a jaeger instance running through all-in-one docker. But not trace spans are getting captured in it. 
## What did you expect to happen?
Able to see spans for each request
## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint):
0.6.3
- Server Operating System/Architecture/Cloud:
Ubuntu 18.04

## What's your config.yaml?
```config.yaml
authenticate_service_url: 

# identity provider settings : https://www.pomerium.io/docs/identity-providers.html
idp_provider: "azure"
idp_provider_url: 
idp_client_id: 
idp_client_secret: 

shared_secret: 
cookie_secret: 
certificate_file: "./cert.pem"
certificate_key_file: "./key.pem"
#log_level: info
tracing_provider: jaeger
tracing_jaeger_collector_endpoint: "http://<jaeger-docker-host>:14268/api/traces"
tracing_jaeger_agent_endpoint: "<jaeger-docker-host>:6831"
policy:
  - from: https://
    to: http://
    allowed_domains:
            - 
    allowed_groups:
            - 
    set_request_headers:
            X-Forwarded-Proto: "https"
```

jaegar-all-in-one docker-compose:
version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
        - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "5775:5775/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - jaeger-example
networks:
  jaeger-example:

**Comment by desimone** [comment]
Could be a configuration issue would be my guess. Your pomerium configuration looks correct.

Here's a configuration I'm using that works. 

```yaml
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    restart: always
```
