### ISSUE TITLE
Enhanced routing capabilites

### ISSUE THREAD

**Issue by sylr** [pomerium/pomerium#591]
**Is your feature request related to a problem? Please describe.**

Pomerium policies are currently `hostname` based only. It would be really helpful if we could define policies based on several other properties such as HTTP method, path ... etc.

**Describe the solution you'd like**

[Traefik](https://github.com/containous/traefik) implements a syntax based on [vulcand/predicate](https://github.com/vulcand/predicate) which allows to describe [rules](https://docs.traefik.io/routing/routers/#rule) that will be matched against incoming requests. If pomerium could have something similar it would allow us to use pomerium to authorize specific endpoints to a subsets of groups or users.

A pomerium policy using traefik rule language would look like this:

```yaml
policy:
- rule: 
    expression: "Host(`myapp.domain.com`) && Method(`POST`) && PathPrefix(`/api`)"
    # if not defined priority defaults to the length of the expression string
    priority: 1000
  to: http://myapp.namespace.svc.cluster.local
  allowed_domains:
  - company.com
  allowed_groups:
  - admins
  - moderators
- rule: 
    expression: "Host(`myapp.domain.com`)"
    priority: 1
  to: http://myapp.namespace.svc.cluster.local
  allowed_domains:
  - company.com
  allowed_groups:
  - employees
```
 
**Describe alternatives you've considered**

I currently have a nginx between pomerium and my application which does something similar but it is not going to work starting with v0.7.0 as the `x-pomerium-authenticated-user-groups` header has been removed.

```
location /api/ {
            if ($request_method != POST) {
                break;
            }
            set $trusted 0;
            if ($http_x_pomerium_authenticated_user_groups ~ ".*(admins|moderator).*") {
                set $trusted 1;
            }
            if ($trusted = 0) {
                return 403;
            }
            ...
}
```

**Additional context**

https://github.com/containous/traefik/blob/v2.2.0/pkg/rules/rules.go
https://github.com/vulcand/route
