### ISSUE TITLE
Proposal: Gather Config from Docker Labels

### ISSUE THREAD

**Issue by branchmispredictor** [pomerium/pomerium#603]
**Is your feature request related to a problem? Please describe.**

I've been thinking more about how to better integrate Pomerium with Traefik (and Docker in general). To me, I see Traefik as a highly extensible reverse proxy (with ACME) and Pomerium as the AuthZ/AuthN server that can secure it. 

With the right integration, I think it should be able to solve #591 and #580 without introducing complex routing logic into Pomerium itself. Perhaps this is against the intentions of the maintainers though.

In any case, part of this work might be to be able to pull policy config from docker labels. 

**Describe the solution you'd like**

Derive config from docker labels. One possibility might be:

```yaml
  httpbin:
    image: kennethreitz/httpbin:latest
    labels:
      - "traefik.http.middlewares.pomerium.forwardauth.authResponseHeaders=x-pomerium-jwt-assertion"
      - "traefik.http.middlewares.pomerium.forwardauth.address=https://fwdauth.x.y.z/"

      - "traefik.http.routers.httpbin.middlewares=pomerium@docker"
      - "traefik.enable=true"
      - "traefik.http.routers.httpbin.rule=Host(`httpbin.x.y.z`)"
      - "traefik.http.routers.httpbin.entrypoints=websecure"
      - "traefik.http.routers.httpbin.tls.certresolver=leresolver"
      
      - "pomerium.policy.httpbin.from=https://httpbin.x.y.z"
      #- "pomerium.policy.httpbin.to=http://httpbin.localhost" # not needed in this case
      - "pomerium.policy.httpbin.allowed_domains=[`pomerium.io`,`gmail.com`]"
```

**Describe alternatives you've considered**

Maintaining two configs: one in docker-compose and one in Pomerium's config.yaml.
