### ISSUE TITLE
Document Traefik tuning for forward auth

### ISSUE THREAD

**Issue by sylr** [pomerium/pomerium#616]
If your are using Traefik to proxy requests to the pomerium proxy acting as forward auth component, then, it is required to configure traefik so that it allows "X-Fowarded-*" headers.

See https://docs.traefik.io/v2.0/routing/entrypoints/#forwarded-header

**Comment by branchmispredictor** [comment]
Are you sure that is the case?

I have been getting by with the following config for forward auth behind traefik 2 without any special config for forwarded headers. Using either the `forwardedHeaders.insecure` or `forwardauth.trustForwardHeader` setting should be discouraged and certainly not required from my understanding.

**Comment by branchmispredictor** [comment]
One final thing you could do is route your forward auth locally instead of externally. These are snippets from some local testing of this approach:

`docker-compose.yaml`:
```yaml
    httpbin:
        image: "kennethreitz/httpbin"
        labels:
            - "traefik.http.middlewares.pomerium.forwardauth.authResponseHeaders=x-pomerium-jwt-assertion"
            - "traefik.http.middlewares.pomerium.forwardauth.address=http://fwdauth:80"
            - "traefik.http.routers.httpbin.middlewares=pomerium@docker"
            - "traefik.enable=true"
            - "traefik.http.routers.httpbin.rule=Host(`httpbin.corp`)"
            - "traefik.http.routers.httpbin.entrypoints=websecure"
            - "traefik.http.routers.httpbin.tls.certresolver=myresolver"

    pomerium:
        image: pomerium/pomerium:master
        networks:
            default:
                aliases:
                    - fwdauth
        volumes:
            - ./config/pomerium/config.yaml:/pomerium/config.yaml:ro
        labels:
            - "traefik.http.services.pomerium.loadbalancer.server.port=80"
            - "traefik.enable=true"
            - "traefik.http.routers.pomerium.rule=Host(`authenticate.corp`)"
            - "traefik.http.routers.pomerium.entrypoints=websecure"
            - "traefik.http.routers.pomerium.tls.certresolver=myresolver"
```

config.yaml:
```yaml
address: :80
forward_auth_url: http://fwdauth:80
authenticate_service_url: https://authenticate.corp

policy:
    - from: https://httpbin.corp
      to: http://httpbin.localhost
      allowed_users:
          - myemail@gmail.com
```
