### ISSUE TITLE
Ping Identity provider

### ISSUE THREAD

**Issue by pcrockett-pathway** [pomerium/pomerium#629]
**Is your feature request related to a problem? Please describe.**

I have encountered a need to support Ping Identity's [PingOne][1] SSO product.

**Describe the solution you'd like**

Native support for PingOne in Pomerium!

**Describe alternatives you've considered**

Using the generic `oidc` provider (haven't tried it yet, but that's what I'm going to try next).

[1]: https://www.pingidentity.com/en/cloud/pingone.html

**Comment by Lumexralph** [comment]
@pcrockett-pathway Glad, you are using Pomerium! have you tried the `oidc` provider configuration?

Also, I went through their documentation, it seems this might be helpful for you.
https://apidocs.pingidentity.com/pingone/customer/v1/api/auth/p1-a_Authorize/

They implemented the open-id and the only point I think you'll have to be careful is the way the provider URL is formed `auth.pingone.com/{environmentID}/as`

I would like to assume that using `PingOne`, you will be given an `environmentID`, that will form part of the provider URL.

Please try this out and let's know if it helped.

**Comment by pcrockett-pathway** [comment]
I did indeed get a proof-of-concept working on a local VM. I have yet to get it into production, but here's the config I'm using:

```yaml
services: "all"
authenticate_service_url: "https://auth.pomerium-test.pcrockett.local"
certificate_file: "/home/phil/pomerium.crt"
certificate_key_file: "/home/phil/pomerium.key"
certificate_authority_file: "/home/phil/.step/certs/root_ca.crt"
shared_secret: RANDOM_SECRET_HERE
cookie_secret: RANDOM_SECRET_HERE

idp_provider: "oidc"
idp_provider_url: "https://auth.pingone.com/ENVIRONMENT_ID_HERE/as"
idp_client_id: "CLIENT_ID_HERE"
idp_client_secret: "CLIENT_SECRET_HERE"

scope: "openid email"

policy:
  - from: https://pomerium-test.pcrockett.local
    to: https://httpbin.org
    allowed_users:
      - email@example.com
```
