### ISSUE TITLE
Allow regexes in policy source/to configuration directives

### ISSUE THREAD

**Issue by beorn-** [pomerium/pomerium#659]
**Is your feature request related to a problem? Please describe.**

It would nice to have policy routes based on regexed sources such as `https://.*.subdomain.domain.tld/` It would avoid unnecessary complexity in configuration management and improve readability

**Describe the solution you'd like**

Allow regexes in the policy configuration. Could work like this :

```
policy:
  - from:
      match: 'https://host.subdomain.domain.tld/'
       type: 'exact'
    to:
      target: 'http://whatever.domain.tld'
      type: 'string'
    allowed_groups:
        - "admin@whatever"
        - "users@whatever"
  - from:
      match: 'https://.*.subdomain.domain.tld/'
       type: 'regex'
    to:
      target: 'http://whatever.domain.tld'
      type: 'regex_match'
    allowed_groups:
        - "admin@whatever"
        - "users@whatever"

  - from:
      match: 'https://(.*).subdomain2.domain.tld/'
       type: 'regex'
    to:
      target: http://$1.whatever.domain.tld
      type: 'regex_match'
    allowed_groups:
        - "users@whatever"
```

**Describe alternatives you've considered**

The natural solution could be
- Workaround in configuration management
- Service registration (such as consul) based policy with template

**Explain any additional use-cases**

Avoid unnecessary restart/reload, have factorized configuration and avoid unreadable code-generated configurations

**Additional context**

It would be something in the spirit of #615. I took the liberty to hack the policy matching phase it was kind of easy. Then the authorize grpc would not be happy. Which made total sense. That's why i'm asking do you see a show stopper reason to this feature ?
