### ISSUE TITLE
Graphql authorization with Pomerium

### ISSUE THREAD

**Issue by SeenaLibin** [pomerium/pomerium#693]
I am trying to authorize graphql through pomerium. As IDP i have used gitlab and authentication is success. Retrieved pomerium JWT token and refresh token. When trying to call graphql endpoint with Authorization header as Pomerium {jwt} it is not working. Am I doing any thing wrong here? Any one please help me out.

Here is the config file of pomerium

```
authenticate_service_url: auth url
authenticate_callback_path: callback path

# certificate settings:  https://www.pomerium.io/docs/reference/certificates.html
#certificate_file: "./_wildcard.localhost.pomerium.io.pem"
#certificate_key_file: "./_wildcard.localhost.pomerium.io-key.pem"
insecure_server: true

pomerium_debug: true
#identity provider settings : https://www.pomerium.io/docs/identity-providers.html
idp_provider: "gitlab"
idp_provider_url: "gitlab url"
idp_client_id: "client id"
idp_client_secret: "client secret"
idp_scopes: "openid,read_user,read_api,email"

cookie_secret: c6+UHXN0BsB+KA1TGmVYoEDUKqgGKApnsH05wLN0Jsc=
shared_secret: at2ATYsobTnQW1xInYFQTN8UwSWV/nAlQuuSiZvXSFQ=

forward_auth_url: http://pomerium:443

# https://www.pomerium.io/configuration/#policy
policy:
  - from: graphql link
       to: http://dummy
    allowed_users:
      - seena.vp@test.com
```
