### ISSUE TITLE
GitHub provider not known

### ISSUE THREAD

**Issue by krangence** [pomerium/pomerium#710]
## What happened?
Using the latest version of the pomerium helm chart, configuring GitHub as an identity provider. the authenticate pod crash loops with this error
```
{"level":"fatal","error":"internal/identity: github provider not known","time":"2020-05-15T23:39:11Z","message":"cmd/pomerium"} 
```

## What did you expect to happen?
The authenticate pod to run normally.

## How'd it happen?
https://github.com/krangence/k8s-flux/blob/master/base/pomerium/helm-release.yaml
```yaml
config:
  sharedSecret: /snip
  cookieSecret:  /snip
authenticate:
  idp:
    provider: github
    clientID:  /snip
    clientSecret:  /snip
```

## What's your environment like?
Latest helm chart on EKS, with managed node pool
