### ISSUE TITLE
emvoy: policy routes with ports aren't working

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/pomerium#747]
When using a policy route like:

```yaml
policy:
  - from: http://httpdetails.localhost.pomerium.io:9000
    to: http://127.0.0.1:5080
    allow_public_unauthenticated_access: true
```

The envoy configuration is only using the hostname (`httpdetails.localhost.pomerium.io`) in the virtual hosts. This results in no route matches.

We need to stop stripping the port for virtual hosts and domain matches in routes.
