### ISSUE TITLE
Demonstrating websocket support?

### ISSUE THREAD

**Issue by abl** [pomerium/pomerium#77]
**Describe the bug**

I am unable to confirm that websocket support works in 0.0.3.

**To Reproduce**

1. Deployed Pomerium 0.0.3
2. Tried to connect to otherwise-working proxied apps where websocket-based features failed
3. Websockets were unable to connect
4. Added a proxy from https://websocket.corp.my-redacted-domain.com to https://websockets.org
5. Demo was unable to connect to wss://websocket.corp.my-redacted-domain.com/
6, Deployed Kaazing gateway at http://kaazing.corp.my-redacted-domain.com:8000
7. Successfully demonstrated insecure websockets on port 8000
8. Configured a policy to point at local gateway
9. Local gateway cannot connect to websocket (this *might* be a Kaazing issue; it's expecting a particular host value, I think.)

**Expected behavior**

Websocket support works.

**Environment:**

- Pomerium version (retrieve with `pomerium --version`): v0.0.3+41c42f5
- Server Operating System/Architecture/Cloud: Synology x86 NAS running docker

Configuration file(s):

policy.yaml:
```yaml
- from: kaazing.corp.my-redacted-domain.com
  to: http://kaazing.corp.my-redacted-domain.com:8000
  allowed_users:
  - <me>
- from: httpbin.corp.my-redacted-domain.com
  to: https://httpbin.org
  allowed_users:
  - <me>
- from: websocket.corp.my-redacted-domain.com
  to: https://websocket.org/
  allowed_users:
  - <me>
```

Logs(s):

There appear to be no logs associated with websocket connection attempts.

**Additional context**

Pomerium is bound directly to port 443.

Happy to add any Pomerium folks who want to try these routes to my allowed users (and share with them the actual URLs involved.) This is not a production system so I'm happy to make sweeping changes.

Connecting to wss://httpbin.corp.my-redacted-domain.com/anything yields an error 200; curiously, nothing is in the logs for this request. `POMERIUM_DEBUG` is true and `LOG_LEVEL` is default; l I am seeing DBG logs.
