### ISSUE TITLE
JWT Audiences

### ISSUE THREAD

**Issue by simbaja** [pomerium/pomerium#833]
## What happened?

The audience for the jwt isn't working as expected.  Let's use forwardauth mode as an example.  The jwt audience field appears to be constructed by using the authenticate url host, the forward auth host, and the redirect host.  So, in this case, let's assume:

Authenticate: sso.example.com
Forward Auth: pomerium.localhost
Redirect: httpbin.example.com

This works fine for the first request you make (i.e. to httpbin).  But, let's say you have another service that you would like to access (let's say whoami.example.com).  When you attempt to go to that service, it fails saying the host isn't in the audience.

## What did you expect to happen?

I'd hope to implement single signon so that the same session can apply to anything listed under the policy (at least to the extent they're part of the same domain).

## How'd it happen?

1. Went to httpbin.example.com
2. Logged in to the identity provider, received pomerium session
3. Redirected to httpbin.example.com -> access allowed
4. Navigated to whoami.example.com -> access denied

## What's your environment like?

- Pomerium 0.9.0
- Traefik 2.2.1
- Linux/Docker
- Keycloak (through OIDC)

## What's your config.yaml?

```
---

cookie_secret: {{ pomerium_cookie_secret }}
cookie_domain: {{ domain_name }}

idp_provider: "oidc"
idp_client_id: "{{ keycloak_auth_client_id }}"
idp_client_secret: "{{ keycloak_auth_client_secret }}"
idp_scopes: openid profile email offline_access web-auth
idp_provider_url: https://idp.{{ domain_name }}/auth/realms/master

log_level: info

insecure_server: false
certificate_file: /pomerium/cert.pem
certificate_key_file: /pomerium/privkey.pem
forward_auth_url: https://pomerium
authenticate_service_url: https://sso.{{ domain_name }}

#NOTE: need to map values for user and groups if using Keycloak
jwt_claims_headers:
  - user
  - email
  - name
  - given_name
  - family_name
  - groups

policy:
  - from: https://whoami.{{ domain_name }}
    to: http://whoami
    allowed_groups:
      - Administrator
  - from: https://httpbin.{{ domain_name }}
    to: http://httpbin
    allowed_groups:
      - Administrator
```

## What did you see in the logs?

```logs

```

**Comment by travisgroth** [comment]
Hi,

Our usual test setup for forward auth is with nginx and multiple routes work fine as you'd expect. Sample policy:

```yaml
  policy:
      - from: https://httpbin.localhost.pomerium.io
        to: https://httpbin.org
        allowed_domains: 
          - pomerium.io
      - from: https://httpbin2.localhost.pomerium.io
        to: https://httpbin.org
        allowed_domains: 
          - pomerium.io
```

Resulting jwt snippets:

```json
{
  "at_hash": "831f07b55fbd6d32",
  "aud": [
    "authenticate.localhost.pomerium.io",
    "httpbin.localhost.pomerium.io",
    "httpbin.localhost.pomerium.io",
    "forwardauth.localhost.pomerium.io"
  ],
```

```json
{
  "at_hash": "831f07b55fbd6d32",
  "aud": [
    "authenticate.localhost.pomerium.io",
    "httpbin2.localhost.pomerium.io",
    "httpbin2.localhost.pomerium.io",
    "forwardauth.localhost.pomerium.io"
  ],
```

You're correct that the same session token/cookie is not usable for multiple routes.  This will change in the future but, in a normal browser session, this should be inconsequential.  

The behavior you're describing shouldn't happen.  In your flow, the request to `whoami.example.com` will redirect you to `sso.example.com` and then redirect back to `whoami.example.com` and get a new cookie with an appropriate audience for the new route.

If you had a misconfiguration in the traefik forward auth configuration, you might wind up with a cookie for the wrong audience but otherwise I don't see how you'd wind up in this scenario.

**Comment by simbaja** [comment]
I can think of two possible causes based on your notes:

1. Perhaps the cookie_domain setting isn't set correctly.  In the above, it's set to the base domain name (i.e. example.com).  
2. The forward-auth configuration in Traefik is set as a single middleware, not a middleware-per-service.  The same middleware is applied to all protected services.  The relevant sections of the config are:

Foward auth definition:
```
    pomerium-auth:
      forwardAuth:
        address: https://pomerium
        tls:
          insecureSkipVerify: true
        trustForwardHeader: true
        authResponseHeaders:
          - x-pomerium-claim-user
          - x-pomerium-claim-email
          - x-pomerium-claim-name
          - x-pomerium-claim-given_name
          - x-pomerium-claim-family_name
          - x-pomerium-claim-groups
          - x-pomerium-jwt-assertion
```
Pomerium service definition:

```
services:
  pomerium:
    image: pomerium/pomerium:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{ cert_path}}/{{ cert_full_chain_file }}:/pomerium/cert.pem:ro
      - {{ cert_path}}/{{ cert_key_file }}:/pomerium/privkey.pem:ro
      # Mount your config file : https://www.pomerium.io/docs/reference/reference/
      - {{ pomerium_config_path}}/config.yml:/pomerium/config.yaml:ro
      - {{ pomerium_lib_path }}:/data:rw
    networks:
      - internal
      - traefik_public
    environment:
      - TZ= {{ timezone }}
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        ## HTTP Routers
        - "traefik.http.routers.pomerium-rtr.entrypoints=https"
        - "traefik.http.routers.pomerium-rtr.rule=Host(`sso.{{ domain_name }}`,`pomerium.{{ domain_name}}`)"
        - "traefik.http.routers.pomerium-rtr.tls=true"
        ## Middlewares
        - "traefik.http.routers.pomerium-rtr.middlewares=chain-no-auth@file"
        ## HTTP Services
        - "traefik.http.routers.pomerium-rtr.service=pomerium-svc"
        - "traefik.http.services.pomerium-svc.loadbalancer.server.port=443"
        - "traefik.http.services.pomerium-svc.loadbalancer.server.scheme=https"
```

Sample service definition:

```
  httpbin:
    # A container that exposes an API to show its IP address
    image: kennethreitz/httpbin:latest
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0    
    networks:
      - internal
      - traefik_public
    environment:
      - TZ= {{ timezone }}
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        ## HTTP Routers
        - "traefik.http.routers.httpbin-rtr.entrypoints=https"
        - "traefik.http.routers.httpbin-rtr.rule=Host(`httpbin.{{ domain_name }}`)"
        - "traefik.http.routers.httpbin-rtr.tls=true"
        ## Middlewares
        - "traefik.http.routers.httpbin-rtr.middlewares=chain-pomerium-forward-auth@file"
        ## HTTP Services
        - "traefik.http.routers.httpbin-rtr.service=httpbin-svc"
        - "traefik.http.services.httpbin-svc.loadbalancer.server.port=80"
        - "traefik.http.services.httpbin-svc.loadbalancer.server.scheme=http"
```
