### ISSUE TITLE
authenticate_service_url should not be allowed to have overlap with routes

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#869]
## What happened?

My friend is setting up a new Pomerium server and did not realize the authenticate_service_url should not be the same with one of the routes. I.e. something like this is broken but the validation doesn't prevent it:

```
authenticate_service_url: https://foo.example.com

policy:
  - from: https://foo.example.com
    to: ...
```

## What did you expect to happen?

The config validation should error out here.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint):
- Server Operating System/Architecture/Cloud:

## What's your config.yaml?

NA

## What did you see in the logs?

NA
