### ISSUE TITLE
hot reload of policy results in 503

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#870]
## What happened?

Hot reloading fails (returns a `503`) if the source URL changes for a given policy route's allowed user domains.

## What did you expect to happen?

I expected to be able to hot reload policy.

## How'd it happen?

Have a policy like so. 

```yaml
policy:
  - from: https://httpbin.imac.bdd.io
    to: https://httpbin.org
    allowed_domains:
      - pomerium.com
```
Change the policy slightly

```diff
policy:
  - from: https://httpbin.imac.bdd.io
    to: https://httpbin.org
    allowed_domains:
      - pomerium.com
+      - gmail.com
```

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): `pomerium/0.9.0 (+https://wwww.pomerium.io; 914b952; go1.14.3)`
- Server Operating System/Architecture/Cloud: docker compose

## What's your config.yaml?

See above.
