### ISSUE TITLE
Prefix Paths aren't working with Traefik Ingress

### ISSUE THREAD

**Issue by Vad1mo** [pomerium/pomerium#873]
I can not make v0.9 work with prefix/regex. No matter what I try path/regex/prefix aren't working with traefik. From the behavior it looks like the first rule doesn't get triggered.
```yaml
  - allowed_users:
    - xxx@gmail.com
    from: https://whoami.stage.example.com
    # regex: "^/(system|ui)/.*$"
    prefix: /system
    to: http://whoami
  - allow_public_unauthenticated_access: true
    from: https://whoami.stage.example.com
    to: http://whoami
```

The following screenshot is what the proxy receives from traefik. 

![image (2)](https://user-images.githubusercontent.com/1492007/84407062-9fde0700-ac0a-11ea-9d7e-8f12a96b3721.png)
