### ISSUE TITLE
Pomerium used DNS query for hostnames in /etc/hosts

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#88]
I'm running Pomerium in docker without IPv6 configured.

The domain name I used as `AUTHENTICATE_SERVICE_URL` only have `AAAA` record. This should normally be fine because I can either set `hostname` on the container to the hostname, or add `extra_hosts` to add an internal IPv4 address.

I'm setting the hostname of the docker container running Pomerium to `example.com`, but I'm seeing this in the log:

```
5:48AM ERR proxy: error redeeming authorization code error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp [2600:XXXX:XXXX:XXXX]:443: connect: cannot assign requested address\"" ip=172.29.0.1 req_id=58d3c18e-a357-0c09-3f57-adfb47017376 user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
```

The IPv6 address in the log is the AAAA record of `example.com`

**Comment by yegle** [comment]
It looks like setting `GODEBUG=netdns=cgo` will correctly resolve the domain name to the internal IP address assigned to the container, but I'm getting error at start up time:

```
6:13AM ERR http: TLS handshake error from 172.29.0.13:38008: remote error: tls: bad certificate addr=:https
```

I'm very confused right now. Maybe I'm confused on what `AUTHENTICATE_SERVICE_URL` should be?

**Comment by yegle** [comment]
Made some progress on this issue. Apparently the `/etc/nsswitch.conf` file is missing from the image. Mounting this file to the container as volume fixed the issue of trying to connect to the domain's IPv6 address. Reference: https://github.com/golang/go/issues/22846

Now I'm still having the issue described in https://github.com/pomerium/pomerium/issues/88#issuecomment-485336725. I have no idea why pomerium will attempt to connect to the container's 443 port without the hostname I specified.

**Comment by yegle** [comment]
OK I think this is all my fault. I should've used the `fullchain.pem` as the certificate, as Let's Encrypt's README suggests.

Some suggestion:

1. Include `nsswitch.conf`
2. Make it easier to troubleshoot when someone accidentally used the `cert.pem` from Let's Encrypt.

**Comment by desimone** [comment]
@yegle where you able to get everything working? I'd like to make the user experience for this better. 

- As you mentioned, the docker container we use does not have nsswitch built in https://github.com/gliderlabs/docker-alpine/issues/367 
- Did you set `CERTIFICATE_AUTHORITY`? I use LE certificates but I usually set `CERTIFICATE_AUTHORITY`/CERTIFICATE_AUTHORITY_FILE`, vs using the full_chain. But it makes sense that either should work. 
- Do you mind posting a (redacted for sensitive details) environmental variables and configuration files?


Thanks!

**Comment by yegle** [comment]
@desimone 
Yes I figured everything out (although I miss a feature, will file a separate FR bug).

To answer your question:
* Right but since Pomerium is a reverse proxy, and reverse-proxy the requests to other containers is a common use case. I would suggest to fix it in Pomerium's official image.
* No I did not set `CERTIFICATE_AUTHORITY`. Instead I followed the readme generated by `certbot` and used the `fullchain.pem` file:

```
`fullchain.pem`: the certificate file used in most server software.
```

The final config I used is

```
  pomerium:                                                                     
    image: pomerium/pomerium:latest
    container_name: pomerium
    restart: unless-stopped
    dns: 172.29.1.1
    hostname: example.com
    environment:
      - POMERIUM_DEBUG=true
      - SERVICES=all
      - IDP_PROVIDER=google
      - IDP_PROVIDER_URL=https://accounts.google.com
      - IDP_CLIENT_ID=XXX.apps.googleusercontent.com
      - IDP_CLIENT_SECRET=XXX
      - AUTHENTICATE_SERVICE_URL=https://example.com
      - AUTHORIZE_SERVICE_URL=https://example.com
      - SHARED_SECRET=XXX
      - COOKIE_SECRET=XXX
      - CERTIFICATE_FILE=/etc/letsencrypt/live/example.com/fullchain.pem
      - CERTIFICATE_KEY_FILE=/etc/letsencrypt/live/example.com/privkey.pem
      - POLICY_FILE=/pomerium/policy.yaml
    volumes:
      - /opt/letsencrypt/etc:/etc/letsencrypt:ro
      - /opt/letsencrypt/var:/var/lib/letsencrypt:ro
      - /opt/pomerium/policy.yaml:/pomerium/policy.yaml:ro
      - /opt/pomerium/nsswitch.conf:/etc/nsswitch.conf:ro
    ports:
      - 443:443
```

**Comment by yegle** [comment]
Should nsswitch.conf be added to the container?

**Comment by desimone** [comment]
Sorry @yegle I mean't to split this issue. PR #96 (hopefully) resolves your concerns about better documentation around certificates.

#97 covers `nsswitch.conf`

**Comment by yegle** [comment]
Looks like there's a regression here. I added a long list of `extra_hosts` to my docker-compose file and Pomerium still uses DNS to get the IP address.

**Comment by cuonglm** [comment]
@yegle would you mind giving your redacted configuration? With current master docker image, I got:

```
$ sudo docker run --rm -it --add-host authenticate.localhost.pomerium.io:127.0.0.100 --entrypoint=sh pomerium/pomerium:master
/pomerium # ping -c 4 authenticate.localhost.pomerium.io
PING authenticate.localhost.pomerium.io (127.0.0.100): 56 data bytes
64 bytes from 127.0.0.100: seq=0 ttl=64 time=0.108 ms
64 bytes from 127.0.0.100: seq=1 ttl=64 time=0.109 ms
64 bytes from 127.0.0.100: seq=2 ttl=64 time=0.092 ms
64 bytes from 127.0.0.100: seq=3 ttl=64 time=0.096 ms

--- authenticate.localhost.pomerium.io ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.092/0.101/0.109 ms
```

**Comment by yegle** [comment]
I just tested with this config:

```
insecure_server: true
cookie_secret: XMk2G6qsDX3abCo9jUhIa8BDu/0fIpEyLa5Kb8Ld2h4=
authenticate_service_url: https://example.com
idp_provider: google
idp_client_id: test
idp_client_secret: test
policy:
    - from: https://example.com
      to: http://does-not-exist.com
```

Once you start the container, you should see DNS queries from the container to does-not-exist.com:

```
docker run --add-host does-not-exist.com:127.0.0.1 --dns 172.29.1.1 --network infrastructure_network --mount type=bind,source=$PWD/config.yaml,target=/pomerium/config.yaml --name pomerium-test pomerium/pomerium
```

@cuonglm your test is using ping not pomerium, there's some complexities with a Go binary (this bug was initially reported due to the missing of `/etc/nsswitch.conf` in the container which caused some Go binary to always use DNS and ignore `/etc/hosts`)
