### ISSUE TITLE
Envoy Pomerium + Istio not working

### ISSUE THREAD

**Issue by jeffhubLR** [pomerium/pomerium#983]
## What happened?

After attempting to follow this writeup: https://www.pomerium.io/configuration/examples.html#istio
I further simplified the configuration to a simple pass-thru proxy (allow_public_unauthenticated_access: true)

Requests to the proxied resource always fail with 
"response-code":500,"response-code-details":"ext_authz_error"

## What did you expect to happen?
Requests should succeed

## How'd it happen?

1. Started with a K8s 1.17.3 cluster running Istio 1.4.7
2. Created Pomerium namespace and enabled istio injection
   ```
   cat <<EOF | kubectl create -f -
   apiVersion: v1
   kind: Namespace
   metadata:
     name: pomerium
     labels:
       istio-injection: enabled
   EOF
   ```
3. Deployed Pomerium with the following command: `helm install pomerium pomerium/pomerium --namespace pomerium --version 9.3.0 --values values.yaml
    ```
    image:
      tag: v0.8.3
    
    config:
      rootDomain: ops.my.domain.com
      # Disable Pomerium TLS in favor of Istio-provided TLS via sidecars
      generateTLS: true # Needed so the initial certificates exist, even though they aren't used
      insecure: true
      sharedSecret: "REDACTED"
      cookieSecret: "REDACTED"
      generateSigningKey: false
      extraOpts:
        jwt_claims_headers: email,name,groups,picture
        idp_scopes: "openid profile email offline_access groups"
      policy:
        - from: https://nginx.ops.my.domain.com
          to: http://nginx.pomerium.svc.cluster.local:80
          timeout: 30s
          allow_public_unauthenticated_access: true
    proxy:
      signingKey: "REDACTED"
   ```
4. Deployed nginx
   ```
   helm repo add bitnami https://charts.bitnami.com/bitnami
   helm install nginx bitnami/nginx --namespace pomerium
   ```
5. Deployed cert-manager Certificate (not material to this issue, but needed for below Istio Gateway)
   ```
    cat <<EOF | kubectl create -f -
    apiVersion: cert-manager.io/v1alpha2
    kind: Certificate
    metadata:
      name: pomerium-cert
      namespace: istio-system
    spec:
      secretName: pomerium-cert
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
      commonName: authenticate.ops.my.domain.com
      dnsNames:
        - authenticate.ops.my.domain.com
        - nginx.ops.my.domain.com
   ```
6. Deployed necessary Istio configuration
   ```
    cat <<EOF | kubectl create -f -
    apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: nginx-virtual-service
      namespace: pomerium
    spec:
      gateways:
        - pomerium-gateway
      hosts:
        - nginx.ops.my.domain.com
      http:
        - route:
            - destination:
                host: pomerium-proxy
                port:
                  number: 80
   ```
   ```
    cat <<EOF | kubectl create -f -
        apiVersion: networking.istio.io/v1alpha3
    kind: Gateway
    metadata:
      name: pomerium-gateway
      namespace: pomerium
    spec:
      selector:
        istio: ingressgateway
      servers:
        - port:
            number: 80
            name: http
            protocol: HTTP
          hosts:
            - authenticate.ops.my.domain.com
            - nginx.ops.my.domain.com
          tls:
            httpsRedirect: true
        - port:
            number: 443
            protocol: HTTPS
            name: https
          tls:
            mode: SIMPLE
            credentialName: pomerium-cert
          hosts:
            - authenticate.ops.my.domain.com
            - nginx.ops.my.domain.com
    ---
    apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: authenticate-virtual-service
      namespace: pomerium
    spec:
      gateways:
        - pomerium-gateway
      hosts:
        - authenticate.ops.my.domain.com
      http:
        - route:
            - destination:
                host: pomerium-authenticate
   ```
7. Setup DNS (by using External-DNS, not in scope for this issue)
8. Requested https://nginx.ops.my.domain.com (both in a browser and via curl), receiving an HTTP 500 error instead of the expected 200 OK.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): v0.9.2
- Helm Chart version: 10.0.2
- Server Operating System/Architecture/Cloud: Kubernetes 1.17.3, Istio 1.4.7

## What did you see in the logs?

Pomerium-Authorize
```
{"level":"info","service":"authorize","request-id":"0fd11ded-153c-44c5-96d1-b4c7d1184231","check-request-id":["af2eeb45-043b-4882-b17a-ae1931d632cb"],"method":"GET","headers":{":authority":["nginx.ops.my.domain.com"],":method":["GET"],":path":["/"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Cache-Control":["no-cache"],"Content-Length":["0"],"Pragma":["no-cache"],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-Site":["cross-site"],"Sec-Fetch-User":["?1"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"],"X-B3-Parentspanid":["4e5cf27fe3d0daac"],"X-B3-Sampled":["0"],"X-B3-Spanid":["8aa7d7d48d24d9b9"],"X-B3-Traceid":["05a772abcdc297cb4e5cf27fe3d0daac"],"X-Envoy-External-Address":["100.120.31.192"],"X-Forwarded-For":["100.120.31.192"],"X-Forwarded-Proto":["https"],"X-Request-Id":["af2eeb45-043b-4882-b17a-ae1931d632cb"]},"path":"/","host":"nginx.ops.my.domain.com","query":"","allow":true,"session-expired":false,"deny-reasons":[],"email":"","groups":[],"time":"2020-06-23T15:07:36Z","message":"authorize check"}
```
Pomerium-Proxy
```
{"level":"debug","service":"envoy","name":"http","time":"2020-06-23T15:07:36Z","message":"\"[C1][S7252674134398121597] request headers complete (end_stream=true):\\n\\':authority\\', \\'nginx.ops.my.domain.com\\'\\n\\':path\\', \\'/\\'\\n\\':method\\', \\'GET\\'\\n\\'pragma\\', \\'no-cache\\'\\n\\'cache-control\\', \\'no-cache\\'\\n\\'upgrade-insecure-requests\\', \\'1\\'\\n\\'user-agent\\', \\'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36\\'\\n\\'accept\\', \\'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\\'\\n\\'sec-fetch-site\\', \\'cross-site\\'\\n\\'sec-fetch-mode\\', \\'navigate\\'\\n\\'sec-fetch-user\\', \\'?1\\'\\n\\'sec-fetch-dest\\', \\'document\\'\\n\\'accept-encoding\\', \\'gzip, deflate, br\\'\\n\\'accept-language\\', \\'en-US,en;q=0.9\\'\\n\\'x-forwarded-for\\', \\'100.120.31.192\\'\\n\\'x-forwarded-proto\\', \\'https\\'\\n\\'x-envoy-external-address\\', \\'100.120.31.192\\'\\n\\'x-request-id\\', \\'af2eeb45-043b-4882-b17a-ae1931d632cb\\'\\n\\'content-length\\', \\'0\\'\\n\\'x-b3-traceid\\', \\'05a772abcdc297cb4e5cf27fe3d0daac\\'\\n\\'x-b3-spanid\\', \\'8aa7d7d48d24d9b9\\'\\n\\'x-b3-parentspanid\\', \\'4e5cf27fe3d0daac\\'\\n\\'x-b3-sampled\\', \\'0\\'\""}
{"level":"info","service":"envoy","upstream-cluster":"","method":"GET","authority":"nginx.ops.my.domain.com","path":"/","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36","referer":"","forwarded-for":"100.120.31.192","request-id":"af2eeb45-043b-4882-b17a-ae1931d632cb","duration":5.545776,"size":0,"response-code":500,"response-code-details":"ext_authz_error","time":"2020-06-23T15:07:37Z","message":"http-request"}
```

## Additional context

After asking in Slack and receiving help from @desimone and @bjoernw it was recommended I downgrade to Pomerium v0.8.3 and helm chart v9.3.0. Downgrading to Pomerium v0.8.3 using helm chart v9.3.0 results in a working setup.
